### DISCUSSION TITLE
Adding a custom flex directory type from a plugin

### DISCUSSION THREAD

**Discussion by ghost** [getgrav/grav#3118] [Development] [answered]
I'd like to add a custom `product` flex directory type from a plugin. I created a `products.yaml` blueprint that works when I store and enable it under `user/data/flex-objects/products.yaml`, so the blueprint itself is fine. Here's what it looks like:

```yaml
title: Products
description: Simple product directory.
type: flex-objects

form:
  fields:
    name:
      type: text
      label: Name
    price:
      type: text
      label: Price

config:
  data:
    storage: user-data://flex-objects/products.json
  admin:
    router:
      path: '/products'
    list:
      fields:
        name:
          link: edit
        price:
    menu:
      list:
        route: '/products'
        title: Products
        icon: fa-address-card-o
        authorize: ['admin.users', 'admin.accounts', 'admin.super']

```

However, I can't seem to add it from a plugin. I know I have to use the `onFlexInit` event, but nothing happens. Here's the plugin code:

```php
<?php
namespace Grav\Plugin;

use Composer\Autoload\ClassLoader;
use Grav\Common\Plugin;
use Grav\Framework\Flex\FlexDirectory;

class ShopPlugin extends Plugin
{
    public static function getSubscribedEvents(): array
    {
        return [
            'onPluginsInitialized' => [
                ['onPluginsInitialized', 0],
            ]
        ];
    }

    public function onPluginsInitialized(): void
    {
        $this->enable([
            'onFlexInit' => ['onFlexInit', 0]
        ]);
    }

    public function onFlexInit($event){
        $directory = new FlexDirectory('products', 'plugins://shop/blueprints/flex-objects/products.yaml', ['enabled'=>true]);

        $flex = $event['flex'];
        $flex->addDirectory($directory);
    }
}
```

What should I do to make it work?
