### ISSUE TITLE
CropZoom and responsive image

### ISSUE THREAD

**Issue by julienchazal** [getgrav/grav#1033]
Hello

I did not manage to cropZoom an uploaded image and then apply responsive method on it.
Here's relevant parts of my template : 

`{% set showcase_image = page.media.images|first.cropZoom(1024,620).derivatives(320, 1024, 200) %}`

`{{ showcase_image.html() }}`

Generated HTML : 
`<img src="/images/9/0/b/5/9/90b59b9a55e4c3d573fd44f983c839e9d05c90c1-vitechheader1.jpeg" srcset="/images/9/a/7/1/8/9a7185c769b328ec031887ffb9c6d9591b3653e3-vitechheader1.jpeg 320w, /images/e/2/5/0/d/e250d49528fa707229a8dfaefeaa1bea0ccae5cf-vitechheader1.jpeg 520w, /images/e/c/f/e/4/ecfe4a3e7f0c55acbc86bbd25cc0ac324dbf1495-vitechheader1.jpeg 720w, /images/1/b/e/8/0/1be80ed233ca8e2eb1fa03f8c9a6627799602d20-vitechheader1.jpeg 919w, /images/9/0/b/5/9/90b59b9a55e4c3d573fd44f983c839e9d05c90c1-vitechheader1.jpeg 1600w" sizes="100vw">`

So the image is responsive but not cropped.
Any ideas please ?

Thx !

**Comment by rhukster** [comment]
I know there is a PR in progress that impacts derivatives.  Could you possibly test with that PR?

**Comment by fredrikekelund** [comment]
@julienchazal the PR is #1035. However, even with that patch, you'd still need to reverse the order of the methods you call - so `derivatives` comes before `cropZoom`

**Comment by julienchazal** [comment]
Yes it's working thanks @fredrikekelund !
But i don't understand why when i set `derivatives(320,1024)` there's a `srcet` for `1600w` ?

**Comment by rhukster** [comment]
Good news!   I still need to do some more testing myself, but that's positive news.  Glad to hear that @fredrikekelund 's PR worked for you!

**Comment by fredrikekelund** [comment]
@julienchazal the original image size is always included in the `srcset` as well, could that be the 1600w entry?

**Comment by julienchazal** [comment]
@fredrikekelund thx for your answer ;)

**Comment by julienchazal** [comment]
@rhukster is it possible to apply derivatives and crop to a pagemediaselect field ?

Excerpt from my blueprint yml :
```
equipements:
          type: tab
          title: Equipements
          fields:
            header.equipements:
              name: equipements
              type: list
              label: Equipement

              fields:
                .image:
                  type: pagemediaselect
                  label: Photo 
                .title:
                  type: text
                  label: Titre
                .desc:
                  type: text
                  label: Description
```

My template : 
```
{% for equipement in page.header.equipements %}
           <div class="equipement">
            {% if equipement.image %}
            <img class="equipement__img" src="{{ base_url }}/user/pages/01.home/_equipements/{{ equipement.image }}" alt="vitech" />
            {% endif %}
           <div class="equipement__inner">
                {% if equipement.title %}
                <h4 class="equipement__title">{{ equipement.title }}</h4>
                {% endif %}
                {% if equipement.desc %}
                <p class="equipement__desc">{{ equipement.desc }}</p>
                {% endif %}
           </div>
           </div>
    {% endfor %}
```
