### ISSUE TITLE
Increase session timout

### ISSUE THREAD

**Issue by Tamriel** [getgrav/grav#1050]
I think, one can sett the session timeout in `system/config/system.yaml` to a maximum of 9999.
I would like to increase that to weeks or "forever".

**Comment by rhukster** [comment]
There's really no simple way to set a session timeout to 'forever' because the the session cookie needs to take a unix timestamp (date in seconds).  The only real option is to make that number bigger.  

We can look at increasing this available option in the admin, but in the meantime you can edit the value directly in `user/config/system.yaml`.  For example `99999999` is over 3 years.

**Comment by rhukster** [comment]
Actually the timeout has no maximum even in the admin:

```
   session.timeout:
                    type: text
                    size: small
                    append: NICETIME.SECOND_PLURAL
                    label: PLUGIN_ADMIN.TIMEOUT
                    help: PLUGIN_ADMIN.TIMEOUT_HELP
                    validate:
                        type: number
                        min: 1
```

Where are you seeing a maximum?
