### ISSUE TITLE
Pages Field in Blueprint: possible to restrict pages to children of a specific folder?

### ISSUE THREAD

**Issue by jozilla** [getgrav/grav#1093]
I'm trying to have a  'related' field in my Blueprint using the Pages field:

```
header.related:
    type: pages
    label: Related news items
    size: medium
    multiple: true
    selectize: true
    show_all: false
    show_root: false
    show_modular: false
```

Since this is for linking a news article to other related news articles, I would like to limit the pages that can be selected in this field to only the pages in the `/news/` group. Is this possible? Or will this always show all pages?

Thanks!

**Comment by jozilla** [comment]
Actually this is possible in Bolt CMS, something like this would be great in Grav too. Here are the docs for Bolt: https://docs.bolt.cm/3.1/fields/select.
And the code: 
        ```
somevalue:
            type: select
            values: pages/title
            filter: { categories: news }
```
