### ISSUE TITLE
Modular Page Blueprint 'type: file' crashes on page save

### ISSUE THREAD

**Issue by fredericmohr** [getgrav/grav#1100]
I have a problem with adding a file upload in a modular page blueprint. 

**First issue** (already resolved via gitter.im)

When adding `type: file` to a modular blueprint, I got the following error message:

`E_ERROR - Maximum function nesting level of '100' reached, aborting!`

Which could be solved by adding `xdebug.max_nesting_level = 256` to `/etc/php5/apache2/php.ini` and restarting apache2.

**The second issue** 

This came right afterwards. When uploading a file and saving the page, the following error is shown.

```
0 - An exception has been thrown during the rendering of a template ("Template "modular/image-and-text.html.twig" is not defined.") in "forms/fields/file/file.html.twig" at line 33
```

The file `modular/image-and-text.html.twig` exists under `theme@templates/modular/` and the page can be rendered. The error only appears in the admin panel when I upload something and try to save it.

**Stacktrace:**

```
[2016-10-11 11:15:13] grav.CRITICAL: An exception has been thrown during the rendering of a template ("Template "modular/image-and-text.html.twig" is not defined.") in "forms/fields/file/file.html.twig" at line 33. - Trace: 
#0 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(211): Twig_Template->displayBlock('input', Array, Array) 
#1 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_088181b3b7102c19efc64bbc00b7fc97b6cc4e513193a7726d8a066d0e759b35->block_group(Array, Array) 
#2 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(139): Twig_Template->displayBlock('group', Array, Array) 
#3 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_088181b3b7102c19efc64bbc00b7fc97b6cc4e513193a7726d8a066d0e759b35->block_contents(Array, Array) 
#4 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(66): Twig_Template->displayBlock('contents', Array, Array) 
#5 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_088181b3b7102c19efc64bbc00b7fc97b6cc4e513193a7726d8a066d0e759b35->block_field(Array, Array) 
#6 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(50): Twig_Template->displayBlock('field', Array, Array) 
#7 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_088181b3b7102c19efc64bbc00b7fc97b6cc4e513193a7726d8a066d0e759b35->doDisplay(Array, Array) 
#8 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#9 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(32): Twig_Template->display(Array, Array) 
#10 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_7279b3511f70c26b9d33325d26cb35ae1fbd0e6bb55aff99f8c5df33a563abeb->doDisplay(Array, Array) 
#11 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#12 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(48): Twig_Template->display(Array) 
#13 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_16ed529b0095031f63d784e957cee88607cf44752b4f2f062307f1bc447183f5->doDisplay(Array, Array) 
#14 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#15 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(145): Twig_Template->display(Array) 
#16 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_76cceb33f42a9b9208f8a0a53ddc7dbe2fb5ea796618da3d1dca7ff4a2ca658b->doDisplay(Array, Array) 
#17 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#18 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(71): Twig_Template->display(Array) 
#19 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_1f44af2aa702fee6bd5f8ebe0bcfc2bf57c4e80559f9d2092c6fd49f1994de0b->doDisplay(Array, Array) 
#20 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) 
#21 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(501): Twig_Template->display(Array) 
#22 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_3b66eb888bd57d93786c60178214c2b06c6c2e983991713845f783bfb3608340->block_content(Array, Array) 
#23 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(205): Twig_Template->displayBlock('content', Array, Array) 
#24 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_1b753b81326bb253c7135229637816457cefd18c6eacdd84c0c454f03f57b936->block_page(Array, Array) 
#25 /var/www/grav-dev/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(158): Twig_Template->displayBlock('page', Array, Array
```

**Blueprint**

For completeness, here's the blueprint (`theme@blueprints/modular/image-and-text.yaml`)
```
title: Image and Text
@extends: default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    name:
                      default: modular/image-and-text
                      @data-options: '\Grav\Common\Page\Pages::modularTypes'
            overrides:
              fields:
                header.template:
                  default: modular/image-and-text
                  @data-options: '\Grav\Common\Page\Pages::modularTypes'

        imageandtext:
          type: tab 
          title: Image and Text
          fields:
            header.custom_file:
              type: file
              label: Upload File
              multiple: false
              destination: 'theme@:images/featured/'
              random_name: false
              avoid_overwriting: false
              filesize: 0
              accept:
                - image/*
```

I followed the docs at: https://learn.getgrav.org/forms/blueprints/how-to-add-file-upload
