### ISSUE TITLE
Improve using Blueprints

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav#1137]
While discussing this with @mahagr and @w00fz we decided we need to make the business of actually using custom blueprints with custom data files a simpler process.

**Comment by matthew-dean** [comment]
Also, the way you get extremely-nested YAML with blueprints I think is problematic. Lots of repeated `fields:` keys.

**Comment by mahagr** [comment]
You only nest fields when you are grouping fields together. And there's no other way to do it than to create nested blueprints -- basically in the same way as you would nest HTML. In fact the mapping between YAML and HTML is 1:1.

**Comment by matthew-dean** [comment]
Okay. It's just that this pattern was visually a little eye-blurring:
```
      fields:
        advanced:
          fields:
            overrides:
              fields:
```
Maybe it's because nesting is easier to visually follow in HTML than YAML.
