### ISSUE TITLE
Unable to perform case-insensitive ordering of a collection when the order is based on a custom header field.

### ISSUE THREAD

**Issue by parcand** [getgrav/grav#1169]
The `$sort_flags` parameter is always set to `SORT_REGULAR ` when ordering a collection based on a custom header field.

This is quite problematic since there are many situations where data is expected to be sorted case-insensitively. 

Adding an optional `sort_flags` parameter to the `order` method of the `Grav\Common\Page\Collection` class could help solve that issue.

**Comment by flaviocopes** [comment]
Ok I've done a bit of research into this, and came up with this PR https://github.com/getgrav/grav/issues/1173

The thing to note is this: If the `intl` PHP extension is loaded, only these flags are available:
https://secure.php.net/manual/en/collator.asort.php as we use PHP's Collator class to sort.

Otherwise, if `intl` is not loaded, you can use the PHP standard sorting flags (https://secure.php.net/manual/en/array.constants.php) and add

```
content:
    ....
    order:
        by: header.title
        sort_flags:
            - SORT_NATURAL
            - SORT_FLAG_CASE
```

to order case insensitive.
