### ISSUE TITLE
Sorting collections by a date field (e.g., YYYY-MM-DD) does not give expected results.

### ISSUE THREAD

**Issue by erichgoldman** [getgrav/grav#1199]
I am trying to sort a collection based on a date field, which is defined in `YYYY-MM-DD` format. The sorting works on regular text fields, but it is acting odd on these date fields. The date fields are simply string so I would not expect special behavior.

e..g, given:
```
May 4, 2016 ==> 2016-05-04
Jan 1, 2016 ==> 2016-01-01
```
We would expect Jan 1 to be sorted so it is before May 4.

----

Here is my blueprint at: `[siteroot]/user/blueprints/pages/event.yaml`
```
title: Event

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        event:
          type: tab
          title: Event Details

          fields:
            header.title:
              type: text
              label: Enter the event title
              default: 'Title'
              validate:
                required: true

            header.startdate:
              type: date
              label: Enter the start date
              validate:
                required: true

            header.enddate:
              type: date
              label: Enter the end date
              validate:
                required: true

            header.description:
              type: textarea
              label: Enter the event description
              default:
              validate:
                required: true

```

Which works correctly in the admin:

![image](https://cloud.githubusercontent.com/assets/3157148/21070683/92fb1be8-be58-11e6-9f64-d8a127804f33.png)

----

I then created a template to show the list of events at: `[siteroot]/user/themes/antimatter/templates/eventlist.html.twig`

```
{% embed 'partials/base.html.twig' %}

{% block content %}

{{ page.content }}

<h1>Sort by Star Date</h1>
<h2>order('header.startdate', 'desc')</h2>

{% set eventsRaw = page.children() %}
{% set events = eventsRaw.order('header.startdate', 'desc') %}

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  {% for p in events %}
    <tr>
      <td>{{ p.header.title }}</td>
      <td>
        {{ p.header.startdate|date("F d, Y")  }}
        <br />
        (Raw: {{ p.header.startdate }}  )
      </td>
      <td>{{ p.header.startdate|date("F d, Y") }} </td>
      <td>{{ p.header.description }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

<hr />

<h1>Sort by Description</h1>
<h2>order('header.description', 'asc')</h2>

{% set eventsRaw = page.children() %}
{% set events = eventsRaw.order('header.description', 'asc') %}

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  {% for p in events %}
    <tr>
      <td>{{ p.header.title }}</td>
      <td>{{ p.header.startdate|date("F d, Y")  }}</td>
      <td>{{ p.header.startdate|date("F d, Y") }} </td>
      <td>{{ p.header.description }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

{% endembed %}
```

The first sort `{% set events = eventsRaw.order('header.startdate', 'desc') %}` does not work as expected. It looks like instead it ignore that this is even a real value and is just sorts by title. The sort for `{% set events = eventsRaw.order('header.description', 'asc') %}` works. I have a more complex example in my real project, I can sort on any field that is not a date - however, if I do have any fields which are in the `YYYY-MM-DD` format, they will also not sort as expected.

----

Here is the code at: `[siteroot]/user/pages/event-list/eventlist.md`

```
---
title: 'Event List'
---

This is the demo to make a list of events. The events are child pages of this page. This page is template type "eventlist". The children are template type "event".

This issue is with the sorting of date strings. The date is stored in the actual content element as a string of length ten in the format `YYYY-MM-DD`. Since it is a string using this presentation, it should sort like a normal string. However, the string sorting seems to be doing weird things as this example will show.
```

----

Here are four  content pages I am using in my testing:

At: `[siteroot]/user/pages/event-list/new-years-2015/event.md`
```
---
title: 'New Years 2015'
startdate: '2015-01-01'
enddate: '2015-01-01'
description: 'Happy New Year!'
---
```

At: `[siteroot]/user/pages/event-list/ground-hog-day/event.md`
```
---
title: 'Ground Hog Day'
startdate: '2015-02-02'
enddate: '2015-02-02'
description: '6 more weeks of winter?'
---
```

At: `[siteroot]/user/pages/event-list/off-to-the-races/event.md`
```
---
title: 'Off to the Races'
startdate: '2015-04-14'
enddate: '2015-04-15'
description: 'Going to see the race horses.'
---
```

At: `[siteroot]/user/pages/event-list//back-to-the-future/event.md`
```
---
title: 'Back to the Future'
startdate: '2015-08-12'
enddate: '2015-12-12'
description: 'Finally got a new flux capacitor.'
---
```

------------------------

Here are screenshots of what is rendered when the event-list template is used:

![image](https://cloud.githubusercontent.com/assets/3157148/21070770/c8710f7e-be5a-11e6-8a75-db356b7db73a.png)

![image](https://cloud.githubusercontent.com/assets/3157148/21070773/dfc68492-be5a-11e6-9197-07c096e6b7a6.png)

In the first screenshot, you can see that it was NOT sorted using the date field, but instead seems to have ignored the request or reverted for some reason?

I am wondering if the date-type field get special handling somewhere in one of the called functions used for the sorting?
