### ISSUE TITLE
Cannot sumbit form with required file field

### ISSUE THREAD

**Issue by franfran** [getgrav/grav#1217]
Hi,

Trying to create a custom form field using the document example.

It is a file field and required is true.

I can see the file field in the advance tab.  However, even I have the file uploaded, the form keep asking me to input the required file field and I cannot save the Page.

see screen below.

<img width="853" alt="screen shot 2016-12-16 at 6 41 43 pm" src="https://cloud.githubusercontent.com/assets/1584365/21260511/3fca02fe-c3c1-11e6-890e-408a579c94ae.png">

I am using Grav v1.1.9 and Admin panel v1.2.5.

Any clue on what could be wrong? 

Here is the blueprints

```
title: testp
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        advanced:
          fields:
            overrides:
              fields:
                header.a_sample_field:
                  type: file
                  label: test p field
                  destination: 'user/plugins/testplugin/assets'
                  accept:
                    - image/*
                  validate:
                    required: true
```
