### ISSUE TITLE
Taxonomy collection type broken?

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav#1222]
As reported on the forum:

Broken
```
content:
    items:
        - '@taxonomy':
            category: [blog, featured]
```
Working
```
content:
    items:
        - '@self.children'
```
