### ISSUE TITLE
Page field `checkbox` value not saved

### ISSUE THREAD

**Issue by onionradish** [getgrav/grav#1225]
Adding a checkbox field `foo` to a page blueprint does not correctly save/update the value. It's always `'0'` or `false`.

```
form:
    fields:
        header.foo:
            type: checkbox
            label: foo
            name: foo
            title: foo
            validate:
                type: bool
```

Results in the header value always equal to `false`, regardless of whether checked/saved or unchecked/saved. Same field with `type: toggle` works correctly.
