### ISSUE TITLE
Bug: `validation: "strict"`does not work

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav#1273]
Dear Grav Team,

I'm pretty sure this bug was introduced a while ago (when re-factoring the Blueprint classes). But today I noticed that `validation: "strict"` cannot be "switched on", i.e., `$blueprint->validate()` never throws an error even if you provide data that do not exists in the blueprint definition. MWE:

```yaml
form:
  validation: strict

  fields:
    test:
      type: text
      label: "Test"
```

Then with PHP:

```php
$blueprint = new Blueprint("blueprints://...");
$blueprint->validate(['wrong' => 'field']);
```
