### ISSUE TITLE
Oddity in lists in plugin-configuration

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1285]
I stumbled over a bit off an unexpected configuration-issue between a plugins default .yaml and a user's set .yaml. Consider the following (using [v.1.2.0](https://github.com/OleVik/grav-plugin-twigfeeds) of the Twig Feeds plugin).

A user has this configuration:

```
enabled: true
twig_feeds:
  -
    source: 'https://vaviblog.com/content/all?_t=rss'
    start: 0
    end: 10
```

The plugin's default is this:

```
enabled: true
twig_feeds:
  - source: http://rss.nytimes.com/services/xml/rss/nyt/World.xml
    name: NY Times
    start: 0
    end: 2
  - source: http://feeds.bbci.co.uk/news/uk/rss.xml
    start: 0
    end: 2
  - source: http://www.aljazeera.com/xml/rss/all.xml
```

Wherein dashes on their own line seems to have no effect, as expected. However, dumping the config through Grav (`$this->config->get('plugins')['twigfeeds']`) I get this:

```
array:2 [
  "enabled" => true
  "twig_feeds" => array:3 [
    0 => array:3 [
      "source" => "https://vaviblog.com/content/all?_t=rss"
      "start" => 0
      "end" => 10
    ]
    1 => array:3 [
      "source" => "http://feeds.bbci.co.uk/news/uk/rss.xml"
      "start" => 0
      "end" => 2
    ]
    2 => array:1 [
      "source" => "http://www.aljazeera.com/xml/rss/all.xml"
    ]
  ]
]
```

That is, the lists are merged between the user-config and the plugin-config. This seems like an error, as the user-config merely replaces the first item in the array of the available configuration.

**Comment by OleVik** [comment]
Seemingly the same as [#857](https://github.com/getgrav/grav/issues/857).

**Comment by flaviocopes** [comment]
Replicated. The issue happens when the field is declared in the blueprint as `list`.

So if you don't have a blueprint definition, all fine.

If you have (as in the twigfeeds plugin https://github.com/OleVik/grav-plugin-twigfeeds example)

```yaml
form:
  validation: loose
  fields:
    enabled:
      type: toggle
      label: Plugin Status
      highlight: 1
      default: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
    twig_feeds:
      name: twig_feeds
      type: list
      style: vertical
      label: Feeds
      fields:
        .source:
          type: text
          label: Source
          description: URL to RSS or Atom feed.
          validate:
            required: true
        .name:
          type: text
          label: Name
          description: Name of the feed.
        .start:
          type: text
          label: Item start
          description: Start of feed results. Must be a number between 0 and 500.
          validate:
            type: int
            min: 0
            max: 500
        .end:
          type: text
          label: Item end
          description: End of feed results. Must be a number between 0 and 500.
          validate:
            type: int
            min: 0
            max: 500
```
