### ISSUE TITLE
E-Mail form problem with attachments

### ISSUE THREAD

**Issue by tauchschlumpf** [getgrav/grav#1311]
Hi, when i try to use attachments i only get a dotted box 

```yaml
---
title: Neu
menu: Start
form:
    name: my-nice-form
    action: /home
    fields:
        - name: name
          id: name
          label: Name
          classes: form-control form-control-lg
          placeholder: Geben Sie Ihren Namen ein
          autocomplete: on
          type: text
          validate:
            required: true

        - name: email
          id: email
          classes: form-control form-control-lg
          label: Email
          placeholder: Geben Sie Ihre E-Mail Adresse ein
          type: text
          validate:
            rule: email
            required: true

        - name: message
          label: Message
          classes: form-control form-control-lg
          size: long
          placeholder: Geben Sie hier Ihre Nachricht ein   
          type: textarea
          validate:
            required: true
            
        - name: my-file
          label: 'Add a file'
          type: file
          multiple: false
          destination: user/data/files
          accept:
            - image/jpg
            - image/png
          
            
       
            
       
    buttons:
        - type: submit
          value: Absenden
          class: btn btn-primary btn-block

    process:
        
        - email:
            from: "{{ config.plugins.email.from }}"
            to:
              - "{{ config.plugins.email.from }}"
              - "{{ form.value.email }}"
            subject: "[Feedback] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
            attachments:
              - 'my-file'
           
        - save:
            fileprefix: feedback-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
        - message: Danke für Ihre Nachricht!
        - display: thankyou


onpage_menu: true
content:
    items: @self.modular
    order:
        by: default
        dir: asc
        custom:
            - _intro
            - _features
            - _video
            - _pricing
            - _testimonials
            - _text
            - _news
            - _contact
---
```

![image](https://cloud.githubusercontent.com/assets/25817435/23017499/c872b3f4-f43a-11e6-9ed3-16a4ea3bf8ca.png)
