### ISSUE TITLE
How to sort list items by date

### ISSUE THREAD

**Issue by sebastianschrama** [getgrav/grav#1313]
On a page I have a field type list with some events. Now I want to sort this list of items by date. How can I achieve this?

This is my .yaml file:

```yaml
title: Events
'@extends': default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            events:
              type: section
              title: Events
              underline: true

              fields:
                header.event.items:
                  name: event
                  type: list
                  label: Event
                  style: vertical
                  btnLabel: Event hinzufügen
                  collapsed: true
                  sort: false

                  fields:
                    .title:
                      type: text
                      label: Titel
                      validate:
                        required: true
                    .date:
                      type: date
                      label: Datum
                    .fromtime:
                      type: time
                      label: Uhrzeit Start
                    .totime:
                      type: time
                      label: Uhrzeit Ende
                    .text:
                      label: Text
                      type: markdown
                      validate:
                        type: textarea
                    .category:
                      type: text
                      label: Kategorie
            options:
              fields:
                header.events.enabled:
                  type: ignore
```

This is my twig file:

```twig
{% extends 'partials/base.html.twig' %}

{% block content %}
	<h1>{{ page.header.title }}</h1>
	<p class="subline">{{ page.header.subtitle }}</p>
	{{ page.content }}
	
	{% set events = page.header.event.items %}
	{% for event in events %}
		<div class="event" id="{{ event.title|replace({'ß':'ss'})|hyphenize }}">
			<h2>{{ event.title }}</h2>
			<div class="date">
				<span class="weekday">{{ event.date|date("l") }}</span>
				<span class="day">{{ event.date|date("d") }}</span>
				<span class="month">{{ event.date|date("M") }}</span>
			</div>
			{{ event.text|markdown }}
		</div>
	{% else %}
		<p>Keine Events vorhanden.</p>
	{% endfor %}
{% endblock %}

```
