### ISSUE TITLE
Display Image in List not working

### ISSUE THREAD

**Issue by sebastianschrama** [getgrav/grav#1316]
Hey,

I just want to display an image inside of a list. But for some reasons I'm not able to do this.

My yaml file:

```
title: Über uns
'@extends': default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            team:
              type: section
              title: Team
              underline: true

              fields:
                header.team.items:
                  name: team
                  type: list
                  btnLabel: Team-Mitglied hinzufügen
                  collapsed: true

                  fields:
                    .title:
                      type: text
                      label: Titel
                      validate:
                        required: true
                    .text:
                      label: Text
                      type: markdown
                      validate:
                        type: textarea
                    .image:
                      type: file
                      label: Bild
                      destination: 'self@'
                      multiple: false
```

My twig template:

```
{% extends 'partials/base.html.twig' %}

{% block content %}
	{{ page.content }}

	{% set teammembers = page.header.team.items %}
	{% for teammember in teammembers %}
		<div class="team">
			<h2>{{ teammember.title }}</h2>
			{% if teammember.text %}
				{{ teammember.text|markdown }}
			{% endif %}

			{% set image = page.media[teammember.image].cropZoom(800, 600) %}
			<img src="{{ image.url }}" alt="{{ teammember.title }}">
		</div>
	{% else %}
		<p>Kein Teammitglied angelegt.</p>
	{% endfor %}
{% endblock %}
```

This is not working. Why?

There's just an error: `An exception has been thrown during the rendering of a template ("Illegal offset type in isset or empty").`
