### ISSUE TITLE
Unset@: true not working for the Advanced Tab

### ISSUE THREAD

**Issue by MrMacStripe** [getgrav/grav#1322]
When I try to hide the "Advanced" tab in Admin/pages, I get an error:

Whoops \ Exception \ ErrorException (E_RECOVERABLE_ERROR)
Argument 1 passed to Grav\Common\Page\Page::move() must be an instance of Grav\Common\Page\Page, null given, called in /Users/myMacUser/Documents/Webdevelopment/Coding/Grav/user/plugins/admin/classes/admincontroller.php on line 497 and defined
 

My Blueprint:
```yaml
title: Homepage
'@extends':
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:

      fields:
        content:
          unset@: true
        options:
          unset@: true
        advanced:
          unset@: true

        custom:
          type: tab
          title: Homepage
          fields:
            header.h1:
              type: text
              label: Main Headline for the Landing Page
              default: Headline`
```

This error is new and it´s somehow strange since I just created a new template via the CLI and started coding. Previous projects did not have that issue with the exact same code.

**Comment by MrMacStripe** [comment]
But I recently hid the advanced tab for nearly every page in another project. That was never an issue so far. The error happens when I try to save the page.

**Comment by flaviocopes** [comment]
The Advanced tab is needed to move the page around, add to a new parent, order.. it's effectively providing a good chunk of functionality which you might miss later.

The error can be easily fixed with an `if ($parent)` check on that line that gives the error, and the page saves just fine, but i guess if instead we should throw an exception with a more helpful error if people try to do the same thing later?

Or we do give the freedom to remove that, with the risk of confusing missing vital functionality for page management?

**Comment by fourroses666** [comment]
I have the same issue, it works for Admins but when a "not superuser" saves the page I get the error.

```
      fields:
        options:
          type: tab
          title: PLUGIN_ADMIN.OPTIONS
          security:
            - admin.super

        advanced:
          type: tab
          title: PLUGIN_ADMIN.ADVANCED
          security:
            - admin.super
```
