### ISSUE TITLE
Twig not being processed in page content

### ISSUE THREAD

**Issue by OvidiuS** [getgrav/grav#1351]
Using Grav v1.1.17 - Admin v1.2.14
I turned on the setting for processing Twig on pages, in `user/config/system.yaml`:
```
  process:
      markdown: true
      twig: true
    twig_first: true
    never_cache_twig: true
  frontmatter:
    process_twig: true
```
but twig does not get processed if used in the content of a page. Something simple like `{{ config.site.author.email }}` gets outputted raw.

The only way to get twig to be processed in a page's content is to add this to the page's frontmatter:
```
process:
    twig: true
```
So the system setting is not being used by the pages, it needs to be re-set on a page-by-page basis.

**Comment by rhukster** [comment]
Ok, i looked into this.  I setup a fresh installation of the latest RC (should be the same as the stable version).

i changed the `user/config/system.yaml`  like so:

```
pages:
  theme: antimatter
  markdown:
    extra: false
  process:
    markdown: true
    twig: true
```

then I setup my page with:

```
---
title: Home
---

# Grav is Running!
## You have installed **Grav** successfully

<h1>{{ page.title }}</h1>
```

The page title displayed just fine as expected.  Turning off twig processing in system.yaml caused the twig code to be rendered as expected.  Are you sure you set your configuration in `user/config/system.yaml` also did you ensure it was under the `pages:` block???
