### ISSUE TITLE
Theme inheritence not working?

### ISSUE THREAD

**Issue by rbukovansky** [getgrav/grav#1353]
I'm trying to follow `https://learn.getgrav.org/themes/customization#theme-inheritance` as I'm trying to enhance theme `knowledge-base` with updates our company needs, but I'm getting this error:

```
Whoops \ Exception \ ErrorException (E_ERROR)
Class 'Grav\Theme\KnowledgeBase' not found
```

My theme files:

`blueprints.yaml`:
```yaml
name: NETTO Knowledge Base
version: 0.0.1
description: "Extending Knowledge Base theme"
icon: crosshairs
author:
 name: Richard Bukovansky
 email: richard.bukovansky@gmail.com
 url: http://github.com/rbukovansky
```

`netto-knowledge-base.php`:
```php
<?php
namespace Grav\Theme;

use Grav\Common\Theme;

class NettoKnowledgeBase extends KnowledgeBase
{
   // Some new methods, properties etc.
}
?>
```

`netto-knowledge-base.yaml`:
```yaml
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/netto-knowledge-base
         - user/themes/knowledge-base
```

Anybody has an idea, what could be wrong? Thank you.
