### ISSUE TITLE
ordering by date in custom field 

### ISSUE THREAD

**Issue by vitopepito** [getgrav/grav#1368]
I experienced the following issue: In a page collection with a header like in the code below, the items will not be ordered chronologically if the field 'header.event.start' is in date format. 

```
title: 'collection'
content:
    items: '@self.children'
    order:
        by: header.event.start
        dir: desc
```

This is an example of an item
```
title: 'item1'
event:
    start: '21-9-2017 20:00'
    end: '21-9-2017 22:00'
```

I think that the date format in the custom field is not recognized and ordering by number is used. Using the american date format makes the items ordered by month first, but it is not properly recognized as a date. 

### Work around
The collection header can use a dateRange in combination with order to achieve chronological ordering that can be either descending or ascending. 

```
title: 'collection'
content:
    items: '@self.children'
    dateRange:
        start: today
        field: header.event.start
    order:
        dir: asc
```

This works for me but is kind of hacky. The documentation of dateRange should be updated to show the ordering options.
