### ISSUE TITLE
html not rendered as expected with twig inside a container

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav#1449]
hi,

this afternoon i decide to switch my hardcoded img url or href  to dynamic ones in my pages

```<img src="/user/pages/07.support/_slider_monitoring/support-ticket.svg"/>```

to ```<img src="{{ page.media['support-ticket.svg'].url }}"/>```

of course i set
```
process:
    markdown: true
    twig: true
```
html is well rendered but when i put all my html code like container 
```
<div>
  <img class="svg" src="{{ page.media['support-ticket.svg'].url }}" alt="Documentation Elana" title="Documentation Elana">
</div>
```
output is :
```
<div>
  <img class="svg" src="%7B%7B%20page.media%5B'support-ticket.svg'%5D.url%20%7D%7D" alt="Documentation Elana" title="Documentation Elana">
</div>
```

when i use the same in a page blueprint , everything is ok
```
            .description:
                  type: markdown
                  label: MY_LABEL
                  showPreview: false
                  validate:
                    type: textarea
```

so i'm really confused, if anybody have an idea

Thanks

Note: Grav v1.2.4 - Admin v1.4.2

**Comment by rhukster** [comment]
The markdown processor is escaping those characters.  The solution is to process the twig before the markdown.  Add this to your frontmatter:

```
twig_frist: true
```

**Comment by dimitrilongo** [comment]
thanks but
```
twig_first: true
process:
    twig: true
    markdown: true
```
but can't have both process set to true, when both set to true, same issue
