### ISSUE TITLE
Question- Is there a way to call a function before the form field saved on Admin-panel?

### ISSUE THREAD

**Issue by ash0080** [getgrav/grav#1460]
For example, I have a form filed in blueprint like this
```
users:
      type: section
      title: Users
      underline: true
      fields:
        users:
          type: array
          label: Accounts
          placeholder_key: username
          placeholder_value: password
          required: true
```
I want to make the password field hashed before save to the .yaml file.
