### ISSUE TITLE
[BUG?] Error when set multiple: true in pages field type

### ISSUE THREAD

**Issue by ash0080** [getgrav/grav#1477]
```
route:
      type: pages
      size: medium
      classes: fancy
      label: PLUGIN_ADMIN.HOME_PAGE
      show_all: true
      show_modular: false
      show_root: false
      multiple: true  // false is ok
      help: PLUGIN_ADMIN.HOME_PAGE_HELP

// then in PHP

$route = $this->config->get('plugins.MYPLUGIN.route');
```
will throw an error like this
![2017-05-15 3 51 06](https://cloud.githubusercontent.com/assets/2803210/26047580/59243acc-3986-11e7-8608-8f32abe850e3.png)
