### ISSUE TITLE
Folder page ordering doesn't obey 99+

### ISSUE THREAD

**Issue by l3aconator** [getgrav/grav#1524]
The folder numerical ordering doesn't obey the order over 99. Anything over 99 puts them back at the top of the order structure on render instead of continuing sequentially.

**Comment by flaviocopes** [comment]
Shouldn't be the case, just tested. 
You mean in a frontend collection? How is the collection defined? Can you paste the parent page header?

**Comment by l3aconator** [comment]
```
---
title: 'TeamSnap Team Players - Employee Bios'
menu: 'Team Players'
metadata:
    description: 'The talented men and women (and dog!) that work together to bring you TeamSnap products and services.'
content:
    items: '@self.children'
visible: true
---
```
And then all the child pages are labeled numerically do order them and allow for content editors to reorder them the way they want.
