### ISSUE TITLE
Markdown modified on filesystem, not reflected in plugin

### ISSUE THREAD

**Issue by jrpub** [getgrav/grav#1547]
Hi
I am coding a plugin with a customized API to set a custom header variable in the markdown file. The workflow is as follows:
a) Request from client to server 
b) A markdown page is generated with "file_put_contents" in the relevant directory
c) Then, immediately after, I am loading the page with GRAV, but the headers I set in b) is not seen

```
// step b
$res = file_put_contents($file, $output);

// step c
$c = file_get_contents('article.md'); 
$this->grav['log']->info($c); // Show the right customized header

this->grav['log']->info(print_r($page->raw(), true)); // customized header does not appear! 

```
I don't understand the issue. I suspected the cache or the fact that $this->grav is not reloaded, but I don't know. Any advice?

Thanks

**Comment by rhukster** [comment]
Can you provide an example of the file that you are storing?  And exactly where you are storing it?  Does it show up after you clear cache?

**Comment by jrpub** [comment]
I put basic Yaml data to store Amazon product informations.

```
title: 'test article'
taxonomy:
    category: blog
wam_id: '3'
items:
    Photo-0:
        type: Photo
        Address: 'http://amazon.fr/...'
    Photo-1:
        type: Photo
        Address: 'http://amazon.fr/'
    Photo-2:
        type: Photo
        Address: 'http://amazon.fr/...'
        Longueur: 120
        Hauteur: 120
        Profondeur: 55
```
But I think, the problem is that when you chain the manual modification/creation of a page and then you try access it with $this->grav. The new content is not taken into account. 

Today I noticed also this is also true for manually created pages:

```
// Manual creation of a page
$r = $this->tools->createDirectory($articleDirectory); // Create the directory for the new page
$output = "---\n".$headerYaml."\n---\n".$filteredContent; // Prepare the page content
$file = $articleDirectory.'/article.md';
$res = file_put_contents($file, $output); // Save the new page

// Looping pages
$pagesCollection = $this->grav['pages']->all();
foreach ($pagesCollection as $page) {
         $this->grav['log']->info($page->title());
}
// Display all pages but not the newly created one
```
I tried to delete cache between the manual creation of the page and the loop of all pages with: 

`Cache::clearCache('all');
`
But it still not working. 

Reloading $this->grav instance programmatically may be a solution, but I don't know how to do this.
