### ISSUE TITLE
"editor" field is not clickable if it is in "list" field

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav#1576]
If I use `editor` field for child item of `list` field, `editor` is not clickable after clicking `Add Item` button.

To be able to focus on editor and enter text, I need to click on an icon in the toolbar, eg Bold icon, to insert something to editor.

I've also tried to add `autofocus: true` attribute but it only brings cursor into editor, I still can't input anything.

Here is a sample blueprint to test with Antimatter theme, you can save it as user/themes/antimatter/blueprints/default.yaml, edit a page which uses `default` template in admin to see the problem.

A similar problem if we use `codemirror`.

Grav v1.3.1
Admin plugin v1.5.1

```
title: Default
'@extends':
    type: default

title: Default

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        test:
          type: tab
          title: Test
          fields:
            header.items:
              type: list
              label: Items
              fields:
                .item:
                  type: editor
                  label: Item
```
