### ISSUE TITLE
Admin: Blueprints & Taxonomies error

### ISSUE THREAD

**Issue by matejkramny** [getgrav/grav#1612]
Hi there, I think I found a bug with the admin page editing. I created a blueprint which contains Taxonomies. Taxonomy is also in the Options tab, so technically it's on the page twice.

Behaviour:

- Go to the custom tab and edit the taxonomy
- Remove a tag
- Press Save
- Saved, but tag still present. If you press save and do nothing, the tag is added twice (to the page file)

Blueprint:

```
title: Item
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:

      fields:
        blog:
          type: tab
          title: TAB

          fields:
            header.taxonomy:
              type: taxonomy
              label: PLUGIN_ADMIN.TAXONOMY
              multiple: true
              validate:
                type: array
```

version: `Grav v1.3.2 - Admin v1.5.2`
