### ISSUE TITLE
Can't use custom date header

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#1641]
Hi!

I found a problem. 
If I have `date: 09.02.2017` in blog post header and this code:
```
content:
    items: @self.children
    order:
        by: date
        dir: desc
```
than my sorting works correctly. `{{ dump(post.header.date) }}` shows me timestamp date.

But if I have custom date header like `releaseDate` and order by this header, then sorting breaks down. For example, `01.09.2012` is older then `09.02.2017`. `{{ dump(post.header.releaseDate) }}` shows me string date as is.

Later @flaviocopes told me to use `Y.m.d` format (`2017.02.09` for example). This temporarily resolved my problem until I want to output the date in the post.
I put `{{ dump(page.header.releaseDate|date('d')) }}` line in twig and see an error:
```
An exception has been thrown during the rendering of a template ("DateTime::__construct(): 
Failed to parse time string (2017.02.09) at position 5 (0): Double time specification").
```

How to fix?

p.s. Same problem in the forum:
https://discourse.getgrav.org/t/date-format/1555/8

**Comment by rhukster** [comment]
This is actually to be expected.  When using a custom field to order by, Grav really has no clue what type of field that is, so it's not smart enough to convert it do a date and compare it that way.  One way to fix this would be to store the custom date field as a timestamp.

**Comment by dimayakovlev** [comment]
@rhukster Maybe you can add `strtotime` Twig filter into Grav? This will solve problems with converting custom dates to timestamps.

**Comment by Sogl** [comment]
@rhukster 
>One way to fix this would be to store the custom date field as a timestamp.
It's uncomfortable for reading or changing such date by a human.

I see two ways to solve this problem:
1. Add `strtotime` filter as @dimayakovlev mentioned.
2. Add additional option to specify field data type for Grav. `releaseDate(date): 09.02.2017`, for example. An indication of the data type in parentheses.

**Comment by rhukster** [comment]
You can already convert a date to a time stamp. 

https://stackoverflow.com/questions/9242072/how-can-i-convert-a-date-to-a-unix-timestamp-with-twig

**Comment by dimayakovlev** [comment]
@sogl `'2017.02.09'|date('U')` - this causes an error, but if you change dots to dashes all works fine. So you can use this code to convert your custom date to timestamp: `'2017.02.09'|replace('.', '-')|date('U')`.

**Comment by Sogl** [comment]
@rhukster In latest Grav 1.3.8 I can use this code `{{ dump(page.header.myDate|date('d')) }}` successfully without errors.

But I'm still can't order collections by custom date header.

I found a workaround:
1. Create a new file in theme: `themename/class/CollectionSorter.php`
```php
<?php
namespace Grav\Theme;

use Grav\Common\Grav;

class CollectionSorter
{
    protected $grav;
    protected $field;
    protected $asc;

    public function __construct() {
        $this->grav = Grav::instance();
    }

    public function byDate($collection, $field, $asc = true)
    {
        $this->field = $field;
        $this->asc = $asc;

        $array = [];
        foreach($collection as $p) {
            $array[] = $p;
        }

        usort($array, function($a, $b) {

            if (!isset($a->header()->{$this->field}, $b->header()->{$this->field})) {
                return 0;
            }

            $valA = $a->header()->{$this->field};
            $valB = $b->header()->{$this->field};

            if ($valA == $valB) {
                return 0;
            }

            if ($this->asc) {
                return strtotime($valA) - strtotime($valB);
            }
            return strtotime($valB) - strtotime($valA);
        });

        return $array;
    }
}
```
2. Add this to `themename.php` file:
```php
public function onTwigSiteVariables()
{
    require_once __DIR__ . '/class/CollectionSorter.php';
    $this->grav['twig']->twig_vars['sorter'] = new CollectionSorter();
}
```
3. Use in twig:
```twig
{% set asc_order = sorter.byDate(page.collection, 'custom_date_field') %}
{% set desc_order = sorter.byDate(page.collection, 'custom_date_field', false) %}
```

But what if I want to handle things like `dateRange`, `limit` etc... do everything in custom PHP functions?

**Comment by Sogl** [comment]
Devs please @rhukster @w00fz @OleVik @flaviocopes @mahagr 

I returned to my project and still can't sort custom header dates with built-in functional 😢 

I saw much similar issues: 
https://github.com/getgrav/grav/issues/1368 
https://github.com/getgrav/grav/issues/1640
https://github.com/getgrav/grav/issues/1764
https://github.com/getgrav/grav/issues/1199

For now.
Just tried to use frontmatter and twig `SORT_NUMERIC` hack together to show upcoming tours.
I can't set `SORT_NUMERIC` straight into the frontmatter because of error:
```
An exception has been thrown during the rendering of a template 
("asort() expects parameter 2 to be long, string given").
```

in items:
```yaml
//tour 1
returnDate: '31-08-2018 23:01'
//tour 2
returnDate: '30-07-2018 23:01'
//tour 3
returnDate: '01-08-2018 23:01'
```

In frontmatter:
```yaml
nearest:
    items:
        '@page.children': '/tours'
    dateRange:
        start: today
        field: header.returnDate
```

in twig:
```twig
{% set nearest_collection = page.collection('nearest')
.order('header.returnDate', 'desc', null, 1) %}

{% for tour in nearest_collection %}
    {{ dump(tour) }}
    {{ dump(tour.header.returnDate) }}
{% endfor %}
```

Tried to change `1` to `SORT_NUMERIC`.


No way: 
```
31-08-2018 23:01
30-07-2018 23:01
01-08-2018 23:01
```



Also tried to disable this thing:
![image](https://user-images.githubusercontent.com/7556290/43235041-e11e437e-9087-11e8-89e2-5069616cb3cf.png)

Maybe any of you @inktrap @erichgoldman @tboulogne @akoebbe @vitopepito  
have found a solution?

**Comment by akoebbe** [comment]
@Sogl I just tried this out in the `devlop` branch and it does work for me. I was using the format of `04/01/2010`. Can you see if changing your date format makes a difference? I'm sorry I don't have more time to try different variations.  Here's what I have...

Custom item headers:

```yaml
#item 1
custom_date: '01/01/2010'
#item 2
custom_date: '02/01/2010'
#item 3
custom_date: '03/01/2019'
#item 4
custom_date: '04/01/2019'
```

Collection definition (used a blog page for this test):
```yaml
content:
    items: '@self.children'
    order:
        by: header.custom_date
        dir: desc
    dateRange:
            start: today
            field: header.custom_date
    pagination: true
    url_taxonomy_filters: true
```

With this set up I only see two items on the page and they are sorted as expected.

**Comment by Sogl** [comment]
@akoebbe Try different dates and months, not only years. Looks like Grav uses string comparsion for custom fields.
For example:
```
#item 1
custom_date: '02/01/2010'
#item 2
custom_date: '01/02/2010'
#item 3
custom_date: '11/10/2019'
#item 4
custom_date: '12/08/2019'
```

It should be:
```
'02/01/2010'
'01/02/2010'
'12/08/2019'
'11/10/2019'
```

Wrong (my situation):
```
'01/02/2010'
'02/01/2010'
'11/10/2019'
'12/08/2019'
```

**Comment by akoebbe** [comment]
So are you saying you're using `dd/mm/yyyy`? Your "Wrong" situation seems like it's sorting `mm/dd/yyyy`. Is that correct?

**Comment by akoebbe** [comment]
Ok. I see what you're saying. Here is a more clear example...

```yaml
#item 1
custom_date: '01/01/2010'
#item 2
custom_date: '03/01/2010'
#item 3
custom_date: '02/01/2020'
#item 4
custom_date: '04/01/2019'
```

is sorted...

```
'01/01/2010'
'02/01/2020'
'03/01/2010'
'04/01/2019'
```

So the question is can you use an ISO9601 format instead `yyyy-mm-dd hh:mm:ss` since that is string sortable? Granted I get that there might still be a point of debate on casting certain strings as dates.
