### ISSUE TITLE
Error while saving custom template

### ISSUE THREAD

**Issue by mgollmer** [getgrav/grav#1647]
Hello there, 

I updated to the new 1.3.3 version and created for my ongoing project a custom template, which inherits the default-template.

After I enter data to the custom fields I wanted to save, but it didn't save as expected. All the parent fields of the default template are saved. The new fields i added via my custom template are gone. 

Can somebody help me, please?

Here is my blueprint for the template. Oh, and I use gantry5 too.

```yaml
title: Einsatzgebiet
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:

      fields:
        einsatzgebiet:
          type: tab
          title: Einsatzgebiet

          fields:

            columns:
              type: columns
              fields:

                column1:
                  type: column
                  fields:

                    content:
                      type: section
                      title: Inhalt
                      style: vertical
                      underline: true


                    einsatzgebiet:
                      type: text
                      label: Einsatzgebiet
                      help: Hier muss der Name des Einsatzgebietes eingetragen werden
                      style: vertical
                      placeholder: Einsatzgebiet eingeben...

                    subcontents:
                      type: list
                      array: true
                      label: Inhaltsblöcke
                      description: Create each item to appear in the content row.
                      help: Hier können die einzelnen Inhaltsblöcke der Seite eingetragen werden.
                      value: title
                      style: vertical
                      ajax: true

                      fields:
                        .name:
                          type: text
                          label: Title

                        .img:
                          type: pagemediaselect
                          label: Image

                        .rokboximage:
                          type: pagemediaselect
                          label: RokBox Image
                          description: Select the rokbox image.

                        .rokboxcaption:
                          type: text
                          label: Caption
                          description: Customize the rokbox caption.
                          placeholder: Enter caption

                        .subtitle:
                          type: text
                          label: Sub Title

                        .description:
                          type: textarea
                          label: Description

                        .class:
                          type: selectize
                          label: CSS Classes
                          description: CSS class name for the particle.

                        .button:
                          type: text
                          label: Button Label
                          description: Specify the button label.

                        .buttonlink:
                          type: text
                          label: Button Link
                          description: Specify the button link.

                        .buttonclass:
                          type: selectize
                          label: Button Classes
                          description: CSS class names for the button.

                    testimonials_header:
                      type: section
                      title: Testimonials
                      style: vertical
                      underline: true

                    testimonials:
                      type: list
                      array: true
                      style: vertical
                      label: Testimonials
                      description: Hier können Testimonials angelegt werden
                      help: Hier können mehrere Testimonials auf einmal angelegt werden.
                      value: title
                      ajax: true

                      fields:
                        .style:
                          type: select
                          label: Testimonial Style
                          description: Select the style for the testimonials
                          placeholder: 'Select...'
                          default: g-testimonial-standard
                          options:
                            g-testimonial-standard: Standard
                            g-testimonial-alt: Alternative

                        .img:
                          type: pagemediaselect
                          label: Image

                        .content:
                          type: textarea
                          label: Content

                        .author:
                          type: text
                          label: Author

                        .company:
                          type: text
                          label: Company

                        .companyurl:
                          type: text
                          label: Link

                column2:
                  type: column

                  fields:

                    slider:
                      type: section
                      title: Slider
                      style: vertical
                      underline: true

                    slider_items:
                      type: list
                      array: true
                      label: Slider Einträge
                      description: Hier können alle Einträge für die Slider auf der Seite angelegt werden.
                      help: Hier können alle Einträge für die Slider auf der Seite angelegt werden.
                      value: name
                      style: vertical
                      ajax: true

                      fields:
                        .name:
                          type: text
                          label: Titel

                        .image:
                          type: pagemediaselect
                          label: Background Image
                          description: Select desired image.
                        .overlayImage:
                          type: pagemediaselect
                          label: Overlay Image
                          description: Select desired overlay image.
                        .overlayParallax:
                          type: select
                          label: Overlay Parallax
                          description: Enable or Disable the Overlay Parallax Effect.
                          default: 0
                          options:
                            1: Enabled
                            0: Disabled
                        .overlayParallaxRatio:
                          type: text
                          label: Parallax Ratio
                          default: 0.3
                          description: Multiplier for scrolling speed to allow the parallax image to move with different speed. Less is slower, and 1 is normal.
```

Regards, 
Michael Gollmer

**Comment by rhukster** [comment]
Hmm.. I don't think anything changed in this release that would affect the blueprints handling.  can you confirm if the prior version (1.3.2) was working as expected?

**Comment by mgollmer** [comment]
Hi there, 

it's the first template i created in this project, so I can't confirm it. :frowning_face: 

But I don't see any problem with this blueprint.

**Comment by iusvar** [comment]
I'm also trying blueprints and I wanted to try what you're doing ...
I did some testing and it works with this version: Grav v1.3.3 - Admin v1.6.0.
Essentially I added some `header` in front of the names of your fields

```
title: Einsatzgebiet
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:

      fields:
        einsatzgebiet:
          type: tab
          title: Einsatzgebiet

          fields:

            columns:
              type: columns
              fields:

                column1:
                  type: column
                  fields:

                    header.content:
                      type: section
                      title: Inhalt
                      style: vertical
                      underline: true


                    header.einsatzgebiet:
                      type: text
                      label: Einsatzgebiet
                      help: Hier muss der Name des Einsatzgebietes eingetragen werden
                      style: vertical
                      placeholder: Einsatzgebiet eingeben...

                    header.subcontents:
                      type: list
                      array: true
                      label: Inhaltsblöcke
                      description: Create each item to appear in the content row.
                      help: Hier können die einzelnen Inhaltsblöcke der Seite eingetragen werden.
                      value: title
                      style: vertical
                      ajax: true

                      fields:
                        .name:
                          type: text
                          label: Title

                        .img:
                          type: pagemediaselect
                          label: Image

                        .rokboximage:
                          type: pagemediaselect
                          label: RokBox Image
                          description: Select the rokbox image.

                        .rokboxcaption:
                          type: text
                          label: Caption
                          description: Customize the rokbox caption.
                          placeholder: Enter caption

                        .subtitle:
                          type: text
                          label: Sub Title

                        .description:
                          type: textarea
                          label: Description

                        .class:
                          type: selectize
                          label: CSS Classes
                          description: CSS class name for the particle.

                        .button:
                          type: text
                          label: Button Label
                          description: Specify the button label.

                        .buttonlink:
                          type: text
                          label: Button Link
                          description: Specify the button link.

                        .buttonclass:
                          type: selectize
                          label: Button Classes
                          description: CSS class names for the button.

                    header.testimonials_header:
                      type: section
                      title: Testimonials
                      style: vertical
                      underline: true

                    header.testimonials:
                      type: list
                      array: true
                      style: vertical
                      label: Testimonials
                      description: Hier können Testimonials angelegt werden
                      help: Hier können mehrere Testimonials auf einmal angelegt werden.
                      value: title
                      ajax: true

                      fields:
                        .style:
                          type: select
                          label: Testimonial Style
                          description: Select the style for the testimonials
                          placeholder: 'Select...'
                          default: g-testimonial-standard
                          options:
                            g-testimonial-standard: Standard
                            g-testimonial-alt: Alternative

                        .img:
                          type: pagemediaselect
                          label: Image

                        .content:
                          type: textarea
                          label: Content

                        .author:
                          type: text
                          label: Author

                        .company:
                          type: text
                          label: Company

                        .companyurl:
                          type: text
                          label: Link

                column2:
                  type: column

                  fields:

                    header.slider:
                      type: section
                      title: Slider
                      style: vertical
                      underline: true

                    header.slider_items:
                      type: list
                      array: true
                      label: Slider Einträge
                      description: Hier können alle Einträge für die Slider auf der Seite angelegt werden.
                      help: Hier können alle Einträge für die Slider auf der Seite angelegt werden.
                      value: name
                      style: vertical
                      ajax: true

                      fields:
                        .name:
                          type: text
                          label: Titel

                        .image:
                          type: pagemediaselect
                          label: Background Image
                          description: Select desired image.
                        .overlayImage:
                          type: pagemediaselect
                          label: Overlay Image
                          description: Select desired overlay image.
                        .overlayParallax:
                          type: select
                          label: Overlay Parallax
                          description: Enable or Disable the Overlay Parallax Effect.
                          default: 0
                          options:
                            1: Enabled
                            0: Disabled
                        .overlayParallaxRatio:
                          type: text
                          label: Parallax Ratio
                          default: 0.3
                          description: Multiplier for scrolling speed to allow the parallax image to move with different speed. Less is slower, and 1 is normal.

```
Good fun @mgollmer
