### ISSUE TITLE
Modular parent and child collection

### ISSUE THREAD

**Issue by bluis4** [getgrav/grav#1662]
Hi,

After trying for 3 days i still got mixed result from modular parent and child collection. Here is my use case :

i have 2 modular pages lets say them Home and Parent. Both have __header_ and __content1_ folder. In parent folder, i have child folder named 01.child-one and 02.child-two. In both child folder also have __header_ and __content1_ folder.

The parent markdown file modular.md look like this :
```
---
entryPage: true
menu: Parent
slug: parent
onpage_menu: true
title: 'Parent Entry Page'
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _header
entry:
    items: '@self.children'
    order:
        by: default
        dir: asc
---
```

As for the 01.child-one folder modular.md look like this :
```
---
menu: Child One
slug: child-one
onpage_menu: true
title: 'Child One'
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _header
---
```

The _header folder in child-one folder have header.md file set like this :
```
---
id: item-header
title: 'Child One Page Header'
content:
    -
        heroTitle: 'Child One Hero Title'
---
```

So in the folder _templates/modular.html.twig_ the code look like this :
```
{# {% extends 'partials/base.html.twig' %} #}

{% embed 'partials/base.html.twig' %}

	{% set entryList = page.header.entryPage %}
	{% set pageEntry = page.collection('entry') %}

	{% block content %}
	    {{ page.content }}
	    {% for module in page.collection() %}
	        {{ module.content }}
	    {% endfor %}

	    {% if entryList == "true" %}
		    <section id="testentry" class="">
		    	<div class="grid-container">
		    		<div class="grid-x">
		    			{% for child in pageEntry %}
		    				<div class="cell medium-6">
		    					<h4>{{ child.heroTitle }}</h4> {# <h4>{{ child.title }}</h4> #}
		    				</div>
		    			{% endfor %}
		    		</div>
		    	</div>
		    </section>
		{% endif %}
	{% endblock %}

{% endembed %}
```

My question is, if i use the ``` {{ child.title }} ``` it will show the child-one modular.md title, but it won't show the ```{{ child.heroTitle }}``` in the header.md in child-one _header folder, so how can i show the ```{{ child.heroTitle}}``` ?

Any help would be appreciate

**Comment by rhukster** [comment]
Could you put together a little zip with the pages you are describing so i can get a local setup to test with?

**Comment by bluis4** [comment]
@rhukster ,

This is the zip containing pages and themes folder from the user folder. The problem is in the modular.html.twig file, where i am able to show the ```{{ child.title }}``` but not the ```{{ child.heroTitle }}```

Regards,

Luke

[user.zip](https://github.com/getgrav/grav/files/1340133/user.zip)

**Comment by rhukster** [comment]
Before I dig into this, you do know that `title()` is a built in method of page, so it will work as `{{ child.title }}`, but because `heroTitle` is a custom header that the object doesn't know about you would use `{{ child.header.hertoTitle }}`

Please try that first :)

**Comment by bluis4** [comment]
@rhukster , yeah i tried using ```{{ child.header.heroTitle }}``` too, but still not working.

**Comment by rhukster** [comment]
I have to say i'm super confused by what you are trying to do, but the first thing that jumps out at me as I look in your pages is that your using the `content:` collection correctly in `modular.md`, 

```
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _header
            - _content1
```

but in each of your modular pages `_content1` and `_header` you are again trying to use a content collection but with an invalid collection.

```
---
section_id: wi-master-header-content-section
section_class: wi-master-header-bg-overlay
id: home-header
title: 'Home Header'
content:
    -
        heroTitle: 'Homepage Hero Title'
        heroSubtitle: 'Homepage Hero Subtitle'
---
```

I think what you want is simply:

```
---
section_id: wi-master-header-content-section
section_class: wi-master-header-bg-overlay
id: home-header
title: 'Home Header'

heroTitle: 'Homepage Hero Title'
heroSubtitle: 'Homepage Hero Subtitle'
---
```

Then you can access things directly with `page.header.heroTitle` or `page.header.heroSubtitle`

`content:` in the frontmatter is reserved for collection definitions only. https://learn.getgrav.org/content/collections#example-collection-definition

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Page.php#L2461-L2467

You can have other collections defined, but by default `Page::collection()` will use `content`, but you can pass other top level collection definitions:

https://learn.getgrav.org/content/collections#multiple-collections
