### ISSUE TITLE
Page order different on remote server than local server, despite uploading entire site

### ISSUE THREAD

**Issue by Stretch2m** [getgrav/grav#1740]
I developed a Grav site and have several places where I'm using numeric folder prefix to specify the page order. The site works perfectly on my localhost server. When I upload an **exact copy** of the website to my Amazon EC2 server, Grav is not obeying my numeric ordering. I have now completely deleted and re-uploaded the entire folder structure twice, and this behavior still occurs. I am new to Grav so I don't know if I'm missing something. Please let me know if you have any ideas for what could be wrong. Thanks.

**Comment by rhukster** [comment]
Default ordering that relies on the filesystem can be different between platforms.  For most platforms it's alphanumeric and works as expected, but for some linux type filesystems, ordering is based on inodes, and the results can be strange.  

I thought we sorted the ordering issue before, but clearly it still exists.  I will have to look into this again. Hopefully you will be willing to test this as I don't have access to a server that has this issue

**Comment by Stretch2m** [comment]
Thank you rhukster. I am glad to hear that there may be an explanation for this! (I thought I was doing something wrong.) Yes I am willing to test this any way you need. FYI my localhost server is MAMP 3.3.1 running on Windows 7, and the EC2 server is Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1022-aws x86_64). Please let me know how I can help.

**Comment by rhukster** [comment]
Try changing the setting in System configuration for `pages.order.by` from `default` to `alpha`

**Comment by rhukster** [comment]
This is think was the solution we came up with, basically by default it will use the filesystem order, but you can optional change it to force alphanumeric ordering.

**Comment by Stretch2m** [comment]
I am not sure if I know how to do this. I am looking in /system/blueprints/config/system.yaml, which has the following:

```
                pages.order.by:
                    type: select
                    size: large
                    classes: fancy
                    label: PLUGIN_ADMIN.DEFAULT_ORDERING
                    help: PLUGIN_ADMIN.DEFAULT_ORDERING_HELP
                    options:
                        default: PLUGIN_ADMIN.DEFAULT_ORDERING_DEFAULT
                        folder: PLUGIN_ADMIN.DEFAULT_ORDERING_FOLDER
                        title: PLUGIN_ADMIN.DEFAULT_ORDERING_TITLE
                        date: PLUGIN_ADMIN.DEFAULT_ORDERING_DATE

```

In the admin console, the options I have for page ordering are:

- Default - based on folder name
- Folder - based on prefix-less folder name
- Title - based on title field in header
- Date - based on date field in header

I don't see "alpha" standing out as an option. Do you mean "Folder - based on prefix-less folder name"? (Wouldn't that ignore the numeric prefix?)

**Comment by Stretch2m** [comment]
FYI - I tried changing it to "Folder - based on prefix-less folder name" and it had no effect.

**Comment by rhukster** [comment]
Oh your in the system blueprints don't change that.

You need to change the value in `user/config/system.yaml`

```
pages:
  ...
  order:
    by: alpha
    dir: asc
```

**Comment by rhukster** [comment]
Ok, i've made a commit, should have a link in this issue.  Try adding those 3 lines to your install in the exact same location and the set your pages.order.by to `folder`

**Comment by Stretch2m** [comment]
It does not seem to have any effect. I updated system/src/Grav/Common/Page/Pages.php to include the three new lines where indicated:

```
                case 'basename':
                    $list[$key] = basename($key);
                    break;
                case 'folder':
                    $list[$key] = $child->folder();
                    break;
                case (is_string($header_query[0])):
                    $child_header = new Header((array)$child->header());
                    $header_value = $child_header->get($header_query[0]);
```

I then updated my user/config/system.yaml as directed:

```
pages:
  theme: upstate
  order:
    by: folder
    dir: asc
```

But the pages still don't obey the numeric prefix order. So I also tried updating the .md files for the affected parent pages (which were set to default) to have "folder" order:

```
content:
    items: '@self.children'
    limit: 0
    order:
        by: folder
        dir: asc
    url_taxonomy_filters: true
```

And this too had no effect. I'm certainly on board for testing some more but I'll have to pick it up tomorrow.
