### ISSUE TITLE
Form blueprint field cannot be called 'order'

### ISSUE THREAD

**Issue by Flamenco** [getgrav/grav#1864]
Form blueprint field cannot be called 'order'. 

```
   order:
     type: toggle
     label: Order
     help: Add before or after template
     highlight: 0
     default: 0
     options:
       1: Before
       0: After
     validate:
       type: bool  
```
Workaround:  Call it order_

<img width="730" alt="screen shot 2018-02-09 at 9 07 01 pm" src="https://user-images.githubusercontent.com/819940/36057537-4cfcd26e-0ddd-11e8-9df1-b1522c44ba84.png">
