### ISSUE TITLE
[BUG] numeric prefix doesn't work with modular

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav#1887]
Hi,

I'm having an issue with modular collection: 

The following is properly ordering the modular by name in `ASC` order.

```
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
```
But when you try to enable `Folder Numeric Prefix` to push some modular in the top of the list, they just stay at the same place.

It's because `Grav` rename modular folder with `numeric prefix` like this:
`_modular1` => `01._modular1`
when it should rename it like this:
`_modular1` => `_01.modular1`

As underscore will always be considered as higher that any number in `ASC` a modular named `01._modularA` will be placed after a modular named `_modularB` when it should be the contrary.
