### ISSUE TITLE
override_locale and utf-8

### ISSUE THREAD

**Issue by yurkobb** [getgrav/grav#1911]
With these settings in my `user/config/system.yaml`:

```yaml
languages:
  translations: true
  override_locale: true
  supported:
    - en
    - de
    - ru
```

Whenever I open a `/ru/` page, the locale is set to `ru_RU`. I would like it to be `ru_RU.UTF8`. How to achieve it?
