### ISSUE TITLE
Embeding the same form in a list and in a section (and fieldset)

### ISSUE THREAD

**Issue by pshe94** [getgrav/grav#1926]
Let's assume that I have a 'template' form named `options.yaml`:
```
form:
  fields:
    .options:
      type: checkboxes
      label: Options
      options:
        option_a: Option A
        option_b: Option B
      use: keys
```
I use this form to embed it in a list:
```
header.list:
  type: list
  label: List
  style: vertical
  import@:
    type: 'partials/options'
    context: blueprints://
```
I would like to reuse the same 'template' form in a section (and also in a fieldset):
```
header.section:
  type: section
  title: Section
  underline: true
  import@:
    type: 'partials/options'
    context: blueprints://
```
Unfortunately, embedding it in a section (and fieldset) doesn't work. Everything is displayed correctly in admin, but saving does not work (in fieldset I can't even check the checkbox). Is there any way to embed this 'template' form in section and fieldset? I would like to avoid duplicating the file and adding `header.` before every field name.
I could possibly change section to a list, and set `min` and `max` to 1, but I would also like to avoid this. 

Example I showed is very simplified. I have multiple 'templates' with many fields, that I later reuse in different places - some are in sections, some in fieldsets and some in lists. It would be a much simpler, if I could reuse the same file everywhere.
PS. I'm not sure if this is related to Grav or just Admin Plugin, so I'm posting it here.
