### ISSUE TITLE
Theme blueprints are broken / not working

### ISSUE THREAD

**Issue by heihachi88** [getgrav/grav#1941]
Following this example: https://learn.getgrav.org/forms/blueprints/example-page-blueprint

I created my video.yaml file under "user/themes/MYTHEMENAME/blueprints", contents of its file:

```
title: Gallery
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        gallery:
          type: tab
          title: Gallery

          fields:
            header.txf:
              type: text
              label: Add a number
              default: 5
              validate:
                required: true
                type: int

            header.sb:
              type: select
              label: Select one of the following
              default: one
              options:
                one: One
                two: Two
                three: Three
```

Cleared all caches, but i still don't see that tab under "/admin/pages" or "/admin/pages/home" advanced tab. What's wrong? Is it bug?

Tried new skeleton installation - same problem. This is bug 100%
