### ISSUE TITLE
Changes to images in one upload area affect the images in other upload areas using Admin.

### ISSUE THREAD

**Issue by glasswork** [getgrav/grav#1942]
Since at least three updates ago, when I make an image change to one upload area, it makes changes in multiple unassociated image upload areas even those where the images are in different folders, or those where the uploads area are in different tabs of the Admin. I have been hoping that the last two Grav updates would take care of this but they have not.

For instance:

Here is the yaml code for two image upload areas:

```
header.upper_hero_image_file:
              type: file
              label: Upload an image for the Upper Hero and Landing page display. (Required)
              destination: '@self/detail'
              multiple: false
              avoid_overwriting: true
              size: medium
              limit: 1
              accept:
                - 'image/*'

header.lower_hero_image_file:
              type: file
              label: Upload an image for the Lower Hero and Landing page display. (Optional)
              destination: '@self/detail'
              multiple: false
              avoid_overwriting: true
              size: medium
              limit: 1
              accept:
                - image/*
```

Both these areas (and many more besides) will be changed when a file is uploaded or deleted in either one or the other upload areas. 

I have been having to place images manually in their folders and then manually edit the .md file.
