### ISSUE TITLE
File's are being duplicated in admin plugin

### ISSUE THREAD

**Issue by heihachi88** [getgrav/grav#1950]
I've added "file" type input using blueprints:

```
            header.image:
              type: file
              label: News Main Image
              help: Upload news image here
              destination: '@self'
              filesize: 1
              accept:
                - image/*
              random_name: true
              # removed validation cause of known bug
```

When i upload image to this "image" field, it's also duplicated in "media_order" field:

![image](https://user-images.githubusercontent.com/5739191/38097930-7bf14cd6-3398-11e8-807b-05049a8958b2.png)
but if i upload first in "media_order" (called Page Media in admin plugin), it doesn't duplicates with my "image" field. Is this bug?
