### ISSUE TITLE
File upload in custom theme configuration adds a leading slash to file path

### ISSUE THREAD

**Issue by voeetech** [getgrav/grav#1952]
Grav version 1.3.10

I have a custom theme with a file upload field defined in the `blueprints.yaml` like this:

```
        header.smallBanner1:
          type: fieldset
          title: Small banner 1
          fields:
            header.smallBanner1.img:
              type: file
              label: img
              destination: 'theme@:/images/header'
              multiple: false
            header.smallBanner1.link:
              type: text
              label: link
```

In my dev server when I upload a file via the admin panel that corresponds to the above definition I get the following in the config file for the theme:

```
  smallBanner1:
    user/themes/horn/images/header/baner1_small.png:
      name: baner1_small.png
      type: image/png
      size: 11230
      path: user/themes/horn/images/header/baner1_small.png
    link: 'https://google.com'
```

However, in my production server that runs the same version of grav with the same version of the theme, the config file is slightly different in that it contains a leading slashes like this:

```
  smallBanner1:
    /user/themes/horn/images/header/baner1_small.png:
      name: baner1_small.png
      type: image/png
      size: 11230
      path: /user/themes/horn/images/header/baner1_small.png
    link: 'https://google.com'
```

This brakes both the theme configuration page:

![image](https://user-images.githubusercontent.com/820442/38117160-d8274972-33b3-11e8-8885-fc468bcf3f45.png)

AND the web site itself as the template uses the `path` which now has a leading slash and that seems to break the code (404 on the image request).

I cannot explain why those two servers behave in a different way since they run the same version of grav with the same version of the theme and I also checked that they both run the same version of all the plugins. 

Any ideas?
