### ISSUE TITLE
site.yaml redirect with `?` in it doesn't work

### ISSUE THREAD

**Issue by jlehtinen** [getgrav/grav#1983]
This redirect in `/user/config/site.yaml` fails because of the question mark. Removing it from the redirect & URL makes it work. Escaping it has no effect. 

--- 
redirects:
  '/dir/tools\.htm\?param=(.*)': '/dir/$1/another'
---

(Also, `=` needs to be unescaped to work. Not sure if this is a bug or how regex works.)

**Comment by rhukster** [comment]
I have a fix for this in develop.  However, it does not a tweak to your regex.  You need to escape the `.` and the `?` as they are special charaters in regex:

```
redirects:
   '/dir/tools\.htm\?param=(.*)': '/dir/$1/another'
```

**Comment by jlehtinen** [comment]
Wow, that was quick. Thanks so much!

**Comment by HunterDG** [comment]
Is this related to links with question marks not working when embedded in markdown pages?  e.g. https://kb.wisc.edu/page.php?id=47883

**Comment by rhukster** [comment]
as i said in previous comment you have to escape the ? with a \

**Comment by HunterDG** [comment]
tried that, and https%3A%2F%2Fkb.wisc.edu%2Fpage.php%3Fid%3D47883

**Comment by rhukster** [comment]
please paste the site.yaml file.

**Comment by HunterDG** [comment]
this is in default.md, using latest grav/quark theme, 

```
- [test 1](https://kb.wisc.edu/page.php?id=47883)
- [test 2](https://kb.wisc.edu/page.php\?id=47883)
- [test 3](https://kb.wisc.edu/page.php%3Fid%3D47883)
- [test 4](https%3A%2F%2Fkb.wisc.edu%2Fpage.php%3Fid%3D47883) 
```

**Comment by HunterDG** [comment]
<details><summary>user/config/site.yaml</summary>
<p>

```
title: Title
default_lang: en
author:
  name: 'name'
  email: email@email.com
taxonomies:
  - category
  - tag
metadata:
  description: 'description'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
```
</p>
</details>

<details><summary>system/blueprints/config/site.yaml</summary>
<p>

```
title: PLUGIN_ADMIN.SITE
form:
    validation: loose
    fields:

        content:
            type: section
            title: PLUGIN_ADMIN.DEFAULTS
            underline: true

            fields:
                title:
                    type: text
                    label: PLUGIN_ADMIN.SITE_TITLE
                    size: large
                    placeholder: PLUGIN_ADMIN.SITE_TITLE_PLACEHOLDER
                    help: PLUGIN_ADMIN.SITE_TITLE_HELP

                default_lang:
                    type: text
                    label: PLUGIN_ADMIN.SITE_DEFAULT_LANG
                    size: x-small
                    placeholder: PLUGIN_ADMIN.SITE_DEFAULT_LANG_PLACEHOLDER
                    help: PLUGIN_ADMIN.SITE_DEFAULT_LANG_HELP

                author.name:
                    type: text
                    size: large
                    label: PLUGIN_ADMIN.DEFAULT_AUTHOR
                    help: PLUGIN_ADMIN.DEFAULT_AUTHOR_HELP

                author.email:
                    type: text
                    size: large
                    label: PLUGIN_ADMIN.DEFAULT_EMAIL
                    help: PLUGIN_ADMIN.DEFAULT_EMAIL_HELP
                    validate:
                        type: email

                taxonomies:
                    type: selectize
                    size: large
                    label: PLUGIN_ADMIN.TAXONOMY_TYPES
                    classes: fancy
                    help: PLUGIN_ADMIN.TAXONOMY_TYPES_HELP
                    validate:
                        type: commalist

        summary:
            type: section
            title: PLUGIN_ADMIN.PAGE_SUMMARY
            underline: true

            fields:
                summary.enabled:
                    type: toggle
                    label: PLUGIN_ADMIN.ENABLED
                    highlight: 1
                    help: PLUGIN_ADMIN.ENABLED_HELP
                    options:
                        1: PLUGIN_ADMIN.YES
                        0: PLUGIN_ADMIN.NO
                    validate:
                        type: bool

                summary.size:
                    type: text
                    size: small
                    append: PLUGIN_ADMIN.CHARACTERS
                    label: PLUGIN_ADMIN.SUMMARY_SIZE
                    help: PLUGIN_ADMIN.SUMMARY_SIZE_HELP
                    validate:
                        type: int
                        min: 0
                        max: 65536

                summary.format:
                    type: toggle
                    label: PLUGIN_ADMIN.FORMAT
                    classes: fancy
                    help: PLUGIN_ADMIN.FORMAT_HELP
                    highlight: short
                    options:
                        'short': PLUGIN_ADMIN.SHORT
                        'long': PLUGIN_ADMIN.LONG

                summary.delimiter:
                    type: text
                    size: x-small
                    label: PLUGIN_ADMIN.DELIMITER
                    help: PLUGIN_ADMIN.DELIMITER_HELP

        metadata:
            type: section
            title: PLUGIN_ADMIN.METADATA
            underline: true

            fields:
                metadata:
                   type: array
                   label: PLUGIN_ADMIN.METADATA
                   help: PLUGIN_ADMIN.METADATA_HELP
                   placeholder_key: PLUGIN_ADMIN.METADATA_KEY
                   placeholder_value: PLUGIN_ADMIN.METADATA_VALUE

        routes:
            type: section
            title: PLUGIN_ADMIN.REDIRECTS_AND_ROUTES
            underline: true

            fields:
                redirects:
                    type: array
                    label: PLUGIN_ADMIN.CUSTOM_REDIRECTS
                    help: PLUGIN_ADMIN.CUSTOM_REDIRECTS_HELP
                    placeholder_key: PLUGIN_ADMIN.CUSTOM_REDIRECTS_PLACEHOLDER_KEY
                    placeholder_value: PLUGIN_ADMIN.CUSTOM_REDIRECTS_PLACEHOLDER_VALUE

                routes:
                    type: array
                    label: PLUGIN_ADMIN.CUSTOM_ROUTES
                    help: PLUGIN_ADMIN.CUSTOM_ROUTES_HELP
                    placeholder_key: PLUGIN_ADMIN.CUSTOM_ROUTES_PLACEHOLDER_KEY
                    placeholder_value: PLUGIN_ADMIN.CUSTOM_ROUTES_PLACEHOLDER_VALUE
```
</p>
</details>

**Comment by HunterDG** [comment]
Should I open a new issue?  Seems the "id" attribute on external links is ignored.

```markdown
['id' attribute not passed through](https://kb.wisc.edu/page.php?id=47883)
[but 'idd' works](https://kb.wisc.edu/page.php?idd=47883)
```

**Using the example from [Pass-through of Non-Supported Attributes](https://learn.getgrav.org/16/content/linking#pass-through-of-non-supported-attributes)** doesn't work for 'id' attribute

```markdown
[Pass-through of 'cat and id' attribute](../some-page?classes=underline&cat=black&id=blue)
```

it's as if `&noprocess=id` is being enforced somewhere.  Is this a setting I can find?

**Comment by HunterDG** [comment]
I found that if I _remove_ the 'id' attribute from Configuration - System > Markdown > Valid Link Attributes, then they are properly passed through/external links work.  Is this desired behavior?  Seems not but I could be misunderstanding "Valid Link Attributes" function.

**Comment by mahagr** [comment]
@rhukster What do you think?

**Comment by HunterDG** [comment]
Apologies - I have realized I misunderstood, added `id` back to Valid Link Attributes (target already exists), and decided to try `&noprocess=id` per [Skip Certain Attributes](https://learn.getgrav.org/16/content/linking#skip-certain-attributes), but...

```markdown
[Skip Certain attributes](../some-page?id=myvariable&classes=underline&target=_blank&noprocess=id,classes)
```
results in:
```html
<a href="/grav/some-page?id=myvariable&classes=underline&target=_blank">Skip Certain attributes</a>
```

**NOT**
```html
<a href="/grav/some-page?id=myvariable&classes=underline" target="_blank">Skip Certain attributes</a>
```

system.yaml:
```yaml
pages:
  markdown:
    valid_link_attributes:
      - id
      - rel
      - target
      - class
      - classes
```
