### ISSUE TITLE
How can I define custom autocomplete data for a selectize field?

### ISSUE THREAD

**Issue by bouiboui** [getgrav/grav#2002]
Hi! 

I have made several plugins for Grav now, and there's a recurring feature that is missing, or that I don't know how to implement correctly.

This is what I want to achieve:
![image](https://user-images.githubusercontent.com/3274103/39419399-11c05772-4c60-11e8-81b8-a16a96da3b1d.png)

The user can type the first letters of the name of a city and the field auto-completes if the city has been defined in the blueprint, or he can write a custom city name.

As you see in the example, I've reached my goal, but the downside is that I have to add my valid city names as `default` data of the field, which is messy, and hugely user-unfriendly:
```yaml
.where:
  type: selectize
  label: Lieu de la réunion (ville)
  default:
    <<: *villes-france
```
![image](https://user-images.githubusercontent.com/3274103/39419627-fdce086c-4c60-11e8-8f25-f1a9fd77db0a.png)

Ideally, I could define my custom autocomplete data like the following (see `options`):

```yaml
.where:
  type: selectize
  label: Lieu de la réunion (ville)
  options:
    <<: *villes-france
```
...which would render a blank input by default, and suggest my `options` data as autocomplete values.

Is there already a way to do this?

Thanks!

**Comment by drnasin** [comment]
Would this help? https://learn.getgrav.org/cookbook/admin-recipes#add-a-custom-select-field

**Comment by bouiboui** [comment]
Not exactly unfortunately, because I want the user to be able to enter his custom option if none of the options is correct.

**Comment by gvstavnev** [comment]
You can do the following:

**blueprint.yaml**
```
.where:
  type: selectize
  label: Lieu de la réunion (ville)
  selectize:
    @data-options: '\Grav\Theme\YourThemeName::villesfrance'
  validate:
    type: commalist
```

**themes/yourthemename/yourthemename.php** add the function

```
    public static function villesfrance() 
    {
        return array(
            array ('text' => 'Agen', 'value' => 'Agen'),
            array ('text' => 'Saint-Joseph', 'value' => 'Saint-Joseph')

            # and so on… #

        );
    }

```

That way the user is still able to type his custom option or to choose from your options.
