### ISSUE TITLE
Selecting multiple file blueprint bug

### ISSUE THREAD

**Issue by grisaa** [getgrav/grav#2025]
i'm trying to create a blueprint that allows selecting `multiple: true` images, but gives me an error when saving.

the code:
```yaml
header.multiplefiles:
  label: Images
  type: filepicker
  folder: 'self@'
  preview_images: true
  accept:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .svg
  multiple: true
```

as `pagemediaselect`:
```yaml
header.multiplefiles:
  type: pagemediaselect
  multiple: true
```

doesn't save and gives this error:
> Whoops \ Exception \ ErrorException (E_NOTICE)
> Array to string conversion

i tried validating with `validation.type: commalist` and `validation.type: array`, but still no luck. it saves but gives this error:
> Twig_Error_Runtime
> An exception has been thrown during the rendering of a template ("Array to string conversion").

am i missing something?

**Comment by rhukster** [comment]
You are using `filepicker`, and it should be `file`:

```
        photos:
            label: Photos
            type: file
            destination: 'user/media/stories'
            multiple: true
            autofocus: false
            resizeWidth: 2560
            resolution:
                min: 
                    width: 1600
                    height: 900             
            accept:
                - image/jpeg 
```

works fine...

**Comment by NicoHood** [comment]
I have the same issue! pagemediaselect is not functional at all for me!

```yaml
header.gallery:
  type: pagemediaselect
  label: "Bildergalerie"
  multiple: true
  preview_images: true
  validate:
    type: array
```
Gives error: `Array to string conversion`

Related unanswered questions:
https://discourse.getgrav.org/t/pagemediaselect-error-when-saving/3621
https://discourse.getgrav.org/t/filepicker-pagemediaselect-returns-empty/8493/2
