### ISSUE TITLE
1:M relationships and searching collections by custom header field

### ISSUE THREAD

**Issue by pierluigi** [getgrav/grav#2052]
I am trying to create a 1:M relationship ("An release belongs to 1 artist, and an artist can have M releases") in Grav by using a custom field (`uuid`) defined via a blueprint, like so:

Release: 
```yaml
# blueprints/release.yaml
title: Release Entry
extends@: default

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        advanced:
          fields:
            overrides:
              fields:
                header.uuid:
                  type: text
                  label: 'Unique ID - do not modify'
                  data-default@: '\Grav\Theme\Upitup::uuid'
                  readonly: true
        content:
          fields:
            header.artist:
              type: select
              label: Select artist
              data-options@: '\Grav\Theme\Upitup::getArtists'
```

Artist:
```yaml
#blueprints/artist.yaml
title: Artist Entry
extends@: default

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        advanced:
          fields:
            overrides:
              fields:
                header.uuid:
                  type: text
                  label: 'Unique ID - do not modify'
                  data-default@: '\Grav\Theme\Upitup::uuid'
                  readonly: true
```

My theme functions are defined as follows:

```php
class Upitup extends Theme
{

    public static function uuid()
    {
        return uniqid(null, true);
    }

    public static function getArtists() 
    {
        $page = Grav::instance()['page'];
        $collection = $page->evaluate(['@page.children' => '/artists']);

        $options = [];
        foreach ($collection as $artist) {
            $options[$artist->header()->uuid] = $artist->title();
        };

        return $options;
    }
```

My goal is to show the Artist of a a specific Release. All I could figure out so far is to get all Pages of type "Artist" and checking one by one for the specific uuid I"m looking for, which is obviously suboptimal. Like so:

```twig

{% set artists = page.evaluate([{'@page':'/artists'}]) %}
{% for artist in artists %}
    {% if artist.header.uuid == page.header.artist %}
       Release by {{ artist.title }}
    {% endif %}
{% endfor %}
```

I read the manual twice but I couldn't figure out what's the best way to achieve this simple scenario. 
Is there a recommended way in Grav to filter collections by a custom value?

Many thanks!
