### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by bilel** [getgrav/grav#2081]
Hi :)
For SEO, Internationalization and centralization purpose, I'd like to use subdomains (as alias) pointing to the same Grav' root directory , share the same layout and tools (dashboard, theme, plugins...) but showing different appropriate content/translations.

pix.com =>English
de.pix.com => German  (without /de prefix)
fr.pix.com => French
...

After reading this draft : https://github.com/getgrav/grav/issues/170 , 
I found some interesting ideas! But after many failed attempts, I'd like to know if Grav is allowing such architecture.

Is it possible using the latest Grav release? Any tips for how to realize that? Via Custom Routes or system.yaml?

P.S: I'm on a VPS using nginx as reverse proxy for Apache

Thank you :)

**Comment by Perlkonig** [comment]
The simplest way Grav handles multilingual content is [via url (e.g., `/fr`, `/de`](https://learn.getgrav.org/content/multi-language#active-language-via-url). So you should be able to create a redirect rule in `.htaccess` (or the nginx equivalent) that rewrites the request to the appropriate URL. This assumes all your subdomains point to the same place and that your slugs don't change by language.

**Comment by bilel** [comment]
Thank you for your answer. 
 It's better to have translated slugs as well. I'll spend some time reading Grav code & Doc and find out how to do it.


Certbot rollback helped me recover my functional configuration :)

And I see the issue was already reported before
https://github.com/getgrav/grav/issues/1226#issuecomment-354992065

Hopefully I'll find a way to do that without touching to the core.

**Comment by bilel** [comment]
First experiments with a specific plugin are promising good results... I'll publish it on github when ready.

**Comment by bilel** [comment]
I gave up  on "reinventing the wheel " ! :) Grav already took care of this without a plugin or extra redirect or rewriting rules...

Let's assume your main domain is fifa.com
your french subdomain is : fr.fifa.com
your dutch subdomain is : nl.fifa.com

Just follow these steps:

1- configure your aliases (virtualhosts) on your server 
2- create new directory with your subdomain name under user' folder
3- create another subdirectory : config

4- Now that we have   /user/fr.fifa.com/config, 
We will create a file **sytem.yaml** for the french version under config directory with the following content:

```
languages:
  include_default_lang: false
  supported:
    - **fr**
    - en
    - nl
```

And do the same for the dutch version by moving "nl" to the top of linguistic priority order :
/user/nl.fifa.com/config/system.yaml

```
languages:
  include_default_lang: false
  supported:
    - **nl**
    - en
    - fr
```

**Comment by mahagr** [comment]
Yup, that is the way to do it with multisite feature :)

**Comment by bilel** [comment]
Didn't tried multisite feature yet ! I thought it was meant to serve only multisites with different (content, themes...)

To get subdomains paths, I added custom blueprints: in user/blueprints/config/site.yaml

```
@extends:
    '@parent'

form:
    fields:
        anothersection:
            type: section
            title: Subdomains
            underline: true
        subdomains:
          type: array
          label: subdomains
          size: large
```
I define my subdomains in the config' panel. Ex:
en => life.com
de => reise.life.com
fr => voyage.life.com  

Later, when needed, I can use paths in template files or plugins like the following:
`config.site.subdomains[active_language_key]`
