### ISSUE TITLE
Toggle field not remembering current state

### ISSUE THREAD

**Issue by cabajian** [getgrav/grav#2097]
In my form.yaml file, I have the following field:

```
.validate.required:
    type: toggle
    highlight: true
    default: true
    options:
        true: YES
        false: NO
    validate:
        type: bool
    label: Required
```
and this correctly shows up in the admin panel and works with my form.md header. However, the selected option in the admin panel is overridden by the default value every time I refresh.

How do I get the value in the admin panel to show the current state?
