### ISSUE TITLE
theme_var('spectre.icons') always false in theme inheriting from Quark

### ISSUE THREAD

**Issue by tremel** [getgrav/grav#2128]
`theme_var('spectre.icons')` seems to return false in a theme inheriting from Quark 1.1.0 on grav 1.4.8.

This worked before, the icons css was included, but isn't any more. When I set to `{% if true %}` in `partials/base.html.twig` the css is rendered.

`saintjosse.yaml`:
```
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/saintjosse
         - user/themes/quark
enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: '/blog'
spectre:
  exp: false
  icons: true
```

**Comment by rhukster** [comment]
Nothing has changed in this function:

```
    /**
     * Get a theme variable
     *
     * @param $var
     * @param bool $default
     * @return string
     */
    public function themeVarFunc($var, $default = null)
    {
        $header = $this->grav['page']->header();
        $header_classes = isset($header->$var) ? $header->$var : null;
        return $header_classes ?: $this->config->get('theme.' . $var, $default);
    }
```

As you can see it's pretty simple, and first checks a page header variable, else it falls back to the current 'theme' config.

Did you add a page-level setting?

**Comment by rhukster** [comment]
I just tested this with a quark inherited theme:

```
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/quark-child
         - user/themes/quark

enabled: true
production-mode: true
grid-size: grid-sm
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: '/blog'
spectre:
  exp: false
  icons: false
```

And the `grid-size` change in the child theme clearly worked.
