### ISSUE TITLE
can only save one option in selectize

### ISSUE THREAD

**Issue by gvstavnev** [getgrav/grav#2149]
When i do the following:

**blueprint.yaml**

```yaml
.test:
  type: selectize
  selectize:
    options:
       - text: testtext1
         value: testvalue1
       - text: testtext2
         value: testvalue2
       - text: testtext3
         value: testvalue3
  validation:
    type: commalist
```

Iam not able to save more than one option when i save the page.

**Edit01:**
With changes to the `selectize.html.twig` by @parcand in [issue #1229](https://github.com/getgrav/grav-plugin-admin/issues/1229) it works.

oops. it belongs to grav-plugin-admin. sorry
