### ISSUE TITLE
Partial blueprints do not save when in a list element

### ISSUE THREAD

**Issue by geme** [getgrav/grav#2156]
**Summary**
When you want to import partial blueprints in a list element the blueprint will render properly in the admin panel. But if you populate the fields and save the changes the content will not be inserted into the corresponding page file.

Values will be saved if the partial blueprint have absoulte ids like header.id, header.name, header.type but then all the items in the list will share the same values.

If the partial blueprint code is copied in place of the import statement it works properly.

**Steps to Reproduce**
1. Create two blueprint files:
> FilterItems.yaml
``` yaml
title: FilterItems
'@extends':
  type: default
form:
  fields:
    tabs:
      fields:
        options:
          type: ignore
        advanced:
          type: ignore
        content:
          fields:
            content:
              type: ignore
            header.media_order:
              type: ignore
            header.title:
              type: ignore
            header.custom.filterItems:
              type: list
              title: filter items
              name: filter items
              label: filter items
              style: vertical
              fields:
                .filterItem:
                  type: section
                  import@:
                    type: partials/FilterItem
                    context: blueprints://
```

> blueprints/partials/FilterItem.yaml
``` yaml
form:
  fields:
    .id:
      label: unique identifier
      type: text
      validate: 
        required: true
    .name:
      label: name
      type: text
      validate: 
        required: true
    .value:
      label: value
      type: text
      validate: 
        required: true
``` 
2. Open the admin panel
3. Add a Filteritems page
4. Observe that the Template is rendered correctly 
![bildschirmfoto 2018-08-24 um 14 52 30](https://user-images.githubusercontent.com/2890619/44585665-5e6a3680-a7ad-11e8-908d-cc01a5dd64c2.png)
5. Enter mock data
6. Save the changes
7. Observe that after a reload the mock data vanished and the changes are not stored inside the corresponding markdown file.

**Expected Result**
> FilterItems.md
``` markdown
--- 
custom:
    filterItems:
        -
            id: sadf
            name: sdf
            value: sdf
        -
            id: dfg
            name: dgf
            value: dfg
---
```

**Actual Result**
> FilterItems.md
``` markdown
---
---
```

**Additonal Infos**
- GravCMS Version 1.5.1
- Admin panel  Version 1.8.9

**Comment by rhukster** [comment]
@mahagr any ideas just looking at this?

**Comment by geme** [comment]
I think it has something todo with that you cannot use relative/nested key notation for the field elements but have to use absolute ones.
like:
realtive:
``` yaml
form:
  fields:
    header.custom.foo:
      type: section
      fields:
        .id:
          type: text
```

absolute:
``` yaml
form:
  fields:
    header.custom.foo:
      type: section
      fields:
        header.custom.foo.id:
          type: text
```
should result in the same output:
```
--- 
custom:
  foo:
    id: bar
---
```

is there a reason why we cannot use relative/nested keys? 
In a `type: list` there is no other way than to use relative. But it would be great to use it anywhere.
