### ISSUE TITLE
Relative URLs linked from external CSS assets not getting rewritten

### ISSUE THREAD

**Issue by marshmn** [getgrav/grav#2216]
I am making use of an external CSS library through the asset manager:

```
{% do assets.addCss('https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css') %}
```

I've enabled CSS pipeline with the options to bring in external CSS assets and to rewrite any relative URLs in them:

```
assets:
  css_pipeline: 1
  css_pipeline_include_externals: true
  css_pipeline_before_excludes: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
```

However, the URLs are not getting rewritten - they are being left as relative paths. This naturally then leads to a failed request since the linked file is not available on my server.

The relevant portion of the CSS file:

```
/* Marker setup */
.awesome-marker {
  background: url('images/markers-soft.png') no-repeat 0 0;
  width: 35px;
  height: 46px;
  position:absolute;
  left:0;
  top:0;
  display: block;
  text-align: center;
}
```
