### ISSUE TITLE
Complex lists in plugin config blueprint saving but not rendering existing data in form

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav#2236]
I may be experiencing a side-effect of the problems described in #2156, it's hard for me to tell. Seems like a different set of problems in the same part of Grav.

The plugin config blueprint I've built so far is saving the correct YAML, but some field values are not shown/loaded into the form controls after saving. So subsequent saves will blank the values unless the same data is re-entered.

I'm trying make blueprints for the following structure, which seems most easily represented by example:

```yaml
hours:
  -
    name: opening
    timezone: Pacific/Auckland
    completed_until: '2019-01-15'
    microdata:
      type: Store
    regular:
      monday:
        - { starts: '09:00', stops: '18:00' }
        - { starts: '19:00', stops: '22:00' }
      tuesday:
        { starts: '09:00', stops: '18:00' }
      ...
  -
    name: on-call # this is a hypothetical second item stub
    ...
```
(I will preferably want to single-source the schedule part (`starts`, `stops` pairs) but that's for later and not the issue. Right now I'm copying and pasting the same pattern.)

So `hours` is a list. The first three properties in each list member are simple and store and render correctly in the config form.

`microdata` has defined child properties (only one right now), stores correctly in YAML but does not populate the value in the config form.

`regular` has defined child properties (`monday` etc) which each contain a list whose items contain two defined properties (`start`, `stop`). They store correctly in YAML (I think?) but do not render items or values in the config form.

Here is what I see after saving the above data:

![blueprint-issue](https://user-images.githubusercontent.com/288202/47417866-69553d80-d7d5-11e8-9559-12b943c12600.png)

Relevant parts of my blueprints.yaml form:

```YAML
form:
  validation: strict
  fields:
    enabled:
      type: toggle
      label: Plugin status
      highlight: 1
      default: 0
      options:
        1: Enabled
        0: Disabled
      validate:
        type: bool

    hours:
      type: list
      style: vertical
      btnLabel: 'Add Calendar'
      controls: both
      fields:

        .name:
          type: text
          label: Name
          help: "Provide a short unique name to use to refer to this calendar, e.g. 'opening'."
          validate:
            required: true
            rule: slug

        .timezone:
          type: select
          label: Timezone
          data-options@: '\Grav\Plugin\QuandoPlugin::timezoneHash'
          config-default@: system.timezone
          validate:
            required: true

        .completed_until:
          type: date
          label: 'Updated until'
          hint: 'Mainly to help you keep track of edits, could also be displayed in a page on your site.'

        .microdata.type:
          type: text
          label: 'Microdata type'
          hint: "Microdata is available for search engines to classify your business when displaying hours and other business information, e.g. 'Dentist'."

        .regular.monday:
          type: list
          label: 'Monday'
          btnLabel: 'Add Schedule'
          fields:
            .starts:
              type: time
              label: 'Starts'
              validate:
                required: true
            .stops:
              type: time
              label: 'Stops'
              validate:
                required: true
```
Please let me know if this is a bug, I'm doing it wrong, or if there's a workaround. This complexity of structure is understandably not thoroughly documented.

Cheers
