### ISSUE TITLE
Very slow page rendering with grav but not other php sites

### ISSUE THREAD

**Issue by zeigerpuppy** [getgrav/grav#2312]
I have been trying to debug very slow page loading with grav.  The first thing I did was install a clean grav install using the git method.
For a basic new install of grav ( see https://grav.stemtalk.net/ ) page loads are taking more than 2 seconds.  Other PHP sites on the same server are loading almost instantaneously (1.75ms for an example Textpress site).

Config:
- latest grav
- running in KVM virtual machine with SSD backed storage (ZFS zvol shared with KVM as block device, > 1GB/s write speeds)
- 4x Xeon SIlver vCPU, 4GB RAM allocated to VM
- Debian 9, nginx 1.10.3, php 7.0, php7.0-fpm
- reverse nginx proxy (but I have also tried without the proxy and the loads are still slow)
- there are no DNS delays, no error messages in nginx or grav error logs
- 1Gbps network upload speed

Caching
- memcache working and tested: https://grav.stemtalk.net/memcache_test.php
- the grav debug interface is showing `Page cache hit` messages
- apc is also installed
- the cache `auto` setting prefers `apcu` but requests are slow even if I force `memcache`

Any other suggestions to work out the slow performance?

------------------------------------------

grav config:
```yaml
absolute_urls: false

home:
  alias: '/home'

pages:
  theme: quark
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'
  memcache:
    server: localhost
    port: 11211

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: true
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true
```

Nginx config:

```nginx
server {
        listen 80;
        server_name  www.grav.stemtalk.net grav.stemtalk.net;

        root /var/www/grav/grav.stemtalk.net;

        # settings to enable PHP (conf contact form)
        index index.html index.php;

        ## Begin - Index
        # for subfolders, simply adjust:
        # `location /subfolder {`
        # and the rewrite to use `/subfolder/index.php`
        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }
        ## End - Index

        ## Begin - Security
        # deny all direct access for these folders
        location ~* /(\.git|cache|bin|logs|backup|tests)/.*$ { return 403; }
        # deny running scripts inside core system folders
        location ~* /(system|vendor)/.*\.(txt|xml|md|html|yaml|yml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }
        # deny running scripts inside user folder
        location ~* /user/.*\.(txt|md|yaml|yml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }
        # deny access to specific files in the root folder
        location ~ /(LICENSE\.txt|composer\.lock|composer\.json|nginx\.conf|web\.config|htaccess\.txt|\.htaccess) { return 403; }
        ## End - Security

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        }

}
```

reverse proxy config (on separate VM):

```nginx
server {
    listen      80;
    server_name grav.stemtalk.net www.grav.stemtalk.net;
    return 301 https://$server_name$request_uri;
}

server {
        listen 443 ssl;
#       listen [::]:443 default_server ipv6only=on;
        server_name grav.stemtalk.net www.grav.stemtalk.net;

        ssl_certificate    /etc/letsencrypt/live/www.grav.stemtalk.net/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/www.grav.stemtalk.net/privkey.pem;

# GRAV is served by blog2 server (nginx)
    location / {
      proxy_pass http://blog2;
      proxy_redirect http://blog2 $scheme://$host/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 20d;
      proxy_ssl_session_reuse off;

      proxy_set_header  Host $host;
      proxy_set_header  X-Real-IP $remote_addr;
      proxy_set_header  X-Forwarded-Proto https;
      proxy_set_header  X-Forwarded-For $remote_addr;
      proxy_set_header  X-Forwarded-Host $remote_addr;
    }


}

```

grav was installed using git method:

```bash
hostname=grav.stemtalk.net
cd /var/www/grav/
mkdir $hostname
sudo chown www-data:www-data $hostname
sudo -u www-data git clone -b master https://github.com/getgrav/grav.git $hostname
cd $hostname
sudo -u www-data composer install --no-dev -o
sudo -u www-data bin/grav install
sudo -u www-data bin/gpm install admin
```
