### ISSUE TITLE
Image filter with media.yaml does not work

### ISSUE THREAD

**Issue by Rotzbua** [getgrav/grav#2313]
## Environment

Grav: 1.5 and 1.6
php 7.1

## Bug

Added grayscale filter to `media.yaml`.

Expected:
Grayscale pictures

Observed:
No change

Any image filter defined in `media.yaml` are not used.
Seems it is the old #984 .

## Reproduce & test

Used: default `media.yaml`
Paths: `system/config` and `user/config`

Modified:
```yaml
types:
  defaults:
    type: file
    thumb: media/thumb.png
    mime: application/octet-stream
    image:
      filters:
        default:
          - grayscale
```
Also changed:
```yaml

  jpg:
    type: image
    thumb: media/thumb-jpg.png
    mime: image/jpeg
    filters:
      - grayscale
  jpe:
    type: image
    thumb: media/thumb-jpg.png
    mime: image/jpeg
    filters:
      - grayscale
  jpeg:
    type: image
    thumb: media/thumb-jpg.png
    mime: image/jpeg
    filters:
      - grayscale
```

Images do not change at all.
