### ISSUE TITLE
How to associate pagemedia with editor fields?

### ISSUE THREAD

**Issue by mondayCoding** [getgrav/grav#2328]
This is more likely more about my lack of knowledge than actual issue but here goes.

I created custom modular template and blueprint (extending default) with the intent of having multiple markdown content editors. This seems to be working fine aside from image links which are parsed incorrectly in template. 

I am think I am missing the point where I associate output from new editors with pagemedia collection? 

**yml:**

```
                header.custom.secondaryContent:
                     type: editor
                     label: Secondary-Content
                     default: ''
                     ordering@: 2

                  header.custom.tertiaryContent:
                     type: editor
                     label: Tertiary-Content
                     default: ''
                     ordering@: 3

                  header.media_order:
                     type: pagemedia
                     label: PLUGIN_ADMIN.PAGE_MEDIA
                     ordering@: 4
```

**Twig template:** 

```
   {{ content }}
   {{ page.header.custom.secondaryContent|markdown }}
   {{ page.header.custom.tertiaryContent|markdown }}
```

Links inside original content-tag work just fine while those generated from secondaryContent/tertiaryContent are just relative links to current page.
