### ISSUE TITLE
Setting to create global fallback for hero image

### ISSUE THREAD

**Issue by notklaatu** [getgrav/grav#2333]
Version: Grav 1.5.6
OS: CentOS 7.x
Theme: Quark

When I create a blog post, my entire site breaks if the hero_image is either not found, corrupted, misspelled, or otherwise unavailable.

I've search the docs and haven't found an official way to work around this, so I'm requesting a config option somewhere to activate a global fallback image. The goal is to be able to post this:

```
---
title: My great post
author: My great name
date: 01:01 01/01/2019
hero_classes: text-light title-h1h2 overlay-dark-gradient hero-large parallax
hero_image: some-file-that-doesnt-exist.jporg
taxonomy:
    category: foo
    tag: bar
---

Some text here.
```

And not break my entire site.

So far I've been placing symlinks to a common generic header.jpg file, but in the end that's subject to the same problems (if it gets linked incorrectly, and so on).
