### ISSUE TITLE
blueprint import@ with param

### ISSUE THREAD

**Issue by JulienCastejonPURJUS** [getgrav/grav#2346]
Hi,
I want to create a partial for the header of all my pages, so I'm able to import it in every pages that need a header.

But the thing is, when importing this partial I would like to set a specific `destination` (for `file` fields) depending on the page that imports the partial.

Like :
**page1.yaml :**
```
imports@:
    type: partials/header
    context: blueprints://
    params:
        upload_dir: 'foo/upload/dir/path1'
```

**page2.yaml :**
```
imports@:
    type: partials/header
    context: blueprints://
    params:
        upload_dir: 'foo/upload/dir/path2'
```

**partials/header.yaml :**
```
...
    .image:
        type: file
        destination: @upload_dir
```

Is there any way to do this?

**Comment by mahagr** [comment]
Or you can just create a configuration option (to a plugin), which you read from the blueprint.

```yaml
    .image:
        type: file
        config-destination@: plugins.myplugin.upload_dir
```
