### ISSUE TITLE
Feature request: Ability to use translation system in configuration files.

### ISSUE THREAD

**Issue by Lufog-git** [getgrav/grav#2364]
In some plugins, through configuration files, we can define various strings and labels, which should change depending on the interface language. 

I will try to give an example.  In the [data-manager plugin](https://github.com/getgrav/grav-plugin-data-manager), through the configuration file, we can customize the presentation of certain data, including the names of a specific lists. For example:

```yaml
enabled: true
types:
  lyric:
    name: 'Song lyrics'   # need the ability to translate
    list:
      columns:
        - field: artist
          label: Artist   # need the ability to translate
        - field: name
          label: Name   # need the ability to translate
        - field: language 
          label: Language   # need the ability to translate
```

How do I see the solution:
```yaml
enabled: true
types:
  lyric:
    name: PLUGIN_DATA_MANAGER.LYRIC.NAME
    list:
      columns:
        - field: artist
          label: PLUGIN_DATA_MANAGER.LYRIC.LIST.COLUMNS.ARTIST
        - field: name
          label: PLUGIN_DATA_MANAGER.LYRIC.LIST.COLUMNS.NAME
        - field: language 
          label: PLUGIN_DATA_MANAGER.LYRIC.LIST.COLUMNS.LANGUAGE
```

In ```user/languages/en.yaml```:

```yaml
PLUGIN_DATA_MANAGER:
   LYRIC:
      NAME: 'Song lyrics'
      LIST:
         COLUMNS:
            ARTIST: Artist
            NAME: Name
            LANGUAGE: Language
```

Although I described an example on a specific plugin, I understand that the processing of configuration files takes place in the grav-core. That's why I request this feature, in this repository.
