### ISSUE TITLE
Page order override in front matter

### ISSUE THREAD

**Issue by neilpanchal** [getgrav/grav#2396]
Hello all,

I've been discussing this issue on Discord channel and thought I'd open it up here. I would like to order navigation items manually and without relying on "0#.folder_name" prefix. I prefer having folder names as "folder_name". 

**Goal:**
To override the folder prefix (e.g. "01.home", "02.features", "03.about", etc...) and use a front matter variable.

**Why?**
I'd like to have my folder structure without the burden of ordering. It is a weird choice for grav to use a folder prefix without a clear way to override this behavior, perhaps I am missing something obvious?

**What did I try**
In system.yaml, I tried the following. Most options such as ordering by title, ordering by date, etc work but the manual order does not work: 

```
pages:
  theme: hypertext
  order:
    by: manual
    dir: asc
    custom:
      - home
      - features
      - about
```

but I always get my nagivation loop showing up as:
`about | features | home`

I also tried putting this in the front matter in the `home` page:
```
---
title: Home
media_order: cat.jpeg
published: true
allowCSS: default
allowJS: default
visible: true
content:
    items: '@self.children'
    order:
        by: manual
        dir: asc
        custom:
            - home
            - features
            - about
---
```
But no luck. Any thoughts on how this can be fixed?

**Ideal solution**

It would be great if ordering was as simple as mentioning it in the front matter:

```
---
title: Home
media_order: cat.jpeg
published: true
allowCSS: default
allowJS: default
visible: true
order_number: 1 <--- specify order # here instead of "01.home" folder prefix
---
```
