### ISSUE TITLE
Module collections with specific modules

### ISSUE THREAD

**Issue by maliyshock** [getgrav/grav#2409]
Is it possible to create multiple collection of the same page, but with indication of specific modules?

for example https://monosnap.com/file/bltdtr1GDlSwnnsK55SjtELKnrulo2
collection of green stroke modules and collection of red stroke modules.
From the documentation, I know that I can create the collection of all child modules of the page. 
But what if I have the complex layout with the sidebar and some sections which follows like that https://monosnap.com/file/Qy5Tl8EwKT20pfRSjKRrwB3cLqLDv4

Right now if I need to create multiple collections of the same page I have to create modules and child pages to make the separation. But what if I need more separation in the future? 3 or even 4 separate collections of modules of the same page. Do I need to use taxonomies collection instead of modules colelction?

I thought taxonomies should be used as content categories, but not for page modules separation.

**Comment by rhukster** [comment]
It is possible to create multiple collections and explicitly list the modules using the `custom` order type: https://learn.getgrav.org/15/content/collections

**Comment by maliyshock** [comment]
Well, the problem is not the order. The problem is that I am not available to do that

```
main:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _intro
            - _blockquote_1
            - _blockquote_2
sidebar: true
other:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _events
            - _anouncements
```

Because the `items: @self.modular` going to pick up **all** modules of the current page.
It does not matter are they exist in order option or not. 
So both of those collections `other` and `main` going to have the same number of modules
- _intro
- _blockquote_1
- _blockquote_2
- _events
- _anouncements

I would like to have some of them inside of `other` collection and some of them inside of `main` collection. I also would like to create additional modular collections in the future.

The only way to make that kind of the separation, that I can see right now is to make some of the modules as child pages.
So I can say :
```            
main:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _intro
            - _blockquote_1
            - _blockquote_2
sidebar: true
other:
    items: '@self.children'
    order:
        by: default
        dir: asc
        custom:
            - events
            - anouncements
```

where `items: '@self.modular'` going to pick up all modules into collection and `items: '@self.children'` going to pick up all not modular child pages. So I can keep them separate.

But it looks like a hack, not the option.

So my question is: is there any possibility to create multiple collections of specific modules by grav?
