### ISSUE TITLE
Flex users - problem with authorization

### ISSUE THREAD

**Issue by lufog** [getgrav/grav#2444]
If you register a new flex user, and try to log in. You get an error "Login failed...".
This happens both when the user is registered from the site, and when the first user is created from the admin plugin.

```yaml
# system.yaml
...
accounts:
  type: flex
  storage: file
...
```

Access rights are correct:
```yaml
# {profile_hash}.yaml
...
access:
  site:
    login: 'true'
...
```
or
```yaml
# {profile_hash}.yaml
...
groups:
  - user
...
```

```yaml
# groups.yaml
...
user:
  groupname: user
  readableName: User
  access:
    site:
      login: true
...
```
If you regenerate an account index file, old accounts also stop logging in.
