### ISSUE TITLE
recaptcha not working in forms

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2455]
Hello all
i have form in standart Grav fields
```
---
title: 'Сайты под ключ в Краснодаре'
action: '@self'
cache_enable: false
form:
    name: my-nice-form
    fields:
        -
            name: name
            placeholder: 'Имя'
            autocomplete: 'on'
            type: text
            classes: 'form-control inp'
            validate:
                required: true
        -
            name: email
            placeholder: 'Email'
            type: text
            classes: 'form-control inp'
            validate:
                rule: email
                required: true
        -        
           name: g-recaptcha-response
           label: Captcha
           type: captcha
           recaptcha_site_key: ////////
           recaptcha_not_validated: 'Captcha not valid!'
           validate:
                required: true
    buttons:
        -
            type: submit
            value: Рассчитать
            classes: 'btn danger-color w100'
    process:
        -
            email:
                from: '{{ form.value.email|e }}'
                to: '{{ config.plugins.email.to }}'
                subject: 'Contact by {{ form.value.name|e }}'
                body: "{% include 'forms/data.html.twig' %}"
        - 
           captcha:
                recaptcha_secret: ///////
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
---
```
but this not work
e-mail's sent without captcha validation
whats wrong?
sorry me english bad...)))
