### ISSUE TITLE
Sorting not working for modules (modular page) - Grav default theme

### ISSUE THREAD

**Issue by nicolasp9-dev** [getgrav/grav#2478]
Hi,

I have a modular page and some submodules of different kinds with numeric prefix enabled on every modules. (01._phase1, 02._adapted-services, 03._android-things, 04._control-interfaces, 05._custom-build, 06._deployment...)

When I sort modules with the following configuration in the parent page:
```
content:
    items: '@self.modular'
    order:
        by: default
body_classes: modular
```
Modules are not displayed in the correct order while loading the page. Sorting by title does not work either. However, modules list is in the correct order on the admin page.

Is it a bug or is there something I missed?

Best regards,
Nicolas
