### ISSUE TITLE
[BUG] @self media image path is not updated when page is ordered

### ISSUE THREAD

**Issue by peca021** [getgrav/grav#2479]
When I change page order (Folder Numeric Prefix is enabled) @self media images path inside the .md file is not updated.

I have a page which name is Jobs and that page has ***05.*** prefix and my .md file for their inner page look like:

```
image:
    user/pages/05.jobs/data-scientist-machine-learning-developer-m-f-d/AczI4qr71un8S5d.svg:
        name: AczI4qr71un8S5d.svg
        type: image/svg+xml
        size: 3449
        path: user/pages/05.jobs/data-scientist-machine-learning-developer-m-f-d/AczI4qr71un8S5d.svg
```

When I move the page and change the order to ***06.jobs*** my path is still looking for the image inside folder ***05.jobs*** and I get error message 404 not found ...

Does anyone know how I can solve this problem? Thanks!
