### ISSUE TITLE
Plugin language interference

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav#248]
Dear Grav Team,

while implementing mult-language features in my plugins, I stumbled over a possible bug concerning language interference of two plugins. Consider for example you have `pluginA` with languages.yaml defined by

```yaml
en:
  PLUGINS:
    PLUGINA:
      TEXT: "Hello plugin A"
```

and another plugin called `pluginB` with languages.yaml defined by

```yaml
en:
  PLUGINS:
    PLUGINB:
      TEXT: "Hello plugin B"
```

Usually I then expect to get

```yaml
en:
  PLUGINS:
    PLUGINA:
      TEXT: "Hello plugin A"
    PLUGINB:
      TEXT: "Hello plugin B"
```

but instead, depending which plugin loads last, one gets one of the two first configurations (inspected by dumping `$grav['config']` to print out the available language entries). It seems like the join in https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Config/Config.php#L375  is the problem, which does effectively an `array_merge`. Instead an `array_merge_recursive` is necessary here.

**Comment by rhukster** [comment]
Have you been able to get a fix working?

**Comment by rhukster** [comment]
Actually, i did fix a bug in 0.9.34 that was causing each plugin language to override each other.  Are you sure you on the latest version???

**Comment by mahagr** [comment]
Configuration merging is really meant for configurations, not for language files. In language files we probably want to have a bit different logic.

**Comment by Sommerregen** [comment]
@rhukster Not yet. I discovered this bug yesterday and was browsing through the code to find the hook, where `languages.yaml` are passed in. And yes I have **Grav 0.9.34**. I will working on a fix and provide the solution here, when done.

**Comment by rhukster** [comment]
Well that's really weird because I came across this when adding mulitlang support to admin plugin.  Basically the logic was whacked and it was constantly overwriting each plugin's language settings.  But pretty sure I fixed this issue.  I have multiple plugins installed and they have merged the languages correctly.

In fact I just tested this by creating a few languages.yaml files in a couple of plugins with some test data in each.  they are all merged correctly into `/cache/compiled/languages/master-localhost.php` correctly.  i can see the array for `en` containing all the correct strings I spread out throughout the plugins.

**Comment by rhukster** [comment]
Oh you know what! I thin i know your problem. its the levels of namespacing your doing.  Rather than doing this:

```
en:
  PLUGINS:
    PLUGINA:
      TEXT: "Hello plugin A"
```

do:

```
en:
  PLUGINS.PLUGINA.TEXT: "Hello plugin A"
```

This will ensure that it's just a string lookup and not a multilevel array that will undoubtedly have deep merging issues.

This may not be the best long-term solution, but for now it's a solid workaround

**Comment by rhukster** [comment]
for what its worth my solution has to be to name things with underscores:

```
en:
  ADMIN_BETA_MSG: This is a Beta release! Use this in production at your own risk...
  ADMIN_REPORT_ISSUE: Found an issue? Please report it on GitHub.
  EMAIL_FOOTER: <a href="http://getgrav.org">Powered by Grav</a> - The Modern Flat File CMS
  LOGIN_BTN: Login
  LOGIN_BTN_FORGOT: Forgot
  LOGIN_BTN_RESET: Reset Password
  LOGIN_BTN_SEND_INSTRUCTIONS: Send Reset Instructions
  LOGIN_LOGGED_IN: You have been successfully logged in
  LOGIN_FAILED: Login failed
  LOGGED_OUT: You have been logged out
  RESET_LINK_EXPIRED: Reset link has expired, please try again
  RESET_PASSWORD_RESET: Password has been reset
  RESET_INVALID_LINK: Invalid reset link used, please try again
  FORGOT_INSTRUCTIONS_SENT_VIA_EMAIL: Instructions to reset your password have been sent via email to %s
  FORGOT_FAILED_TO_EMAIL: Failed to email instructions, please try again later
  FORGOT_CANNOT_RESET_EMAIL_NO_EMAIL: Cannot reset password for %s, no email address is set
  FORGOT_USERNAME_DOES_NOT_EXIST: User with username <b>%s</b> does not exist
  FORGOT_EMAIL_NOT_CONFIGURED: Cannot reset password. This site is not configured to send emails
  FORGOT_EMAIL_SUBJECT: %s Password Reset Request
  FORGOT_EMAIL_BODY: <h1>Password Reset</h1><p>Dear %1$s,</p><p>A request was made on <b>%4$s</b> to reset your password.</p><p><br /><a href="%2$s" class="btn-primary">Click this to reset your password</a><br /><br /></p><p>Alternatively, copy the following URL into your browser's address bar:</p> <p>%2$s</p><p><br />Kind regards,<br /><br />%3$s</p>
```
