### ISSUE TITLE
Secondary user://config-bis/ directory

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav#2488]
I started using the great `git-sync` plugin but I found that some configuration directive would be better off the repository. The fact that configuration is automatically merged from the various sources is appreciable. But the default scheme configuration is not sufficient:
https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Config/Setup.php#L65
```php
        'config' => [
            'type' => 'ReadOnlyStream',
            'prefixes' => [
                '' => ['environment://config', 'user://config', 'system/config'],
            ]
```

Here `environment://config` is for `<domain-specific>/config/`.
But I'd like to add a secondary (actually fourth) configuration source in `user://private-config`.
This directory would be `.gitignore`d and contains the sensitive part of the configuration.

In order to do this I'm planning to add this to my `/user/config/streams.yaml`:
```yaml
schemes:
  config:
    type: ReadOnlyStream
    paths:
      - environment://config
      - user://config
      - system/config
      - user://private-config   # <-- added
```

Is there any drawbacks/problems to anticipate?
Does it seem a valid use-case for stream modification?
