### ISSUE TITLE
Unable to use Cyrillic in title

### ISSUE THREAD

**Issue by arkanos** [getgrav/grav#2501]
Hi guys,

I'm having issues trying to use any character that is not in the standard A-Z in the titles.

We are using Grav 1.6.8

I have checked the system/blueprints/default.yaml and I have included this regexp:

```
rules:
  slug:
    pattern: '[a-zA-Z0-9_\-]+'
    min: 1
    max: 200
  title:
    pattern: '[A-Za-zА-Яа-я0-9 \-_\?\¿\!\¡\"\']+'
    min: 1
    max: 200
```

I am using the second one line this:

```
header.title:
              type: text
              autofocus: true
              style: vertical
              label: PLUGIN_ADMIN.TITLE
              validate:
                rule: title
```

However, I'm still getting the error message that only numbers and letters can be used.

Any help would be very much appreciated.

**Comment by mahagr** [comment]
Try this:
https://stackoverflow.com/questions/23314171/how-to-use-regex-in-html5-attribute-for-cyrillic-letters

**Comment by arkanos** [comment]
I have solved the issue adding the following to 'user/themes/quark/blueprints/article.yaml':

```
title: Article
rules:
  title:
    pattern: "[ A-Za-z0-9\-_\?\¿\!\¡\"\'.\p{Common}\p{Cyrillic}]+"
    min: 2
    max: 255
```
Also I added it into the folder.yaml.

Regarding your answer @mahagr, if using the Unicode character range, a preg_match() error will be thrown if the unicode flag is not used. It needs to be used carefully.
