### ISSUE TITLE
GPM errors from blueprints are not logged

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#2505]
An error popped up because of a forgotten reference to a class in a method, but that error never made its way to logs/grav.log or the console. This was only visible in Admin, because the method is called statically by a blueprint.

The error is present in v1.7.1-beta.1 of the Presentation-plugin, when [blueprint.yaml](https://github.com/OleVik/grav-plugin-presentation/blob/v1.7.1-beta.1/blueprints.yaml#L42) calls the [getRevealThemes()](https://github.com/OleVik/grav-plugin-presentation/blob/v1.7.1-beta.1/presentation.php#L435-L448)-method. That is, it tries to [include_once Utilities.php](https://github.com/OleVik/grav-plugin-presentation/blob/v1.7.1-beta.1/presentation.php#L439), which at this point has been moved into /classes. The error is a normal `PHP Fatal error:  Uncaught Error: Class 'Grav\Plugin\PresentationPlugin\Utilities' not found in C:\Users\Ole\GitHub\grav-plugin-presentation\presentation.php`, revealed by running `php bin/gpm index`.

## Replication

Environment:
- Core v1.6.9
- Admin v1.9.4
- Email  v3.0.2
- Error  v1.6.2
- Form  v3.0.3
- Login  v3.0.2
- Markdown Notices  v1.0.1
- Presentation v1.7.1-beta.1
- Presentation Deckset v1.2.0
- Problems  v2.0.3
- Shortcode Core  v4.1.1

System.yaml:

```yaml
absolute_urls: false

home:
  alias: '/home'

pages:
  theme: quark
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: true
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true
```

1. Install environment
2. Visit /admin/plugins
3. Observe that no plugin-information loads, and no errors are logged to console or grav.log

For an easy diff between the working version of the plugin, and the broke version, consider: https://github.com/OleVik/grav-plugin-presentation/compare/v1.7.0-beta.1...v1.7.1-beta.1

The problem was [resolved in v1.7.1-beta.4](https://github.com/OleVik/grav-plugin-presentation/blob/v1.7.1-beta.4/presentation.php#L425) of the plugin, but the error should still persist in Admin.
