### ISSUE TITLE
Image markdown not working in custom field

### ISSUE THREAD

**Issue by educedesign** [getgrav/grav#2519]
Hi,

I have an issue displaying an image through a custom field. I am using the following markdown in a custom field of a modular page and it shows up as a broken link on my website:

`[![Alt Text](UseCase1.png)](http://www.google.ca?target=_blank)`

Using the browser's inspect mode I can see that it tries to fetch the image from the root directory, i.e. _localhost/cytapex/UseCase1.png_.

However, when I am using the same code in the pages default content field, Grav looks into the page folder where the image is located and as a result, displays is without an issue. Do I need to specify anything in my page blueprint for the custom field to look into the page folder for media instead of the root? Code for the page blueprint is below.

```
title: Use Cases #Create new tab blueprint called Use Cases
'@extends':
  type: default #it extends the default blueprint

form:
  fields:
    tabs:
      type: tabs #Type is a tab
      active: 1

      fields:
        gallery:
          type: tab
          title: Use Cases #Set the title of the tab to 'Use Cases'

          fields:
            header.usecases:
              type: list #Create a list
              label: Case Study #called 'Use Case'
              fields: #declare the fields for each list item
                .title: #name
                  type: text #is of the type text
                  label: Case Study Title #called 'Use Case Title'
                .intro: #description
                  type: editor #textarea is a text editor
                  label: Case Study Introduction (~65 words) #called 'Use Case Introduction'
                .desc:
                  type: editor #this is a text editor
                  label: Case Study Description #called 'Use Case Description'
                .featured: #images
                  type: filepicker #allows you to select a file
                  folder: 'self@'
                  label: Select a feature image
                  preview_images: true
                  accept:
                    - .png
                    - .jpg
                    - .jpeg
```

And finally I am using `{{ usecase.desc|markdown }}` in my front matter to display the content of the custom field.
