### ISSUE TITLE
Resetting a user's password clears the user's site access

### ISSUE THREAD

**Issue by emielmolenaar** [getgrav/grav#2528]
I am using Grav 1.6.9 and I have created a new user. The user has access to:

```
access:
  site:
    login: 'true'
  admin:
    super: 'true'
    login: 'true'
```

I can login with that user. When I reset the password of the user via the password-reset form, the access configuration (as shown above) disappears from the users YAML file; preventing the user from logging in.

I have been searching the internet for similar cases but I can not find anything regarding this issue. Is this a bug or am I doing something wrong?
