### ISSUE TITLE
How to save form data between pages

### ISSUE THREAD

**Issue by drnasin** [getgrav/grav#2530]
Hi, this is not a bug report "per se" but more of a question. I have an order process where I have to save the form data between pages (steps). What is the best way to do that in grav? Sesssions? js + cookies? thank you!

**Comment by rhukster** [comment]
Frankly, the best way to approach this is to have a single form, and use JS/CSS to switch between sections of the form as if it was multiple steps.  We have done this before using Fieldsets to arrange the form into sections we can then work with. An example:

```yaml
form:
    name: newbuild
    client_side_validation: true
    keep_alive: true
    clear_redirect_url: '/dashboard'

    fields:
        step_1:
            type: fieldset
            id: build_step_1
            classes: active
            legend: 'What do you drive?'
            fields:
                year:
                    type: selectize
                    label: 'Year'
                    data-options@: 'Grav\Plugin\CustomPlugin::getBuildsYears'
                    validate:
                        required: true
                        message: 'This field cannot be blank'
                make:
                    type: modeltrim_selectize
                    label: 'Make'
                    validate:
                        required: true
                        message: 'This field cannot be blank'
                model:
                    type: modeltrim_selectize
                    label: 'Model'
                    validate:
                        required: true
                        message: 'This field cannot be blank'
                trim:
                    type: modeltrim_selectize
                    label: 'Trim'
                    options:
                        '': Trim (optional)
        step_2:
            type: fieldset
            id: build_step_2
            classes: partial-requirement
            legend: 'What mods have you done?'
            fields:
                engine:
                    type: tags
                    label: Engine
                    placeholder: 'ex: Superchips Programmer'
                    validate:
                        type: commalist
                intake:
                    type: tags
                    label: Intake
                    placeholder: 'ex: Airaid Cold Air intake'
                    validate:
                        type: commalist
```
