### ISSUE TITLE
registration - not work

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2535]
Hi
I write username as 'abc123' - not validate,
write abC-123_abc - not validete
delete username_regex from admin - error 'Username does not pass the minimum requirements'
register admin grav - ok
my form standart
```
---
login_redirect_here: false

form:

  fields:
    Name:
      type: text
      label: Имя
      validate:
        required: true
        message: PLUGIN_LOGIN.USERNAME_NOT_VALID
        config-pattern@: system.username_regex

    email:
      type: email
      validate:
        required: true
        message: PLUGIN_LOGIN.EMAIL_VALIDATION_MESSAGE

    password1:
      type: password
      label: Пароль
      validate:
        required: true
        message: PLUGIN_LOGIN.PASSWORD_VALIDATION_MESSAGE
        config-pattern@: system.pwd_regex

    password2:
      type: password
      label: Пароль еще раз
      validate:
        required: true
        message: PLUGIN_LOGIN.PASSWORD_VALIDATION_MESSAGE
        config-pattern@: system.pwd_regex

  buttons:
      -
          type: submit
          value: Регистрация
          classes: dob
  process:
      register_user: true
      message: "Спасибо за регистрацию..."
      reset: true
---

# Регистрация
```
whats wrong?

delete validation on form - error
how set simple username - abc123 and other?
