### ISSUE TITLE
page.collection not returning any data

### ISSUE THREAD

**Issue by thejame** [getgrav/grav#2576]
Try as I may, I cannot populate a collection with this page. Note that the page does not have any children (it's pulling the collection from another pages), and if I explicitly define the collection's content in the template it will bring back the data, but I need to fill the collection dynamically as I have several pages.

template (templates/podcast.html.twig):
```
{% set podcast_collection = page.collection %}
{{ podcast_collection.count }} <!-- this is zero -->
{% for podcast_item in podcast_collection %}
  {{ podcast_item.title }} <!-- this never shows -->
{% endfor %}
...
```
page (pages/podcasts/podcast-a/podcast.md):
```
---
title: Podcast A
content:
  items: '@page:/sermons'
  order:
    by: date
    dir: desc
  limit: 100
---
```

Thanks!
