### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by imsheng** [getgrav/grav#2597]
![微信截图_20190720134448](https://user-images.githubusercontent.com/10435075/61574610-9e888500-aaf4-11e9-8e27-86196fe384a1.png)

**Comment by rhukster** [comment]
Hmmm i have no idea how you are getting a reference to `www.chat.getgrav.org`

Overall, "A" rating with no issues: https://www.ssllabs.com/ssltest/analyze.html?d=getgrav.org&hideResults=on

Plus, never seen anyone else having this issue, makes me think its something on your end. Try tweaking some of the GPM options in config to see if that helps: https://learn.getgrav.org/16/basics/grav-configuration#gpm

**Comment by imsheng** [comment]
@rhukster  Just download and install it on my hosting.
https://getgrav.org/downloads

**Comment by imsheng** [comment]
It won't work.

```
gpm:
  releases: stable
  proxy_url:
  method: 'auto'
  verify_peer: false
  official_gpm_only: true
```

```
gpm:
  releases: stable
  proxy_url:
  method: 'auto'
  verify_peer: false
  official_gpm_only: false
```
