### ISSUE TITLE
$validate['type'] undefined. Easy fix!

### ISSUE THREAD

**Issue by eulores** [getgrav/grav#2610]
There is a bug in the file `grav/system/src/Grav/Common/Data/Validation.php` where `$validate` is used before being defined.
See (and **swap!**) lines 30 and 31.
```php
30     $type = $validate['type'] ?? $field['type'];
31     $validate = (array)($field['validate'] ?? null);
```
As an example, the blueprint `blog.yaml` from the quark theme will try to validate the field `header.content.limit` as `type: text` instead of `type: int`
```yaml
            header.content.limit:
              type: text
              label: Max Item Count
              default: 5
              validate:
                required: true
                type: int
                min: 1
```
