### ISSUE TITLE
set blog page

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2626]
Hi
I use standart theme
set blog 
```
title: blog
content:
    items:
        - '@self.children'
    limit: 10
    order:
        by: date
        dir: desc
    pagination: true
```
blog page set to
```
title: ' CSS-in-JS'
taxonomy:
    category:
        - css
        - js
```
why taxonomy in blog page list a njt display
and in blog item - dont display date, taxonomy , page title
use clean theme, whats wrong?
