### ISSUE TITLE
[Bug] Unpublished blog posts are still displayed on the front-end

### ISSUE THREAD

**Issue by paulaime** [getgrav/grav#2650]
Since last Grav update (v1.7.0-beta.5), on [one of my Grav websites](https://iampox.com/blog) that's using the [Mediator theme](https://github.com/getgrav/grav-theme-mediator) (customized by me), all the unpublished blog posts are still displayed on the front-end.

The header of a blog post is as follows:

```
---
title: 'Title of the blog post'
media_order: background.jpg
published: false
image: background.jpg
---
```

And the header of the parent file (default.md) is as follows:

```
---
title: 'Title of the website'
external_links:
    process: true
    title: false
    no_follow: true
    target: _blank
    mode: active
sitemap:
    changefreq: monthly
    priority: 1.03
content:
    items: '@self.children'
    order:
        by: date
        dir: desc
    limit: 4
    pagination: true
feed:
    description: 'Sample blog description'
    limit: 10
pagination: true
cover: shore.jpg
---
```

But the blog posts are shown on the website even if they're set on `published: false`.

I talked with Ricardo on Discord, and was told to add `filter: published: true` in the `content` for the moment for a quick fix, but I wanted to post this bug here because it might be an issue with Grav.
