### ISSUE TITLE
HTML in Frontmatter or form label?

### ISSUE THREAD

**Issue by noelacosta** [getgrav/grav#2655]
Not sure if this is the correct place to post this (or is this about grav-form) but I don't know how to make clickable links in form element text. Here's a sample:

```
        -
            name: press_info
            type: radio
            label: 'Would you prefer to receive press information links via email? [Sample link](http://sho-rten.com/coahs1)'
            validate:
                required: true
            options:
                'yes': 'Yes'
                'no': 'No'
```
It only renders as plain text (as typed) in Frontmatter or the actual page. Thank you.
