### ISSUE TITLE
Double taxonomy value

### ISSUE THREAD

**Issue by Memurame** [getgrav/grav#2671]
I have add taxonomy to my page blueprint. it works fine. 
When i save first time the value show like this....
<img width="261" alt="Bildschirmfoto 2019-09-20 um 17 01 40" src="https://user-images.githubusercontent.com/15847494/65337717-03ca2680-dbc9-11e9-9128-b89a2a219a33.png">

However, if I save a second time, the values are double...
<img width="208" alt="Bildschirmfoto 2019-09-20 um 17 02 05" src="https://user-images.githubusercontent.com/15847494/65337794-28260300-dbc9-11e9-9ed6-5b6243cb3a74.png">

My blueprint:
```
header.taxonomy:
  type: taxonomy
  label: PLUGIN_ADMIN.TAXONOMY
  multiple: true
  default:
    category: ['blog']
  validate:
    type: commalist
```
What am I doing wrong and why does it store the values twice?
i have tried with commalist and array.
