### ISSUE TITLE
Feature Request: Interpolated YAML Variables

### ISSUE THREAD

**Issue by DaveJarvis** [getgrav/grav#2672]
# Overview

I'd like to associate a YAML file with one or more Markdown documents such that before a Markdown document is converted to HTML, its variable references are first replaced with the definitions from the YAML file.

# Interpolated Strings

For the interpolated string values, please see:

* https://github.com/jgm/pandoc/issues/1950#issuecomment-524521696
* https://dave.autonoma.ca/blog/2019/07/06/typesetting-markdown-part-5/#yaml-and-markdown-separation
* https://bitbucket.org/djarvis/yamlp/src/master/src/main/java/com/whitemagicsoftware/yamlp/parser/YamlParser.java#lines-242 (sample algorithm)

# Examples

Consider the following files:

* /user/pages/01.blog/01.typesetting-markdown/definitions.yaml
* /user/pages/01.blog/01.typesetting-markdown/item.md

In **/user/pages/01.blog/01.typesetting-markdown/definitions.yaml**:

``` yaml
author:
  name:
    first: Jane
    last: Doe
    full: $author.name.first$ $author.name.last$
```

In **/user/pages/01.blog/01.typesetting-markdown/item.md**:

``` md
You've reached the blog of $author.name.full$! But, please, call me $author.name.first$.
```

Produces:

``` html
<p>
You've reached the blog of Jane Doe! But, please, call me Jane.
</p>
```

This could also allow for globally defined page references as well:

``` md
[link]($site.blog.home$/$site.main.filename$.md)
```

Where:

``` yaml
site:
  blog:
    home: /blog
  main:
    filename: item
```
