### ISSUE TITLE
Permission based fields data is reset on save

### ISSUE THREAD

**Issue by alljamin** [getgrav/grav#2747]
I have two users one super-admin and another admin with access to pages.

Super-admin yaml:
```yaml
...
access:
  admin:
    login: true
    super: true
  site:
    login: true
...
```

Admin yaml:
```yaml
...
access:
  admin:
    login: true
    pages: true
  site:
    login: true
...
```
In my custom theme I have specified to which tabs each user has access to:

```yaml
...
fields:
        advanced:
          security:
            - admin.super

        options:
          security:
            - admin.super

        content:
          security:
            - admin.super
        
        homepage:
          type: tab
          title: Homepage
          fields:
            header.field1: ...
            header.field2: ...
            header.field3: ...
...
```
If I login as super admin and add, for example, metadata in the options tab, save it, it will show correctly in the front end. If I now log out and login as admin go to the page and click save it will flush all the data. This ultimately means that I cannot set permissions on tabs because no matter the permission level the data will be reset.

Any idea why is this happening?

Originally posted on [Grav Discourse](https://discourse.getgrav.org/t/permission-based-fields-data-is-reset-on-save/10529).
