### ISSUE TITLE
Blueprint markdown editor is not displayed on server but locally

### ISSUE THREAD

**Issue by liebig** [getgrav/grav#2752]
I have a very strange behavior with the following blueprint:

```
title: Article
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.editorlist:
              type: list
              label: Add a column
              btnLabel: Add column
              controls: both
              fields:
                .block:
                  type: Editor
                  label: Column block
            content:
              unset@: true
```
Locally on my WAMP server (PHP 7.2.18) the markdown editor is displayed correctly in the backend under Pages and I can edit the page without problems. Uploaded to my webspace (PHP 7.3.12) the markdown editor is not displayed, only a small text input field is displayed. I tested with the types Editor and markdown but got the same error for both types.

![gravcms markdown editor](https://user-images.githubusercontent.com/3033740/70028897-19cf6c80-15a6-11ea-9f88-7155fa604045.png)
