### ISSUE TITLE
CSS Pipeline Rewrite breaks SVG fills

### ISSUE THREAD

**Issue by AeonSake** [getgrav/grav#2784]
The pipeline option `assets.css_rewrite` breaks URL-encoded IDs of linear gradients defined within the SVG.

SVG structure (example):
```svg
<svg height="200" width="200">
  <defs>
    <linearGradient id="linear-gradient" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="#000" />
      <stop offset="100%" stop-color="#fff" />
    </linearGradient>
  </defs>
  <ellipse cx="100" cy="100" rx="100" ry="100" fill="#ccc" />
</svg>
```

Before pipeline:
```css
svg {
    fill: url(#linear-gradient);
}
```

After pipeline:
```css
svg {
    fill: url(/user/themes/my-theme/css/#linear-gradient);
}
```
