### ISSUE TITLE
Encoding is broken due to "type: file"

### ISSUE THREAD

**Issue by reqweb** [getgrav/grav#2822]
I don't know if this is related to the update. Maybe it was just a coincidence. But after updating the grav, and saving the page that I changed through the **Admin Panel** plugin, I have an incorrect encoding.  
  
Blueprints of this page is custom, I added the necessary fields.
  
I noticed that if remove the "file" field from the drawing, everything works correctly. I did the drawing according to the documentation, and I can't understand what went wrong.
  
Below is the code, removing which everything works correctly.  
  
```
            header.tovarimg:
              type: file
              label: Основное изображение товара
              destination: 'user/images'
              accept:
                - image/*
```
and
```
            header.tovarslider:
              type: file
              label: Слайдер в нижней части страницы
              destination: 'user/images'
              multiple: true
              accept:
                - image/*
```

**Comment by reqweb** [comment]
Here is the entire file  
```
title: PLUGIN_ADMIN.DEFAULT

rules:
  slug:
    pattern: '[a-zA-Zа-яA-Я0-9_\-]+'
    min: 1
    max: 200

form:
  validation: loose

  fields:

    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:
            xss_check:
              type: xss

            header.title:
              type: text
              autofocus: true
              label: Заголовок (название)

            header.tovar1:
              type: text
              label: Кол-во секций, л/мин

            header.tovar2:
              type: array
              label: Характеристики (можно добавлять)
              placeholder_key: Название характеристики
              placeholder_value: Значение характеристики
                  
            header.tovar3:
              type: text
              label: Цена товара

            header.tovar4:
              type: toggle
              toggleable: true
              label: Цена в рублях или евро
              highlight: 1
              default: false
              options:
                1: Это цена в евро
                0: Это цена в рублях
              validate:
              type: bool
              
            header.tovarimg:
              type: file
              label: Основное изображение товара
              destination: 'user/images'
              accept:
                - image/*
                
            header.tovarcontent2:
                label: Варианты настроек
                type: array
                value_only: true
                size: large
                
            header.tovarcontent:
                label: Описание товара (текстовый блок)
                type: markdown
                validate:
                  type: textarea
                  
            header.tovarslider:
              type: file
              label: Слайдер в нижней части страницы
              destination: 'user/images'
              multiple: true
              accept:
                - image/*

            header.partblock:
              type: toggle
              toggleable: true
              label: Показывать блок "партнёры" внизу?
              highlight: 1
              default: true
              options:
                1: Показывать
                0: Не показывать
              validate:
              type: bool
                
        options:
          type: tab
          title: PLUGIN_ADMIN.OPTIONS

          fields:

            publishing:
              type: section
              title: PLUGIN_ADMIN.PUBLISHING
              underline: true
              
              fields:
                header.descr:
                  type: text
                  label: Description

                header.published:
                  type: toggle
                  toggleable: true
                  label: PLUGIN_ADMIN.PUBLISHED
                  help: PLUGIN_ADMIN.PUBLISHED_HELP
                  highlight: 1
                  size: medium
                  options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                  validate:
                    type: bool

                header.date:
                  type: datetime
                  label: PLUGIN_ADMIN.DATE
                  toggleable: true
                  help: PLUGIN_ADMIN.DATE_HELP

                header.publish_date:
                  type: datetime
                  label: PLUGIN_ADMIN.PUBLISHED_DATE
                  toggleable: true
                  help: PLUGIN_ADMIN.PUBLISHED_DATE_HELP

                header.unpublish_date:
                  type: datetime
                  label: PLUGIN_ADMIN.UNPUBLISHED_DATE
                  toggleable: true
                  help: PLUGIN_ADMIN.UNPUBLISHED_DATE_HELP

                header.metadata:
                  toggleable: true
                  type: array
                  label: PLUGIN_ADMIN.METADATA
                  help: PLUGIN_ADMIN.METADATA_HELP
                  placeholder_key: PLUGIN_ADMIN.METADATA_KEY
                  placeholder_value: PLUGIN_ADMIN.METADATA_VALUE

            taxonomies:
              type: section
              title: PLUGIN_ADMIN.TAXONOMIES
              underline: true

              fields:
                header.taxonomy:
                  type: taxonomy
                  label: PLUGIN_ADMIN.TAXONOMY
                  multiple: true
                  validate:
                    type: array

        advanced:
          type: tab
          title: PLUGIN_ADMIN.ADVANCED

          fields:
            columns:
              type: columns
              fields:
                column1:
                  type: column
                  fields:

                    settings:
                      type: section
                      title: PLUGIN_ADMIN.SETTINGS
                      underline: true

                    folder:
                      type: text
                      label: PLUGIN_ADMIN.FOLDER_NAME
                      validate:
                        rule: slug

                    route:
                      type: parents
                      label: PLUGIN_ADMIN.PARENT
                      classes: fancy

                    name:
                      type: select
                      classes: fancy
                      label: PLUGIN_ADMIN.PAGE_FILE
                      help: PLUGIN_ADMIN.PAGE_FILE_HELP
                      default: default
                      data-options@: '\Grav\Common\Page\Pages::pageTypes'

                    header.body_classes:
                      type: text
                      label: PLUGIN_ADMIN.BODY_CLASSES


                column2:
                  type: column

                  fields:
                    order_title:
                      type: section
                      title: PLUGIN_ADMIN.ORDERING
                      underline: true

                    ordering:
                      type: toggle
                      label: PLUGIN_ADMIN.FOLDER_NUMERIC_PREFIX
                      help: PLUGIN_ADMIN.FOLDER_NUMERIC_PREFIX_HELP
                      highlight: 1
                      options:
                        1: PLUGIN_ADMIN.ENABLED
                        0: PLUGIN_ADMIN.DISABLED
                      validate:
                        type: bool

                    order:
                      type: order
                      label: PLUGIN_ADMIN.SORTABLE_PAGES
                      sitemap:

            overrides:
              type: section
              title: PLUGIN_ADMIN.OVERRIDES
              underline: true

              fields:

                header.dateformat:
                  toggleable: true
                  type: select
                  size: medium
                  selectize:
                    create: true
                  label: PLUGIN_ADMIN.DEFAULT_DATE_FORMAT
                  help: PLUGIN_ADMIN.DEFAULT_DATE_FORMAT_HELP
                  placeholder: PLUGIN_ADMIN.DEFAULT_DATE_FORMAT_PLACEHOLDER
                  data-options@: '\Grav\Common\Utils::dateFormats'
                  validate:
                    type: string

                header.menu:
                  type: text
                  label: PLUGIN_ADMIN.MENU
                  toggleable: true
                  help: PLUGIN_ADMIN.MENU_HELP

                header.slug:
                  type: text
                  label: PLUGIN_ADMIN.SLUG
                  toggleable: true
                  help: PLUGIN_ADMIN.SLUG_HELP
                  validate:
                    message: PLUGIN_ADMIN.SLUG_VALIDATE_MESSAGE
                    rule: slug

                header.redirect:
                  type: text
                  label: PLUGIN_ADMIN.REDIRECT
                  toggleable: true
                  help: PLUGIN_ADMIN.REDIRECT_HELP

                header.process:
                  type: checkboxes
                  label: PLUGIN_ADMIN.PROCESS
                  toggleable: true
                  config-default@: system.pages.process
                  default:
                    markdown: true
                    twig: false
                  options:
                    markdown: Markdown
                    twig: Twig
                  use: keys

                header.twig_first:
                  type: toggle
                  toggleable: true
                  label: PLUGIN_ADMIN.TWIG_FIRST
                  help: PLUGIN_ADMIN.TWIG_FIRST_HELP
                  highlight: 0
                  options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                  validate:
                    type: bool

                header.never_cache_twig:
                  type: toggle
                  toggleable: true
                  label: PLUGIN_ADMIN.NEVER_CACHE_TWIG
                  help: PLUGIN_ADMIN.NEVER_CACHE_TWIG_HELP
                  highlight: 0
                  options:
                    1: PLUGIN_ADMIN.YES
                    0: PLUGIN_ADMIN.NO
                  validate:
                    type: bool

                header.child_type:
                  type: select
                  toggleable: true
                  label: PLUGIN_ADMIN.DEFAULT_CHILD_TYPE
                  default: default
                  placeholder: PLUGIN_ADMIN.USE_GLOBAL
                  data-options@: '\Grav\Common\Page\Pages::types'

                header.routable:
                  type: toggle
                  toggleable: true
                  label: PLUGIN_ADMIN.ROUTABLE
                  help: PLUGIN_ADMIN.ROUTABLE_HELP
                  highlight: 1
                  options:
                    1: PLUGIN_ADMIN.ENABLED
                    0: PLUGIN_ADMIN.DISABLED
                  validate:
                    type: bool

                header.cache_enable:
                  type: toggle
                  toggleable: true
                  label: PLUGIN_ADMIN.CACHING
                  highlight: 1
                  options:
                    1: PLUGIN_ADMIN.ENABLED
                    0: PLUGIN_ADMIN.DISABLED
                  validate:
                    type: bool

                header.visible:
                  type: toggle
                  toggleable: true
                  label: PLUGIN_ADMIN.VISIBLE
                  help: PLUGIN_ADMIN.VISIBLE_HELP
                  highlight: 1
                  default: false
                  options:
                    1: PLUGIN_ADMIN.ENABLED
                    0: PLUGIN_ADMIN.DISABLED
                  validate:
                    type: bool

                header.debugger:
                  type: toggle
                  toggleable: true
                  label: PLUGIN_ADMIN.DEBUGGER
                  help: PLUGIN_ADMIN.DEBUGGER_HELP
                  highlight: 1
                  options:
                    1: PLUGIN_ADMIN.ENABLED
                    0: PLUGIN_ADMIN.DISABLED
                  validate:
                    type: bool

                header.template:
                  type: text
                  toggleable: true
                  label: PLUGIN_ADMIN.DISPLAY_TEMPLATE

                header.append_url_extension:
                  type: text
                  label: PLUGIN_ADMIN.APPEND_URL_EXT
                  toggleable: true
                  help: PLUGIN_ADMIN.APPEND_URL_EXT_HELP

            routes_only:
              type: section
              title: PLUGIN_ADMIN.ROUTE_OVERRIDES
              underline: true

              fields:

                header.routes.default:
                  type: text
                  toggleable: true
                  label: PLUGIN_ADMIN.ROUTE_DEFAULT

                header.routes.canonical:
                  type: text
                  toggleable: true
                  label: PLUGIN_ADMIN.ROUTE_CANONICAL

                header.routes.aliases:
                  type: array
                  toggleable: true
                  value_only: true
                  size: large
                  label: PLUGIN_ADMIN.ROUTE_ALIASES


            admin_only:
              type: section
              title: PLUGIN_ADMIN.ADMIN_SPECIFIC_OVERRIDES
              underline: true

              fields:

                header.admin.children_display_order:
                  type: select
                  label: PLUGIN_ADMIN.ADMIN_CHILDREN_DISPLAY_ORDER
                  help: PLUGIN_ADMIN.ADMIN_CHILDREN_DISPLAY_ORDER_HELP
                  toggleable: true
                  classes: fancy
                  default: 'collection'
                  options:
                    'default': 'Ordered by Folder name (default)'
                    'collection': 'Ordered by Collection definition'


                header.order_by:
                  type: hidden

                header.order_manual:
                  type: hidden
                  validate:
                    type: commalist

                blueprint:
                  type: blueprint
```

**Comment by rhukster** [comment]
that's an odd one!

**Comment by reqweb** [comment]
If save the page using Expert mode in the Admin panel, the page is saved good, no errors.   
  
I could assume something with the hosting setup, but only this template behaves like this, with this blueprint.

**Comment by mahagr** [comment]
There were some encoding changes in Grav to fix non-UTF8 characters if server configuration was not using UTF8. Can you show me what exactly broke and how when you saved the page?

**Comment by reqweb** [comment]
before `ctrl+s`
```
Страница тест
```
I click `ctrl+s` and...
```
Ð¡ÑÑÐ°Ð½Ð¸ÑÐ° ÑÐµÑÑ
```

**Comment by reqweb** [comment]
server ( **locale** )
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```

**Comment by mahagr** [comment]
So it only happens if you have file fields? Do you need to add a file?

**Comment by reqweb** [comment]
Yes, I wrote above

**Comment by reqweb** [comment]
I made two fields for files, I need them. If you remove them, everything works. But I need them, especially since it worked before.

**Comment by reqweb** [comment]
Sorry for the bad English, I use a translator

**Comment by reqweb** [comment]
Yes, so only with a drawing that has a custom field for the file
Standard for GRAV pagemedia does not break the encoding
If you save it via ftp, the encoding doesn't break either
If you save it in "expert" mode, everything is fine too
Only the "normal" admin mode breaks the encoding when saving

**Comment by reqweb** [comment]
Configured on the server **locale**
But the problem persisted
```
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=ru_RU.UTF-8
```

**Comment by mahagr** [comment]
I'm not able to reproduce this one, unfortunately.

**Comment by mahagr** [comment]
@rhukster Is this one related to the enctype fix you did yesterday?

**Comment by reqweb** [comment]
Please tell me what to configure or update. I'm not so smart that I can decide for myself. At least indicate the direction. After all, if everything works correctly on my other server, then it's the problem server configuration.

**Comment by rhukster** [comment]
Just update the form plugin.

**Comment by reqweb** [comment]
I updated the forms plugin  
I'm creating a page (I didn't change the drawing)
Now the title is in English

![](http://reqweb.net/user/imgforgrav/01.png)

I change it to Russian
i press ctrl+s or save key (top right in admin plugin)

![](http://reqweb.net/user/imgforgrav/02.png)

and...

![](http://reqweb.net/user/imgforgrav/03.png)

**Comment by reqweb** [comment]
I can make a subdomain and copy the site, and pass accesses. I really can't figure out what the problem is. But as usual, it is in something simple and obvious.

**Comment by reqweb** [comment]
Or just pass you the server config

**Comment by rhukster** [comment]
is forms at 4.0.4? if so, then it's another issue.

**Comment by reqweb** [comment]
Yes, is forms at 4.0.4

**Comment by rhukster** [comment]
can you please paste the russian text, so i can copy paste into my site? I can't type russian easily.

**Comment by reqweb** [comment]
Русский текст

**Comment by rhukster** [comment]
I added your file field to a blueprint:

```
header.tovarslider:
              type: file
              label: Слайдер в нижней части страницы
              destination: 'user/images'
              multiple: true
              accept:
                - image/*
```

Then opened that page and saved a text field with your `Русский текст` string and it saved fine. 

![image](https://user-images.githubusercontent.com/1084697/75477795-14da4900-595a-11ea-9ae7-00bcc3b41328.png)

 No weird encoding, so I don't think it's Grav code, it must be your setup/config somehow.
