### ISSUE TITLE
Blueprint default override header.visible not respected by admin page creation

### ISSUE THREAD

**Issue by paulrudy** [getgrav/grav#2853]
In an inherited theme, I make an 'item.yaml' blueprint that extends the parent theme's 'item.yaml':

```yaml
extends@: item

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            overrides:
              fields:
                header.visible:
                  toggleable: false
                  default: 0
```

In 1.6.x, when using the Item template to create a page 'New Item' in Admin with the setup outlined above, clicking 'Save' automatically creates the following code in the new page's header:

```
---
title: 'My new blog item'
visible: false
---

However, in 1.7.0-rc.7, doing so omits the `visible: false` line, even though the admin GUI correctly shows 'Disabled' as selected next to the 'Visible' item. To have the `visible: false` line saved to the page header requires manually clicking on the 'Disabled' button in the GUI and then saving the page.
