### ISSUE TITLE
Grav 1.7 no longer accepts groupnames that are integers

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav#2863]
I have a group.yaml file that is similar to this:

```yaml
11796:
  groupname: '11796'
  readableName: Group-11796
  icon: users
  access:
    site: {  }
    admin: {  }
```

This throws the following error:

Argument 1 passed to Grav\Framework\Flex\Storage\SimpleStorage::getObjectMeta() must be of the type string, int given, called in /var/www/html/system/src/Grav/Framework/Flex/Storage/SimpleStorage.php on line 444

The type hinting is expecting a string, but since the group name is an integer, this fails.

I'm renaming my groups for now, but I wanted to bring it to your attention in the event this breaks other things.
