### ISSUE TITLE
Reuse a module several times on the same page

### ISSUE THREAD

**Issue by bu3tt1** [getgrav/grav#2892]
It's possible to reuse the same module on the same page?

My modular.md

```
---
title: Home
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _text
            - _images
            - _text
display: true
---

```

**Comment by mahagr** [comment]
Yes, you can. There's nothing preventing you from doing that, it can all be handled inside twig file.

**Comment by bu3tt1** [comment]
I'm sorry...it's very simple (on the other hand like the whole CMS)!

Modular Pages to refer to the Twig-template uses the Markdown-file name and not the folder name.

So just do the following:

**modular.md**
```
---
title: Home
content:
    items: '@self.modular'
    order:
        by: default
display: true
---
```
**Folder and file structure**
```bash
user/pages/01.home/
|-- modular.md
|-- 01._text
|   |-- text.md
|-- 02._images
|   |-- images.md
`-- 03._text
    |-- text.md
```
