### ISSUE TITLE
Support for Native Lazy Loading of Images

### ISSUE THREAD

**Issue by angusmcb** [getgrav/grav#2910]
Native lazy loading of images is now supported in chrome and firefox.
[https://caniuse.com/#feat=loading-lazy-attr](https://caniuse.com/#feat=loading-lazy-attr)

Would it be possible to support this in Grav? Possibly even setting it as the default for all images inserted through markdown?

Thanks!

**Comment by rhukster** [comment]
This has been added to latest 1.7 branch.

**Comment by julienbenisty** [comment]
Pretty cool this simple yet powerful browser native feature has been added as a config in Grav. 
Sometimes, something little and simple can go a long way :)

**Comment by angusmcb** [comment]
That is great :-)

Another related suggestion is to include the height="" and width="" properties, so there is no possibility of jank when lazy loading (I understand it also stops jank even when not lazy loading).

I realise that might be more difficult, as you would need to know the image file width and height.

**Comment by 01Kuzma** [comment]
That's strange. I've upgraded to 1.7 RC16 and Admin Panel v1.9.16, but these lines are missing in `blueprints/config/system.yaml`:
```
            images.defaults.loading:
              type: select
              size: small
              label: PLUGIN_ADMIN.IMAGES_LOADING
              help: PLUGIN_ADMIN.IMAGES_LOADING_HELP
              highlight: auto
              options:
                auto: Auto
                lazy: Lazy
                eager: Eager
```
