### ISSUE TITLE
Boolean header field values in a list

### ISSUE THREAD

**Issue by mloitm** [getgrav/grav#2923]
Boolean page fields in lists are saved as '1'/'0' or true/false, depending if the field is in a list or not.

This has changed in 1.7 as 1.6 seems to behave correctly.

Blueprint to reproduce the behaviour:

```yaml
title: Article
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.boolean_value:
              type: toggle
              label: Toggle
              default: 1
              highlight: true
              options:
                1: 'Yes'
                0: 'No'
              validate:
                type: bool
            header.list:
              name: list_of_booleans
              type: list
              label: List of booleans
              fields:
                .boolean_list_item:
                  type: toggle
                  label: Toggle in a list
                  default: 1
                  highlight: true
                  options:
                    1: 'Yes'
                    0: 'No'
                  validate:
                    type: bool

```

Saving page in `1.7.0-rc.11` results in the following file content:

```
---
title: test-article
boolean_value: true
list:
    -
        boolean_list_item: '1' 
---
```

The same thing in `1.6.25`:

```
---
title: test-article
boolean_value: true
list:
    -
        boolean_list_item: true
---
```

Environment: Tested in docker with Dockerfile from https://github.com/getgrav/docker-grav.
For 1.7 replaced `GRAV_VERSION` variable in Dockerfile.
