### ISSUE TITLE
`system.pages.hide_empty_folders` should be Boolean

### ISSUE THREAD

**Issue by NoNoNo** [getgrav/grav#2925]
`system.pages.hide_empty_folders` should be of type Boolean IMHO:

```yaml
pages.hide_empty_folders:
    type: selectize
    size: large
    label: PLUGIN_ADMIN.HIDE_EMPTY_FOLDERS
    help: PLUGIN_ADMIN.HIDE_EMPTY_FOLDERS_HELP
    classes: fancy
    validate:
        type: commalist
```

[system/blueprints/config/system.yaml#L243](https://github.com/getgrav/grav/blob/develop/system/blueprints/config/system.yaml#L243)
