### ISSUE TITLE
Blueprint "ordering@" behaviour

### ISSUE THREAD

**Issue by N-Parsons** [getgrav/grav#2931]
I was exploring extension of theme blueprints and I came across unexpected behaviour with `ordering@` compared to [what the docs say](https://learn.getgrav.org/16/forms/blueprints/advanced-features#changing-field-ordering).

As a simple example, I was importing the Quark theme's blueprint and changing the ordering for the `grid-size` field.

```yaml
form:
  import@:
    type: blueprints
    context: themes://quark
  fields:
    grid-size:
      ordering@: -1
```

The docs say that setting `ordering@: -1` should make the field the first one, but it currently places it second from last, while setting `ordering@: 0` successfully positions it first.

I've tested it on both Grav v1.6.25 (Admin v1.9.14) and Grav v1.7.0-rc.11 (Admin v1.10.0-rc.11) with the same results.
