### ISSUE TITLE
Fieldset text does not support markdown or HTML

### ISSUE THREAD

**Issue by ayozehd** [getgrav/grav#2934]
Just noticed we can't include markdown content or HTML into the `text` attribute of fieldsets. Sometimes plugins or themes developers want to add some info about the section or bla bla... 

![image](https://user-images.githubusercontent.com/37075876/83974268-1c5ba780-a8e4-11ea-8cff-c3478273a12d.png)

**Steps to reproduce:**
```
foo.fieldset:
   type: fieldset
   markdown: true
   text: 'Text having HTML or [Markdown](example.org)'
```

Tested on Grav 1.7.0-rc.11 and Admin 1.10.0-rc.11
