### ISSUE TITLE
Blueprints: Ordering causes 'dangerous_tags' warning

### ISSUE THREAD

**Issue by hdwebpros** [getgrav/grav#2940]
On https://learn.getgrav.org/16/forms/blueprints/advanced-features#changing-field-ordering it says to add `ordering@:` to change the ordering of blueprint fields, but if I do so it causes 

> NOTICE: Grav found potential XSS issues in header.example: 'dangerous_tags'

Example portion of the customized blueprint:
```
title: Example
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:
            header.example:
              ordering@: 1
...
```

**Comment by ricardo118** [comment]
what version of admin is this ?

using the following:
```
extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:

            header.faq:
              type: list
              label: Accreditations
              style: vertical
              collapsed: true
              fields:

                .question:
                  type: text
                  label: Question

                .answer:
                  type: textarea
                  rows: 5
                  label: Answer

            spacer2:
              type: spacer
              underline: true

            content:
              ordering@: 3
            header.media_order:
              ordering@: 99
```
 as an example doesnt trigger this for me
