### ISSUE TITLE
Page collection containing pages in ANY language?

### ISSUE THREAD

**Issue by mbirth** [getgrav/grav#2952]
I've setup a site that supports English and German languages where 90% of the pages are English-only and the rest is mostly German-only with only a few bi-lingual.

For the home page, I want to have a list of the most recently changed pages REGARDLESS OF THEIR LANGUAGE.

At the moment, I'm doing this:

```yaml
content:
  items:
    '@taxonomy.category': wiki
  order:
    by: header.modified_date
    dir: desc
  pagination: true
```

But this only returns pages in the currently selected/detected language. How do I get a collection of ALL pages with `'@taxonomy.category': wiki` - regardless of their primary language. Is that possible using frontmatter?
