### ISSUE TITLE
frontmatter twig variable substitution not working in file field destination

### ISSUE THREAD

**Issue by GavinTomlins** [getgrav/grav#2980]
Given the scenario of user **JohnCitizen** logged into Grav and to uploading a file the **destination:** field attribute of file does not do twig variable substitution correctly.

Example:
```
---
title: Home

access:
  site.login: true
  admin.login: true

process:
  twig: true
  twig_first: true

form:
    name: upload

    fields:
        upload:
          label: upload Label
          type: file
          destination: 'user/{{ grav.user.username }}'
          multiple: true
          accept:
           - image/*
    buttons:
        upload:
          type: upload
          value: Upload
    process: 
        userinfo: true 
---

# Testing File Upload
## Storing file uniquely in logged in user. Making life a little easier...

```
With twig processing enabled in **system.yaml**
```
   frontmatter:
    process_twig: true
    ignore_fields:
      - form 
      - forms
```
placing **frontmatter.yaml** in the same folder with configuration

```
frontmatter:
    process_twig: true
```
If JohnCitizen uploads a file called logo.png

{{grav.user.username}} is not substituted correctly for the current logged in user with the file and folder created
/user/JohnCitizen/logo.png ie. Expected correct behaviour

Event though using {{dump(grav.user.username)}} the debugger bar outputs the correct result of logged in user..

The **incorrect** behaviour that occurs is the following:
/user/{{grav.user.username}}/logo.png
