### ISSUE TITLE
Config blueprint site.yaml fails to handle file field in Admin

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav#2991]
I have a `user/blueprints/config/site.yaml` file (shown at bottom of this post) that adds a few fields for Admin access on 1.7-rc15. It fails to manage image uploads, however - the data is written to`user/config/site.yaml` but the Admin shows an empty drop zone. 

Here's an example of what happens when uploading an image (text field data has already populated and saved):

**The user/config/site.yaml before image upload**

```
locationservicelist:
  -
    service: 'Building Security'
    description: 'Our extensive range of...'
    photo: {  }
  -
    service: Communications
    description: 'In addition to the...'
    photo: {  }
```

*The Image uploaded the Building Security photo field in Admin*

![Screen Shot 2020-08-25 at 9 12 47 AM](https://user-images.githubusercontent.com/998832/91178525-3b7fff00-e6b3-11ea-8017-b24793128286.png)

**The user/config/site.yaml after image upload and successful Save operation**

```
locationservicelist:
  -
    service: 'Building Security'
    description: 'Our extensive range of...'
    photo:
      user/images/location/services/location_building-security.jpg:
        name: location_building-security.jpg
        type: image/jpeg
        size: 36685
        path: user/images/location/services/location_building-security.jpg
  -
    service: Communications
    description: 'In addition to the...'
    photo: {  }
  -
```

**The Building Security field in Admin after Save**

![Screen Shot 2020-08-25 at 9 16 26 AM](https://user-images.githubusercontent.com/998832/91178820-b6491a00-e6b3-11ea-96a4-0c4226b928e6.png)

**My `user/blueprints/config/site.yaml` file**

```
'@extends':
    '@parent'

form:
    fields:
        content:
            fields:
                tollfreenumber:
                    type: text
                    label: 'Toll-Free Number'
                    help: 'The toll-free number as it will appear to visitors, e.g., 1-800-111-2222.'
                tollfreelink:
                    type: text
                    label: 'Toll-Free Link'
                    help: 'The toll-free link that will make the call e.g., +18001112222.'
                whyworkwithtroy:
                    type: textarea
                    label: 'Why Work with X?'                      
                contactconfirm:
                    type: markdown
                    label: 'Contact form confirmation message'                      
                applyconfirm:
                    type: markdown
                    label: 'Application form confirmation message'                      
                accessconfirm:
                    type: markdown
                    label: 'Accessibility form confirmation message'                      
                rfpconfirm:
                    type: markdown
                    label: 'RFP form confirmation message'                      
                fieldset:
                  type: fieldset
                  title: Location Services
                  text: The text and images below are used across Location pages where provided.
                  collapsed: true
                  collapsible: false
                  fields:
                    locationservicelist:
                      name: locationservicelist
                      type: list
                      style: vertical
                      label: 'Location Services'
                      fields:
                        .service:
                          type: text
                          label: 'Service Name'
                        .description:
                          type: textarea
                          rows: 4
                          label: 'Service Description'
                        .photo:
                          type: file
                          label: 'Service Image'
                          destination: 'user/images/location/services'
                          accept:
                            - image/*
```
