### ISSUE TITLE
Get "is page published"

### ISSUE THREAD

**Issue by marexx** [getgrav/grav#3034]
Hi,
I use this in my blueprint, so i can select which page should be listet inside the content:
```
    header.involved:
      name: involved
      type: list
      style: vertical
      label: Involved Lawyers
      fields:
        .name:
          type: text
          label: Name
        .text:
          type: text
          label: Jobs
        .link:
          type: pages
          size: medium
          classes: fancy
          label: Select involved lawyers
          show_all: true
          show_modular: false
          show_root: false
```
now we have the problem, that some pages are not available any more. So i need to check, if the linked page is still published because if not, i just want to display the pageTitle whithout the link.
At the moment, if i Debug the var "**page.header.involved.link**" i just get the link to the page, no more data..
