### ISSUE TITLE
Twig debugging enabled by default, twice

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3043]
In the grav core download from the website the `system.yaml` file has twig debugging enabled by default. I am not sure how critical this is, but I'd expect it to be opt-in.

Second it seems to be available in two places:
```yaml
twig:
  cache: true
  debug: true # <--- debug enabled
  auto_reload: true
  autoescape: false

debugger:
  enabled: false # <--- debug enabled
  twig: true
  shutdown:
    close_connection: true
```

But the doc does not mention the second option:
https://learn.getgrav.org/16/basics/grav-configuration#debugger

Maybe it is obsolete?

**Comment by rhukster** [comment]
These are two settings, Twig has its own debug mode that should be enabled by default as it allows you to use the `dump()` command and has no real performance impact.

**Comment by NicoHood** [comment]
I just noticed I posted my markers on the wrong place (facepalm):
```yaml
twig:
  cache: true
  debug: true # <--- debug enabled
  auto_reload: true
  autoescape: false

debugger:
  enabled: false
  twig: true # <--- debug enabled
  shutdown:
    close_connection: true
```

Now I understand the first, but what about the second? Could that be added to the documentation?
