### ISSUE TITLE
Grav language API returns false

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3045]
I noticed, that unless you define any supported language the following commands will all return false. This is not documented and also confusing to me:
```
{{ grav.language.enabled|defined('no')|default('false') }}
{{ grav.language.getDefault }}
{{ grav.language.getActive }}
{{ grav.language.getLanguage }}
```

```yaml
languages:
  translations: true
  http_accept_language: true
  include_default_lang: false
  default_lang: en
  # supported:
  #   - en
```

I expect that the functions return `en` or if `http_accept_language` is used any other language.

Another issue I am facing is, that if I set supported languages (en, de) the browser now always redirects to `/de/index.php` for example, when I am using a german browser. If i do not specify and supported language it will show all languages under the same url. That behavior is inconsistent to me.
