### ISSUE TITLE
How to change blueprints data

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#3087]
I have files:
`product.html.twig` and  `product.yaml
`
in `product.yaml`
we have some custom field, eg:

 ```
  header.price:
              ordering@: 4
              type: textarea
              label: 'Цена '
              style: vertical
              default: ????
```
how to auto fill `default` field in admin from php,  variable set in php
