### ISSUE TITLE
What about versions.yaml?

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3111]
There is a versions.yaml file in my config folder, but it still lists grav version 1.6.29 (1.6.31 installed). What is this used for? I can imagine that this becomes handy when dealing with dependencies, however it seems to be broken for me.

**Comment by rhukster** [comment]
It's not supposed to update, it just is a way for us to know what the version was when the file was created.  It's used to track versions for things like plugin installations. 

For example:

```
core:
  grav:
    version: 1.7.0-rc.19
    schema: 1.7.0_2020-11-20_1
plugins:
  client_plugin:
    version: 3.0.0
    history:
      - { version: 3.0.0, date: '2020-12-23 20:45:09' }
    schema: 3.0.0_2020-12-18_1
```

I'm on 17 rc 20, but this core created this file at rc.19.  It's very much an internal thing we can use to handle one time jobs (migrations), and other things related to versions.
