### ISSUE TITLE
visibility_requires_access does not work in 1.7

### ISSUE THREAD

**Issue by Japhys** [getgrav/grav#3176]
Hi I am testing my site with 1.7 and while visibility_requires_access: true worked perfectly in 1.6 it does not seem to work in 1.7

Option has been enabled on plugin conf page

Frontmatter has:
```yaml
access:
  site.login: true
  admin.login: true
login:
  visibility_requires_access: true
```

Has something else changed?
