### ISSUE TITLE
Unable to submit form after one invalid submission

### ISSUE THREAD

**Issue by KjellArkel** [getgrav/grav#3190]
I am not sure if this is a bug from my side is or this is a bug in Grav. When a visitor enters invalid information into the form and submits this form it will be invalid (as suspected). After the user has updated the invalid field and tries to resubmit. It shows this message: “This form has already been submitted”. I cannot submit this form unit I go to another page and go back to the form.

This is what my file looks like:

```
---
title: Contact

form:
    name: contact-form
    fields:
        name:
            label: Name
            placeholder: 'Enter your name'
            autocomplete: 'off'
            type: text
            validate:
                required: true
        company:
            label: Company name
            placeholder: 'Enter your company name'
            type: text
            validate:
                required: false
        email:
            label: Email
            placeholder: 'Enter your email address'
            type: email
            validate:
                required: true
        phoneNumber:
            label: Phone number
            placeholder: 'Enter your phone number address'
            type: tel
            validate:
                required: false
        demoSubject:
            type: checkboxes
            label: Select a subject
            default:
                option-one: false
                option-two: false
            options:
                option-one: CrisisSuite
               option-two Social media trainer
            use: keys
            validate:
                required: true
            classes: checkboxes
        g-recaptcha-response:
            type: captcha
            label: Captcha
            recaptcha_not_validated: 'Captcha is not valid'
    buttons:
        submit:
            type: submit
            value: Submit
            classes: primary-button
    process:
        captcha: true
        email:
            from: '{{ config.plugins.email.from }}'
            to: '{{ config.plugins.email.to }}'
            subject: 'some message'
            body: "{% include 'forms/data.html.twig' %}"
        redirect: en/contact/thankyou
---
```
I am using Grav version: 1.7.3 and PHP version: 7.4.14. This is a modular contact form. Any suggestions are welcome. More information can be given if needed. I posted this on the Grav form where somebody had sort of the same issue https://discourse.getgrav.org/t/form-has-already-been-send-after-an-invalid-form-submition/14815
