### ISSUE TITLE
Form Plugin update overwrite the user preferences 

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav#3194]
Hi.
In the latest form plugin updates, I've noticed that this overwrite the user preferences. In my case, I have recaptcha with V3 - Latest version.

In each update of the plugin this value returns to version 2, making the form unusable.

Is there any way to correct this issue?
Thanks so much.

**Comment by rhukster** [comment]
You mean when you save things in admin, it doesn't save your changes? Or do you mean when you updated you lost your configuration?  If the second, did you make changes in `user/plugins/form/form.yaml` ? If so that's normal that an update would overwrite those changes.  Changes should not be made in this location, should be made in `user/config/plugins/form.yaml` per the README/Grav docs etc.

**Comment by pmoreno-rodriguez** [comment]
Hi @rhukster 
I have my form.yaml file in user/config/plugins with this content:
```
enabled: true
built_in_css: true
inline_css: true
refresh_prevention: false
client_side_validation: true
inline_errors: false
files:
  multiple: false
  limit: 10
  destination: self@
  avoid_overwriting: false
  random_name: false
  filesize: 0
  accept:
    - 'image/*'
recaptcha:
  version: '3'
  theme: light
  site_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
The original form.yaml in user/plugin/form has the following:
```
enabled: true
built_in_css: true
inline_css: true
refresh_prevention: false
client_side_validation: true
inline_errors: false
files:
  multiple: false          # To allow multiple files, default is single
  limit: 10                # Number of allowed files per field (multiple required)
  destination: 'self@'     # Where to upload the files (path and self@, page@, theme@)
  avoid_overwriting: false # Prevent files with the same name to be overridden. Date prefix will be added
  random_name: false       # Generate a random 15 long string name for the uploaded files
  filesize: 0              # Maximum file size allowed (in MB)
  accept:                  # List of mime/types or file extensions allowed (ie, image/*,.zip,.mp4)
    - image/*
recaptcha:
    version: 2-checkbox
    theme: light
    site_key:
    secret_key:
```
When I update the form plugin (it has happened in two or three last updates), the recaptcha version changes to **2-checkbox**. However, both site_key and secret_key keep their values. I don't know why this happens.
