### ISSUE TITLE
http_accept_language and include_default_lang interference

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3200]
This is my config:
```
languages:
  translations: true
  http_accept_language: true
  include_default_lang: false
  default_lang: en
  include_default_lang_file_extension: true
  supported:
    - en
    - de
    - fr
  content_fallback:
    de: [en]
```

My browser setup:
* Firefox - de
* Chromium - en

On disk I only have `default.md`, no translation (yet).

The following happens:
* Firefox - de
  * `/` -> `/de` (Happens because of `http_accept_language`)
  * `/en` -> `/de` --> this should not happen
  * `/de`
  * `/fr`
* Chromium - en
  * `/`
  * `/en` -> `/`
  * `/de`
  * `/fr`

This means a German user can never access the `en` language with this setup. I think the best solution is to always serve the default language without any redirect but keep the redirect for pages with no prefix if the browser does not use the default language:
* Firefox - de
  * `/` -> `/de` (Happens because of `http_accept_language`)
  * `/en` -> no redirect
  * `/de`
  * `/fr`
* Chromium - en
  * `/` -> no redirect, so when sharing the link, the user can see it in their default language.
  * `/en` -> no redirect
  * `/de`
  * `/fr`
