### ISSUE TITLE
getFormFieldTypes() does not merge settings

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3219]
Imagine a plugin code like this:
```php
    /** @var array */
    public $features = [
        'formfields' => 0
    ];

    /**
     * Get list of form field types specified in this plugin.
     * Only special types needs to be listed.
     * NOTE: This function gets called by the grav plugin framework.
     *
     * @return array
     */
    public function getFormFieldTypes()
    {
        return [
            'rating' => [
                'validate' => [
                    'type' => 'number',
                    'step' => 1,
                    'min' => 1,
                    'max' => 5
                ]
            ]
        ];
    }
```

Now I got the following yaml file:
```yaml
        - name: stars
          type: rating
          label: PLUGIN_RATINGS.RATING_LABEL
          validate:
            required: true
```

Because I specified `validate.required: true` all other settings set by `getFormFieldTypes()` are now lost. I need to repeat them again, which is more error prone:

```yaml
        - name: stars
          type: rating
          label: PLUGIN_RATINGS.RATING_LABEL
          validate:
            min: 1
            max: 5
            step: 1
            type: number
            required: true
```
