### ISSUE TITLE
Broken attachment reference in Flex Objects when destination: self@ used

### ISSUE THREAD

**Issue by phmg701** [getgrav/grav#3225]
Hello,

I'm trying to build a custom flex type `photos` here are the relevant code sections:

```
    photo:
      type: file
      multiple: false
      accept:
        - image/*
      label: Photo
      destination: self@
```

`data` section:

```
  data:
    # Object class to be used, allowing custom methods for the object
    object: 'Grav\Common\Flex\Types\Generic\GenericObject'
    # Collection class to be used, allowing custom methods for the collections
    collection: 'Grav\Common\Flex\Types\Generic\GenericCollection'
    # Index class to be used, works as a quick database-like lookup index
    index: 'Grav\Common\Flex\Types\Generic\GenericIndex'
    storage:
      # Storage class, use single file storage (does not support images and assets)
      class: 'Grav\Framework\Flex\Storage\FolderStorage'
      options:
        formatter:
          class: 'Grav\Framework\File\Formatter\YamlFormatter'
          options:
            file_extension: '.yaml'
            inline: 5           # Save with up to 4 expanded levels
            indent: 2           # Indent with 2 spaces
            native: true        # Use native YAML decoder if available
            compat: true        # If YAML cannot be decoded, use compatibility mode (SLOW)
        folder: user-data://flex-photos
```

Image storage works as expected, storing the photo in the "hashed" folder alongside with the photo.yaml file.
The problem is that no relative path is stored in the .yaml file, so attached image gets lost when editing back the object.
Generated `item.yaml` file:

```
published: true
title: 'Title'
photo:
  AAA.jpg:
    name: AAA.jpg
    type: image/jpeg
    size: 12345
    path: AAA.jpg
```

opposed to:

```
published: true
title: 'Title'
photo:
  user/data/flex-photos/files/AAA.jpg:
    name: AAA.jpg
    type: image/jpeg
    size: 12345
    path: user/data/flex-photos/files/AAA.jpeg
```

when using relative path destination `destination: user/data/flex-photos/files`.

I haven't tried yet to build a directory to list photos, but I'm guessing it wouldn't work either, if I get a basic understandig of Grav Forms and Assets management.

Thank you!
