### ISSUE TITLE
Problem with upload

### ISSUE THREAD

**Issue by Kovic77** [getgrav/grav#3236]
Hi, upload of files in list suddenly stopped working. When Im trying to upload a file, I got an error: 
An error occurred while trying to upload the file fade-pas-min.png
Undefined index: *

Blueprint:
```yaml
title: Features
'@extends': default

form:
  fields:
    tabs:
      fields:
        features:
          type: tab
          title: Loga

          fields:
            header.id:
              name: id
              type: text
              label: ID Sekce

            header.items:
              name: features
              type: list
              label: Ikony

              fields:
                .icon:
                  type: file
                  label: Logo
                  destination: 'self@'

                .width:
                  type: number
                  label: Šířka
                  size: medium

                .alt:
                  type: text
                  label: Popis obrázku
                  size: medium
```

Thanks
