### ISSUE TITLE
Question: How to show page only for specific group?

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#3240]
I have group `RH1` with one user in it.

I have this code for read closed page:
```
permissions:
    groups:
        RH1:
            read: false
```

But after login this user still can open this page.

Any ideas how to show page ONLY for specific group?

**Comment by Sogl** [comment]
Found some info here:
https://discourse.getgrav.org/t/page-group-access/14139
https://learn.getgrav.org/17/advanced/groups-and-permissions#assigning-a-user-to-a-group

This code:
```
access:
    site:
        login: true
        paid: true
```
close page from guests, but with `paid: false` it becomes open 😳 
User isn't logged!

**Comment by mahagr** [comment]
The first example worked only in admin as permissions are only for CRUD (Create, Read, Update, Delete) operations.

The second example also makes sense, because you may want to display a page for users who haven't paid, including guests. That access field matches if any of the rules match.

**Comment by Sogl** [comment]
But how to show page for only logged-in users (`login: true`) AND users in paid group (`paid: true`)?

**Comment by mahagr** [comment]
You don't need to as guests have no access. So just use paid.

**Comment by Sogl** [comment]
I don't understand how it works... user in `paid` group doesn't have access to `paid: true` pages, but have access to `paid: false` pages (like guests). Why? 🤔

**Comment by mahagr** [comment]
So did you try:

```
access:
    site:
        paid: true
```

**Comment by mahagr** [comment]
It works for me. I cannot access the page unless I have logged in with a user with paid access (or super admin).

**Comment by Sogl** [comment]
@mahagr 
Ok, from the beginning.

1) I have `paid` group. All permissions are not set.
2) I have user `irina` in `paid` group. Permissions are not set except `login to site: true`
3) Two pages (`chapter.ru.md` in GravLearn4 theme).

Page one:
```yaml
---
title: 'Page one'
permissions:
    groups:
        paid:
            read: true
login:
    visibility_requires_access: false
access:
    site:
        paid: true
---
```
Page two:
```yaml
---
title: 'Page two'
permissions:
    groups:
        paid:
            read: false
login:
    visibility_requires_access: false
access:
    site:
        paid: false
---
```

4) When user not logged in, `Page two` works and I see login page when click on `Page one`:
![image](https://user-images.githubusercontent.com/7556290/118396067-6271cd00-b656-11eb-8894-abd8eaf9d1da.png)
5) And when i log-in with `irina` in `Page one`, I see:
![image](https://user-images.githubusercontent.com/7556290/118397399-67397f80-b65c-11eb-899b-f86d0920d62b.png)

`Page two` works fine.

Why doesn't it work?
