### ISSUE TITLE
Three regressions when editing a page containing a list (Grav 1.7.6 compared to 1.6.31)

### ISSUE THREAD

**Issue by fdruide** [getgrav/grav#3242]
Hello,

We noticed 3 minor regressions in Grav 1.7.6 compared to Grav 1.6.31 when editing a page containing a list :

1. When a list is collapsed, the last item of the list overflows his container.
2. When a collapsed item is revealed, the text in the editor is invisible until we click inside the editor.
3. When adding a new item in the list, uploading an image cause an error _Undefined index: *_.

Here is a simple blueprint _mytest.yaml_ used for testing :
```
extends@: default

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: My Blueprints
          fields:
            header.title:
              unset@: true
            content:
              unset@: true
            header.media_order:
              unset@: true
            header.sections:
              label: Sections
              type: list
              collapsed: true
              style: vertical
              fields:
                .image:
                  type: file
                  label: Image
                  destination: 'self@'
                .text:
                  type: markdown
                  label: Text
```

Here is a _mytest.md_ page. You can use any image.
```
---
title: mypage
sections:
    -
        text: 'My text'
        image:
            140x100.png:
                name: 140x100.png
                type: image/png
                size: 333
                path: 140x100.png
---
```

1. Overflow
<img width="400" alt="grav-list-overflow" src="https://user-images.githubusercontent.com/32466736/109024320-9f4baa80-768b-11eb-89a6-16dbc834c664.png">

2. Invisible text after revealing an item
<img width="400" alt="grav-list-invisibletext" src="https://user-images.githubusercontent.com/32466736/109024381-b12d4d80-768b-11eb-877c-ba77d90ca8e7.png">

The text appears after a click inside the editor
<img width="400" alt="grav-list-invisibletext-afterclick" src="https://user-images.githubusercontent.com/32466736/109024469-d0c47600-768b-11eb-9249-57aee7e5a4d9.png">

3. After adding a new item, this error appears when uploading a new image. It's possible to bypass by (1) adding a new empty item, (2) saving the page and (3) uploading the image. 
<img width="400" alt="grav-list-uploadimage" src="https://user-images.githubusercontent.com/32466736/109024514-d9b54780-768b-11eb-96ba-39dc0dcbf91a.png">

Thank you for your time! :)
