### ISSUE TITLE
Upload to a collection fails since Update to 1.7.x

### ISSUE THREAD

**Issue by ferdynator** [getgrav/grav#3245]
We use a custom page blueprint:

```yaml
title: Gallery

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        gallery:
          type: tab
          title: Gallery

          fields:
            header.media:
              name: media
              type: list
              label: Bilder
              fields:
                .title:
                  type: text
                  label: Titel
                .file:
                  type: file
                  multiple: false
                  label: Bild
                  random_name: true
                  destination: 'self@'
                  accept:
                    - image/*
```

Uploading images fails at first with this error message:
![Screenshot_20210226_185628](https://user-images.githubusercontent.com/3531327/109337203-bf829180-7864-11eb-9283-0e4805a494ff.png)

After saving the page it is possible to add *one* more item. The next fails again. Replacing or removing images works fine. I guess there is some illegal offset access for the images but don't know where to look. Any ideas?
