### ISSUE TITLE
Page blueprint : Conditional tab

### ISSUE THREAD

**Issue by unmick** [getgrav/grav#3248]
Hello ,

As explain in the [Forum](https://discourse.getgrav.org/t/page-blueprint-with-conditional-tab/16065/3)
i would like to display a tab in a blueprint if something

It works perfectly for a field `type: conditional
```yaml
                            condition: "'true'"            
                            fields:            
                                header.test:
                                    type: toggle
                                    label: TEST`
```

And i would like to know if it could be possible for a tab .

What i have tried is 
```yaml
title: Gallery  
  '@extends': 
   type: default
   context: blueprints://pages
form:
 fields:
   tabs:
     type: tabs
     active: 1
     fields:
       gallery:
         type: tab
         title: PAGE_MAP.GALLERY.LABEL
         underline: true
         import@1:
           type: partials/gallery
           context: theme://blueprints  
       **conditionfeat:
         type: conditional
         condition: "'true'"            
         fields:
           features:
             type: tab**
             title: PAGE_MAP.FEATURES.LABEL    
             underline: true
             import@2:
               type: partials/features
               context: theme://blueprints 
```

In fact, i use the same yaml for standard pages or blog ones and i would like to display the tab dedicated to the blog only if the parent is a blog

Thanks for your help
