### ISSUE TITLE
category and tags in Flex Objects

### ISSUE THREAD

**Issue by phmg701** [getgrav/grav#3257]
Hello,

while testing Flex Objects, I noticed some unexpected behaviours.
First, here's relevant parts of my custom Flex Object definition: 

```
    test_tags:
      type: selectize
      size: large
      label: Test Tags
      classes: fancy
      validate:
        type: commalist

    categories_and_tags:
      type: taxonomy
      label: Category and Tag
      multiple: true
      validate:
        type: array
```

```
    list:
      title: title
      fields:
        test_tags:
```

* test_tags do not have the autocomplete function, otherwise found in `taxonomy` field type. This is very very helpful in creating a catalog or any other type of organized data.
* test_tags results in `["Test1","Test2","Test3"]` in list view, typical array/plain text representation.
* test_tags cannot be searched when other text fields can. We could expect the field to be searchable, given its plain text representation.
* no matter how I try to configure it, in list view, `taxonomy` never displays. However this way we have the autocomplete function.

I think I tried many combinations, if not every possible one, so I decided to open this issue.

Is there something else I can try?

As usual, thank you!

**Comment by mahagr** [comment]
You need to implement support for the taxonomy for your type, it's not automated (yet). For now, taxonomy works only for pages and only by using the default field.

**Comment by phmg701** [comment]
Thank you, that explains
> * no matter how I try to configure it, in list view, taxonomy never displays. However this way we have the autocomplete function.

So, creating
```
test_tags:
      type: selectize
      size: large
      label: Test Tags
      classes: fancy
      validate:
        type: commalist
```
and
```
test_category:
      type: selectize
      size: large
      label: Test Category
      classes: fancy
      validate:
        type: commalist
```
would be a way to achieve data organization, mimicking Category and Tags, right?
That leads to the other part of the strange behaviour:
> * test_tags do not have the autocomplete function, otherwise found in `taxonomy` field type. This is very very helpful in creating a catalog or any other type of organized data.
> * test_tags results in ["Test1","Test2","Test3"] in list view, typical array/plain text representation.
> * test_tags cannot be searched when other text fields can. We could expect the field to be searchable, given its plain text representation.

Am I doing something wrong in blueprint's field definition?

Thank you!
