### ISSUE TITLE
Theme inheritance not working, dash '-' symbol in theme name? 

### ISSUE THREAD

**Issue by maxroseGIT** [getgrav/grav#3261]
I followed [https://learn.getgrav.org/themes/customization#theme-inheritance](https://learn.getgrav.org/themes/customization#theme-inheritance) but I get this error when trying to inherit from themes like [knowledge-base](https://github.com/Perlkonig/grav-theme-knowledge-base) or [project-space](https://github.com/OleVik/grav-theme-project-space):
```
Sorry, something went terribly wrong!
0 - syntax error, unexpected '-', expecting '{'
```

I use Grav v1.7.7 - Admin v1.10.6.

My theme files are located in the theme folder with name 'kb2'.

I just copied everything of the 'blueprints.yaml' of the original knowledge-base theme into
`blueprints.yaml`:
```
name: Knowledge Base Modified
version: 2.1.1
description: A theme for a knowledge base or FAQ
icon: database
author:
  name: Aaron Dalton
  email: aaron@daltons.ca
homepage: https://github.com/Perlkonig/grav-theme-knowledge-base
demo: http://perlkonig.com/knowledge-base
keywords: grav, theme, faq, knowledge base, responsive, css3, html5, purecss
bugs: https://github.com/Perlkonig/grav-theme-knowledge-base/issues
readme: https://github.com/Perlkonig/grav-theme-knowledge-base/blob/master/README.md
license: MIT

dependencies:
  - error
  - problems
  - relatedpages
  - simplesearch
  - readingtime
  - 'count-views'
```

Then I created the following lines for
`kb2.php`:
```
<?php
namespace Grav\Theme;

class kb2 extends knowledge-base
{
   // Some new methods, properties etc.
}
?>
```
and added the streams so that
`kb2.yaml` contains:
```
enabled: true
dropdown:
  enabled: true

params:
  articles:
    root: /home                # the route where the articles themselves live
    blacklist: ['scratch']     # list of categories to ignore
    show:
      date: true      # show article date in the article header
      authors: true   # show article authors in the article header
      topics: true    # show assigned topics in the article header
      time: true      # show reading time in the article header
  front:              # params for the front page content
    maxrows: 3        # the maximum number of rows on the front page
    maxentries: 5     # maximum number of articles displayed for each category
  sidebar:            # params for the sidebar
    maxentries: 5     # maximum number of articles to display in "Popular" and "Latest" sections
    show:
      categories: true  # show Category list in the sidebar
      popular: true     # show the Popular Articles sidebar
      latest: true      # show the Latest Articles sidebar

streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/kb2
         - user/themes/knowledge-base
```

I am aware of a related discussion in [Bug#1353](https://github.com/getgrav/grav/issues/1353). But that error was fixed.

When I test inheritance with Quark as the Base-Theme everthing is fine...

Does anyone have an idea why I get this error when trying to inherit from themes with a dash '-' in their names?
