### ISSUE TITLE
**BUG** blueprint file upload no longer working correctly, creates folder at root of GRAV

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav#3275]
I ran across this recently with a site with custom blueprint that has a file upload for a video background like so...

here's my 'default.yaml

```

extends@: default

form:
  fields:
    tabs:
      fields:
        content:
            type: tab
            fields:
              header.backgroundvideoupload:
                name: backgroundvideo
                type: file
                label: Background video upload
                multiple: false
                destination: '@self/videos'
                accept:
                  - video/*

              header.backgroundvideo:
                type: filepicker
                folder: '@self/videos'
                label: Select a background video
                preview_images: true
```

this USED to work fine, saving a file into the relevant page folder in a subfolder 'videos' 

But **now** it creates a folder called '@self' with a subfolder 'videos' at the root levee of the Grav install folder.

Just tested this on a completely vanilla fresh install of Grav 1.7.7 admin 1.10.6
