### ISSUE TITLE
Redis cache not working

### ISSUE THREAD

**Issue by mabushey** [getgrav/grav#328]
Here is the snippet of my user/config/system/yml file:
```
cache:
  enabled: true
  check:
    method: file
  driver: redis
  redis:
    server: 127.0.0.1
    port: 6379
  prefix: g
  lifetime: 604800
  gzip: false
```
`redis-cli --scan` shows no keys added.

I tried changing redis to memcache:
```
  driver: memcache
  memcache:
    server: 127.0.0.1
    port: 6379
```
As redis is a superset of memcache, however I get:
`Class 'Memcache' not found`
`151                 $memcache = new \Memcache();`
