### ISSUE TITLE
User with Site Configuration permissions is not allowed to manage Site Configuration

### ISSUE THREAD

**Issue by arkhi** [getgrav/grav#3322]
I’m not sure if this Issue should be filed in the admin plugin or here, so I’ll go for the more generic approach.

1. I create a group `group-config-site` with the following permissions:
     ```yaml
    group-config-site:
      access:
        admin:
          login: true
          configuration:
            site: true
    ```
1. I create a user `user-config-site`.
1. I assign the group `group-config-site` to `user-config-site`.
1. I login with `user-config-site`.
1. In the Site Configuration page (/admin/config/site), I change the title of the site.
1. I submit the form to save the change.
1. The message “You have insufficient permissions for task save.” is displayed.
1. The changes are not saved.

Adding `system: true` to the group allows `user-config-site` to save the Site Configuration.

This is based on the environment in https://github.com/getgrav/grav-plugin-admin/issues/2001 and the following (latest) versions:

- Grav v1.7.1.2
- Admin Panel v1.10.12
- Email v3.1.2
- Error v1.7.1
- Flex Objects v1.0.7
- Form v5.0.1
- Login v3.4.2
- Markdown Notices v1.1.0
- Problems v2.1.1
