### ISSUE TITLE
http_accept_language not working as expected for sites where not all pages are translated

### ISSUE THREAD

**Issue by angusmcb** [getgrav/grav#3362]
For multi-language sites, where not all content is translated, http_accept_language does not behave as I think it is expected it to.

For example, for a site with two languages: en and fr, default language english, using the content_fallbacks as follows:
```
  content_fallback:
    fr: fr
    en: en
```

Not all content is available in French, so some pages do not appear in the menu if site is in french. This is as expected.

If `http_accept_language: true`, then a visitor with the browser http-accept set as fr will be directed to the french language page if no language is specified in the url (expected), even if that page does not exist (unexpected).

I think the expected behaviour should be to only forward to the french language page if the page exists, and if not then reroute to either:
1) Other accepted languages in the order that the browser has provided them, and if this is not possible
2) The first language in which that page is available.

Sorry this is a slightly difficult to explain issue - I hope this is clear!

(for reference, here are all the settings I am using)

```
languages:
  supported:
    - en
    - fr
  default_lang: null
  include_default_lang: true
  pages_fallback_only: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: true
  override_locale: false
  content_fallback:
    fr: fr
    en: en
```
