### ISSUE TITLE
Error related to blueprint causes Grav / Admin to crash

### ISSUE THREAD

**Issue by yankl** [getgrav/grav#3364]
I am getting the follow error: 
```
TypeError
Argument 1 passed to Grav\Common\Data\BlueprintSchema::processFormRecursive() must be of the type array or null, string given, called in C:\laragon\www\grav-frish\system\src\Grav\Common\Data\BlueprintSchema.php on line 320
```

Here is how I can reproduce this error on a relatively fresh install with Quark theme. 
In `quark/templates/` I add simple `test.html.twig`:

`{% extends 'default.html.twig' %}`

in `user/pages/03.testbug` I add `test.md`: 

```
---
title: test
pick: BPY_1.1.1_Read_01.mp3
content_fallback:
    -
        key: bin
        value: BPY_1.1.1_Read_b_1.mp3
---
```

Finally, I add  `test.yaml` to `quark/blueprints/`: 

```
title: Oysyes Blueprint
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1
      
      fields:
        content:
          fields:
            header.letters:
              type: list
              label: Letters
              min: 4
              max: 4
              
              fields:
                .letter_itself:
                  type: list
                  label: Letter Audio
                  max: 2
                  
                  fields: 
                    .letter:
                      type: text
                      label: Letter
                    .file:
                      type: filepicker
                      folder: 'self@'
                      accept:
                        - .mp3
                      label: Audio
                
                .words:
                  type: list
                  label: Words
                  
                  fields:
                    .word:
                      type: text
                      label: Word
                     
                    .file:
                      type: filepicker
                      folder: 'self@'
                      accept:
                        - .mp3
                      label: Audio
                      
            .words_you_know:
              type: list
              label: Known Words
              
              fields:
                .word:
                  type: text
                  label: Word
                 
                .file:
                  type: filepicker
                  folder: 'self@'
                  accept:
                    - .mp3
                  label: Audio
            
            .words_to_read:
              type: list
              label: Words to Read
              
              fields:
                .word:
                  type: text
                  label: Word
                 
                .file:
                  type: filepicker
                  folder: 'self@'
                  accept:
                    - .mp3
                  label: Audio
```

Then, in .../admin/pages/testbug/mode:normal, the blueprint seems to work correctly in terms of the form created. But when I click Save, I get the mentioned error: 
![image](https://user-images.githubusercontent.com/425828/118949788-3dd16a00-b962-11eb-9d65-e871e3e0cf92.png)

I'm sure this can be further simplified but that's what I have for now. I made an issue here instead of in Admin plugin, because the error is coming from Grav\Common\Data\BlueprintSchema and not from the Admin plugin. 

Grav v1.7.15 - Admin v1.10.15
