### ISSUE TITLE
Weird first and last line in frontmatter.yaml caused by page blueprint

### ISSUE THREAD

**Issue by markusritschel** [getgrav/grav#3377]
Hi, 
As I also described in the [Discord channel](https://discord.com/channels/501836936584101899/510527519066161193/851417936626319380), the following issue occurs recently on my site:
For a page on a friend's band website, I've set up a page blueprint with a custom tab in the Admin panel to insert new tour dates. Those entries were usually written to a `frontmatter.yaml` file since they need to be the same for each of the languages on the website.
I know that this used to work, but recently there is now the problem that the already existing content of the `frontmatter.yaml` file is not rendered anymore in the Admin tab, and, if one is creating new entries via the form in the Admin panel, the content in the `frontmatter.yaml` file is replaced and the file always looks like this:
```yaml
"\0*\0items":
  gigs:
    -
      date: '2021-06-14 13:07'
      location: 'My Location'
      city: Berlin
      country: Germany
      link: null
      status: confirmed
"\0*\0nestedSeparator": .
``` 
I think the problem lies in the first and the last line. But I have no idea why they suddenly occur...
Any hints on what causes this behavior? And how can I solve it?

The blueprint looks like follows:
```yaml
title: Features
'@extends': default

form:
  fields:
    tabs:
      fields:
        features:
          ordering@: 1
          type: tab
          title: Gigs
          fields:
            header.gigs:
              name: gigs
              type: list
              label: Gigs
              collapsed: true

              fields:
                .date:
                  type: datetime
                  label: Date
                  placeholder: Select a date for the event
                  validate:
                    required: true
                .location:
                  type: text
                  label: Location
                  placeholder: Name of the location
                  validate:
                    required: true
                .city:
                  type: text
                  label: City
                  placeholder: Name of the city
                  validate:
                    required: true
                .country:
                  type: text
                  label: Country
                  placeholder: Name of the country (optional)
                .link:
                  type: url
                  label: Link
                  placeholder: https://www.yourlink.com/
                  help: add the link for the event, including the trailing 'https://'
                .status:
                  type: select
                  size: short
                  classes: fancy
                  label: Status
                  help: Select the status of the event (optional)
                  options:
                    confirmed: confirmed
                    pending: pending
                    canceled: canceled
```

Thanks a lot in advance! Any help is highly appreciated :-)
Cheers,
Markus
