### ISSUE TITLE
Adding a content type via media.yaml

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav#3394]
Have I done something wrong or is this some unreported regression?

I think I've followed directions in the docs for adding a CSV custom content type so that CSV files can be served from URLs with .csv extensions. Instead I see 404 pages. Both `.json` and `.txt` files at the same paths work fine. I am working around this by serving CSV as plain text and saving as CSV from the browser.

My `user/config/media.yaml`:

```yaml
types:

  csv:
    type: CSV
    thumb: media/thumb.png
    mime: text/csv
```
Template is serving valid CSV, Grav 1.7.15, let me know if I can provide anything else you need to reproduce.
