### ISSUE TITLE
Email contact form broken after update

### ISSUE THREAD

**Issue by Vip0r** [getgrav/grav#3406]
Hey all,

running this wonderful cms since quite a time with a modular page (livepage https://deinyogaflow.de) 

Unfortunately i recognized after some of the last updates the contact form i am using is no more working as expected. (now on grav v.1.7.17 with form and email plugin updated to the latest version i have the following behaviour:

The form itself could be filled, will be validated and the mail is sent to the configured destination. However, there is no redirect and the confirmation message as well is not shown.

my page consist of a main folder (home) with several subfolders containing modular pages. One of them is the folder "13._contact" containing a file contact.en.md.

With the following configuration the mail will be send but the user basically get no response

```
title: 'Contact'
form:
    action: /_contact
    name: kontakt-ajax-form
    refresh_prevention: true
    fields:
        name:
            label: Name
            placeholder: Name
            autofocus: 'off'
            autocomplete: 'on'
            type: text
            outerclasses: form-field
            classes: full-width
            validate:
                required: true
                message: 'Bitte gebe deinen Namen an'
        email:
            label: Email
            placeholder: E-Mail
            type: email
            outerclasses: form-field
            classes: full-width
            validate:
                required: true
                type: email
        subject:
            label: Betreff
            type: text
            placeholder: Betreff
            outerClasses: form-field
            classes: full-width
            validate:
                required: true
                message: 'Bitte gebe einen Betreff an'
        message:
            name: Message
            label: Nachricht
            placeholder: Nachricht
            type: textarea
            outerclasses: form-field
            classes: full-width
            rows: null
            validate:
                required: true
                message: 'Bitte gebe einen Nachricht an'
        veranstaltungen:
            label: false
            type: checkboxes
            options:
                option1: 'YOGA Summer Flow am Mittwoch (bitte Termine eintragen + Wunschuhrzeit für schlechtes Wetter)'
                option2: 'YOGA Natur FLOW am Samstag, 14.08.2021'
                option3: 'Ich möchte gerne eine Privatstunde vereinbaren'
                option4: 'YOGA FLOW Gutschein erwerben'
        g-recaptcha-response:
            label: Captcha
            type: captcha
            recaptcha_not_validated: 'Bitte fülle zuerst alle Pflichtfelder aus'
    buttons:
        submit:
            type: submit
            value: Senden
            outerclasses: form-field
            classes: 'full-width btn--primary'
    process:
        captcha: true
        email:
            subject: '[Neue Nachricht auf deinyogaflow.de von: ] {{ form.value.name|e }}'
            body: '{% include ''forms/data.html.twig'' %}'
```

If i add at the end an 

`redirect: /home`

then the page will reload after short time and the homepage get rendered in a wierd way below the contact form.

I went trough the docs which have explained contact forms on modular pages on a dedicated page 
(https://learn.getgrav.org/17/forms/forms/how-to-forms-in-modular-pages)

Sadly i didn't get it working. Are there any known issues with contact forms on the latest version? Kindly ask for help.
