### ISSUE TITLE
Forms add HTML tags

### ISSUE THREAD

**Issue by Deight8** [getgrav/grav#3417]
I try to find solution, 2 hr in documentation here a try to find it, but nothing.

Pls guys how i can to put html tag inside the "Frontmatter"?

I have This for example:
```
title: Reklamace
form:
    name: reklamace
    fields:
        name:
            label: 'Celé jméno'
            type: text
            autofocus: 'on'
            validate:
                required: true
            autocomplete: 'on'
        company:
            label: Firma
            type: text
            validate: null
            autocomplete: 'on'
....
```

And i need this: 
```
title: Reklamace
form:
    name: reklamace
    fields:


        h2
            text: 'H1 TEXT'


        name:
            label: 'Celé jméno'
            type: text
            autofocus: 'on'
            validate:
                required: true
            autocomplete: 'on'
        company:
            label: Firma
            type: text
            validate: null
            autocomplete: 'on'
```

How can i made this pls?

Thx all!
