### ISSUE TITLE
Collection ordering ignored in the column-based Flex Pages UI

### ISSUE THREAD

**Issue by parcand** [getgrav/grav#3441]
It appears that the `children_display_order: collection` setting is being ignored in the column-based Flex Pages UI.

```
admin:
    children_display_order: collection
content:
    items: '@self.children'
    order:
        by: date
        dir: desc
```
![collection-sorted-by-date](https://user-images.githubusercontent.com/22176950/133341004-fb97ded4-04be-4510-baf8-9b418d2461ee.png)
![pages-sorted-alphabetically](https://user-images.githubusercontent.com/22176950/133341001-3fc4a19c-d078-4d59-9b44-5a50832484a9.png)

**Affected version**
Grav 1.7.21
Admin 1.10.21

**Related issue:**
https://github.com/getgrav/grav/issues/2881
