### ISSUE TITLE
Filepicker Custom-Streams, ignores extra locations

### ISSUE THREAD

**Issue by Diggen85** [getgrav/grav#3485]
Hi,

when defining a custom Stream with multiple locations (like in the example https://learn.getgrav.org/17/advanced/multisite-setup) the Filepicker just shows Files from the first location.
The Example below shows Images from theme://images in the Filepicker. Swaping the locations leads to just show Images from user://images

**streams.yaml**
```
schemes:
  mdl:
    type: Stream
    prefixes:
      'images': ['theme://images','user://images']

```
**blueprint**
```
       fields:
          head.logo:
            type: filepicker
            folder: 'mdl://images/'
            label: Page Logo
            preview_images: true
            accept:
              - .png
              - .jpg
```
