### ISSUE TITLE
Checkboxes validation bug

### ISSUE THREAD

**Issue by IamSAB** [getgrav/grav#3521]
The checkboxes field only is valid when all options are checked. Selecting only some or no options will render it invalid and the form won't submit.

```yaml
hobbies:
  type: checkboxes
  label: Hobbies
  options:
    soccer: Soccer
    rugby: Rugby
    biking: biking
   swimming: Swimming
```
As you see, there is any validation defined, the field is not even required. Is that a known bug?

_I use that field type inside a flex form in the admin backend,_
