### ISSUE TITLE
Custom menu not working when running in Modular mode.

### ISSUE THREAD

**Issue by stianmathisen** [getgrav/grav#3522]
_I'm trying to utilize Modular in my home page to have an easy way to structure content when people visits my domain.com. 
I don't want the navbar to have the modules, instead, I want to use the nav bar for more in-depth pages since the modules in the home page only touches each section briefly._ 

_Since only modules show up in navbar when running in modular structure, I have disabled them so they do not show up in the navbar, and I'm trying to adjust the navbar myself using the site.yml's "menu" feature._

_I have set the menu in site.yml like this:_
```
menu:
    - text: Home
      url: https://domain.com
    - text: Vision
      url: https://domain.com/vision
    - icon: Products
      url: https://domain.com/products
```

_When I make home page Default instead of Modular, Home, Vision and Products is visible and clickable. When I switch the page back to Modular, Products disappear and everything else in the menu turns unclickable._ 

**Versions:**
Grav: Grav v1.7.27.1 - Admin v1.10.26.1
Themes: Latest version of Quark and Antimatter.
Webserver: Litespeed
PHP: 8

I been at this for weeks, and been struggling with it. There is a big chance I'm just stupid and the problem is PEBCAC, but any input on this would be greatly appreciated.

Thank you for developing this amazing tool, I love utilizing GravCMS for my projects.
