### ISSUE TITLE
Debugger line in FlexCollection/FlexObject breaks any non html output

### ISSUE THREAD

**Issue by ricardo118** [getgrav/grav#3538]
system/src/Grav/Framework/Flex/FlexCollection.php
```
if ($debugger->enabled()) {
    $output = "\n<!–– START {$type} collection ––>\n{$output}\n<!–– END {$type} collection ––>\n";
}
```

This line should not be changing the output, rather should be in the debugger itself like clockwork. Any output that is non html breaks with this line,

Personally think that it should jsut output to the debugger itself, rather than the body/content or have an extra option to toggle the line on/off

**Comment by ricardo118** [comment]
```
debugger:
  enabled: false
  provider: clockwork
  censored: false
  flex_output: false                         # <--- something like this?
  shutdown:
    close_connection: true 
```
