### ISSUE TITLE
Typhoon Theme Extending

### ISSUE THREAD

**Issue by Eggeriley** [getgrav/grav#3549]
I am getting an error message when I switch over to the new theme I created which is a direct copy of the typhoon theme. I used the devtools plugin and followed all steps in this article: https://getgrav.org/premium/typhoon/docs
```
**/Users/Rileyegge_1/Documents/CodeProjects/access-grav/user/plugins/color-tools/vendor/mexitek/phpcolors/src/Mexitek/PHPColors/Color.php**

```
    private $_hsl;
 
    /**
     * @var array
     */
    private $_rgb;
 
    /**
     * Auto darkens/lightens by 10% for sexily-subtle gradients.
     * Set this to FALSE to adjust automatic shade to be between given color
     * and black (for darken) or white (for lighten)
     */
    public const DEFAULT_ADJUST = 10;
 
    /**
     * Instantiates the class with a HEX value
     * @param string $hex
     * @throws Exception
     */
    public function __construct(string $hex)
    {
        $color = self::sanitizeHex($hex);
        $this->_hex = $color;
        $this->_hsl = self::hexToHsl($color);
        $this->_rgb = self::hexToRgb($color);
    }
 
    /**
     * Given a HEX string returns a HSL array equivalent.
     * @param string $color
     * @return array HSL associative array
     * @throws Exception
     */
    public static function hexToHsl(string $color): array
    {
        // Sanity check
        $color = self::sanitizeHex($color);
 
        // Convert HEX to DEC
        $R = hexdec($color[0] . $color[1]);
```

Arguments

1. "Mexitek\PHPColors\Color::__construct(): Argument #1 ($hex) must be of type string, null given, called in /Users/Rileyegge_1/Documents/CodeProjects/access-grav/u ▶"

I am getting this color helper PHP function issue when I try to use a new copied theme of typhoon. 
```

**Comment by YenLung-Huang** [comment]
I had same problem. I fixed this with replace the content under the streams section in your [inherit-typhoon].yml from all content in typhoon.yml.

```yaml
streams:
 schemes:                                                                                                        
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - 'user://themes/inherit-typhoon'
         - 'user://themes/typhoon'
         
# !!!!!! Replace all of this with original content from typhoon.yml
enabled: true                                                       # Enable the theme
external_in_new_tab: false                                          # Open external URLs in new tab

```

The problem is dev-tools working incorrect.

https://github.com/getgrav/grav-premium-issues/issues/50
