### ISSUE TITLE
Theme language files not working

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#357]
Themes `languages.yaml` files are not loaded.
From [`Themes.php`](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Themes.php#L233) I guess some prefixes in theme configuration are needed
```php
$schemes = array_reverse($config->get("themes.{$name}.streams.schemes.theme.prefixes.", []));
```
but in the theme configuration there are only paths 
```yaml
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      paths:
        - ...
```
Maybe it shoud be `$config->get("themes.{$name}.streams.schemes.theme.paths", [])` instead, or where to put these prefixes and what they should contain?
