### ISSUE TITLE
Feature Request: Add FLAC and AAC as media types

### ISSUE THREAD

**Issue by suterma** [getgrav/grav#3580]
In config/media, many file types are included by default, including audio files, like e.g. MP3. I suggest that you also add FLAC and AAC files there since these are also popular file types.

**Comment by suterma** [comment]
Additionally, I suggest that these are also added in the media player handler mentioned here: https://learn.getgrav.org/17/content/media#audio-actions

Currently, these files do not produce an audio element, even when added to the configuration media.

**Comment by pmoreno-rodriguez** [comment]
Hi @suterma 
In fact Grav has support for those types of audio files, you just have to add the extensions in config/media.yaml, as follows:

```
flac:
     type: audio
     thumb: media/thumb-fla.png
     mime: audio/flac
     image:null
   aac:
     type: audio
     thumb: media/thumb-aac.png
     mime: audio/aac
     image:null
```

Then on your page load the audio files and call them from the page editor. Here I show you a screenshot (and I can assure you that the audio plays)
```
flac sample

![sample3.flac](sample3.flac)

AAC samples

![sample3.flac](sample3.aac)
```
![flac_aac_grav](https://github.com/getgrav/grav/assets/60596353/715b4137-4f0a-4c49-bba4-3b0a041e4801)
