### ISSUE TITLE
Extra `.md` inserted in filename when creating a new page in admin panel

### ISSUE THREAD

**Issue by kees-closed** [getgrav/grav#3582]
Running version: v1.7.33 on PHP 7.4

When creating a new page in the admin panel, the software creates the wrong file.
It inserts an extra `.md` in the file, this is then corrected with `mv item.md.nl.md item.nl.md`.
This bug is triggered since 1.7.33 (as far as I'm aware of).

**Comment by mahagr** [comment]
I'm not able to reproduce the issue. Can you paste your language settings from the `system.yaml` file?

**Comment by kees-closed** [comment]
```
$ grep lang system.yaml 
languages:
  default_lang: nl
  include_default_lang: false
  include_default_lang_file_extension: true
  http_accept_language: false
```

**Comment by pamtbaau** [comment]
Seems someone else has also bumped into this or similar issue. See Discord https://discourse.getgrav.org/t/weird-md-naming-after-enabling-language-support/20683

**Comment by mahagr** [comment]
@kees-closed Can you paste the full language configuration, not just the ones including lang?

Unfortunately, I need to reproduce this one myself to be able to figure out where, when, and why it happens.

**Comment by kees-closed** [comment]
```
languages:
  supported:
    - nl
  default_lang: nl
  include_default_lang: false
  include_default_lang_file_extension: true
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: true
  pages_fallback_only: false
```
