### ISSUE TITLE
page media resize with a value from page header doesn't seem to work

### ISSUE THREAD

**Issue by spamhater-grav** [getgrav/grav#3590]
Been trying to pass a page.header value to a page.media resize command and have unexpected results and wonder if it is a bug or there is a correct way of passing it 

if I do this 
```
{% for key, item in page.header.intro %}
  {{dump(evaluate_twig(page.media[item.image].resize(50,50))) }}
{% endfor %}
```

it creates a reduced size image of the correct dimensions  in the cache as expected
but if I do 

```
{% for key, item in page.header.intro %}
  {{dump(evaluate_twig(page.media[item.image].resize(item.imagesize))) }}
{% endfor %}
```

all I get is the original image.

Is there a certain way I need to format / to pass the size from the page header imagesize ( I understand from an error it is expecting a int / string ) but cant figure why it isn't passing correctly. Is it I just need to evaluate / filter the string ?

```
---
title: intro
intro:
  - image: wedding-catering-nottingham.jpg
    offset: 'x=25 y=50'
    imagesize: 10,10
    
  - image: hot-buffet-catering.jpg
    offset: 'x=-25 y=0'
    imagesize: 150,150
    
  - image: wedding-catering-nottingham.jpg
    header: Cold Buffets
    text: something about disasters
    url:
---
```
 **I have tried alternatives like '150,150' and '150, 150'** 
 
 Wonder if @mahagr will have the answer straight away, with you currently working on the media stuff.. Thank you
