### ISSUE TITLE
Flex Object CSV storage doesn't work (Grav\Framework\File\Formatter\CsvFormatter)

### ISSUE THREAD

**Issue by LuanHimmlisch** [getgrav/grav#3593]
Using the class `Grav\Framework\File\Formatter\CsvFormatter` throws an error.

![CSV Error Grav CMS](https://user-images.githubusercontent.com/46875694/171965390-d48803cf-9cb8-4d2c-9ed8-100280d5a3fa.png)

Even after adding the media types on the `system.yaml` and `mime.yaml`, since it seems the errors comes from a hard-coded part of the parent class of the SimpleStorage.

![Parent class SimpleStorage causing errors](https://user-images.githubusercontent.com/46875694/171965434-775c95b3-2908-4f29-8ceb-4f7d371e4457.png)

The export of CSV however, works.

The code I'm using for storage is straight out of the documentation:

```yaml
config:
  data:
    storage:
      class: 'Grav\Framework\Flex\Storage\SimpleStorage'
      options:
        folder: user-data://flex-objects/stores.csv
        formatter:
          class: 'Grav\Framework\File\Formatter\CsvFormatter'
          options:
            file_extension: [".csv", ".tsv"]
            delimiter: "," # Delimiter to separate the values
            mime: "text/x-csv" # MIME type for downloading file
```
