### ISSUE TITLE
pagemediaselect with multiple in list resets value to null on save

### ISSUE THREAD

**Issue by cyanonoob** [getgrav/grav#3687]
I have a pagemediaselect in a list:

```
form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.columns:
              name: columns
              type: list
              style: vertical
              label: Kolommen
              fields:
                .images:
                  type: pagemediaselect
                  label: Slider-afbeeldingen
                  multiple: true
```

When I manually edit my markdown frontmatter, this works fine. However, if I save through grav, the images field is reset to null every time. Is there a fix for this?

**Comment by mdestafadilah** [comment]
```yaml
.images:
 type: pagemediaselect
 label: Slider-afbeeldingen
 multiple: true
```

just more space with tabs not spacing.

![test](https://github.com/getgrav/grav/assets/5575882/f48f0ab1-45df-439a-ba16-30287e501e08)

enjoy!
