### ISSUE TITLE
Make getMimeType function configurable

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#369]
I suggest to create some configuration for mime types.
For example, add something like this
```yaml
mimetypes:
  - mimetype: 'image/jpg'
    extensions: [jpeg, jpg, jpe]
  - mimetype: 'image/svg+xml'
    extensions: [svg]
```
into `system.yaml` or into separate `mimetypes.yaml` configuration file.

Then add something like this
```php
$mimetypes = self::getGrav()['config']->get('mimetypes.mimetypes', []);

foreach ($mimetypes as $mimetype) {
    if (in_array($extension, $mimetype['extensions'])) {
        return $mimetype['mimetype'];
    }
}
```
into the `getMimeType` function in the `Utils.php`.

In that way it will be possible to add some extensions/mime types/content types without altering source code. So if it is needed to add `xlsx`, `pptx`, or some other extension or content type it could be done it the configuration file inside `user/config` folder.
