### ISSUE TITLE
Blueprint field of type: pages ignores multilingual route

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav#3690]
I have a bilingual site, EN/FR;  v1.7.37.1 (Admin v1.10.37.1). On that site, I have an FR page with the following frontmatter:

```
title: 'Signature Optica - Notre silence fait beaucoup de bruit'
published: true
routes:
    default: /nouvelles/signature-optica
    canonical: /nouvelles/signature-optica
```

I can browse to `/fr/nouvelles/signature-optica` and it displays as expected.

Next, I have a custom blueprint page with a `type: pages` field:

```
                    .buttonpagelink:
                      type: pages
                      size: medium
                      label: 'Choose a Web page on this site'
                      show_modular: false
                      show_root: true
```

When in the Admin, with FR selected, I choose the FR page `Signature Optica - Notre silence fait beaucoup de bruit` in the pick list:

![image](https://user-images.githubusercontent.com/998832/220654814-ef9baeb5-e8a2-4e1b-8f7e-2c9463e73d72.png)

I expected the resulting link to be `/fr/nouvelles/signature-optica`, but instead it applied the corresponding `news/signature-optica-silence-making-big-noise` EN path. Here's the frontmatter for the saved page:

```
       itembuttons:
            -
                buttonlabel: RENSEIGNEZ-VOUS
                buttonicon: null
                buttoniconloc: null
                buttonlink: null
                buttonpagelink: /news/signature-optica-silence-making-big-noise
                buttonweblink: null
                buttonclass: button
                buttontarget: _self
```
