### ISSUE TITLE
Float numbers in text form field validation doesn't work if used with max directive

### ISSUE THREAD

**Issue by ViliusS** [getgrav/grav#3732]
Let's say in the blueprint I want to have a text field with input value for float. If max validation directive for that field is specified, you cannot input float numbers via Grav Admin UI.

Blueprint example which doesn't work:
```
myoption:
  type: text
  size: x-small
  label: "some label"
  validate:
    type: number
    min: 0
    max: 1
```

Blueprint example which does work:
```
myoption:
  type: text
  size: x-small
  label: "some label"
  validate:
    type: number
    min: 0
```

Looks like some kind of JavaScript bug in validation code.

P.S. I cannot use number field type either, because then HTML5 input validation blocks anything that is not integer completely.
