### ISSUE TITLE
Filepicker: broken previews when streams are used

### ISSUE THREAD

**Issue by u07** [getgrav/grav#3767]
As [the docs say](https://learn.getgrav.org/17/forms/blueprints/fields-available#filepicker-field), we can use theme:// in filepicker. But it does not work as intended.

![image](https://github.com/getgrav/grav/assets/20968145/90dd3cbd-cb20-4b9b-8067-4c9b90914ec0)
![image](https://github.com/getgrav/grav/assets/20968145/36a0c7ab-b16d-4069-9bf3-a8d83256e76b)
![image](https://github.com/getgrav/grav/assets/20968145/7ecf5be2-34f5-4da0-9dfe-cee74fde8874)
![image](https://github.com/getgrav/grav/assets/20968145/c5224662-52d8-48da-b7b1-05f10af4cd49)

**Comment by pamtbaau** [comment]
@u07, Please do not use images to explain an issue (see [Stackoverflow](https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors) for reasons) and preferably provide:
- a verbal explanation of the problem. _"But it does not work as intended."_ does not quite describe the problem.
- a short reproducible case showing the issue

Using a fresh install of Grav+Admin v1.7.43, I do not find anything that is "not working as intended".

My setup:
- Fresh install of latest Grav+Admin v1.7.43
- Added a filepicker field to blueprint */user/themes/quark/blueprints/default.yaml*
  ```
  header.picked_image:
    type: filepicker
    folder: 'theme://images'
    label: Select a file
    preview_images: true
    accept:
      - .png
      - .jpg
  ```
- Added extra image *windows background.jpg* to folder */user/themes/quark/images*
- Admin shows the following field:
  ![image](https://github.com/getgrav/grav/assets/5120011/dad8e3b0-a60f-4301-9055-18871a01e674)
- When picking a file and saving the page, the frontmatter of the page looks as follows:
  ```
  ---
  title: Typography
  picked_image: 'windows background.jpg'
  ---
  ```

**Comment by pamtbaau** [comment]
@u07, Can't reproduce the issue either using flex-objects...

My setup:
- Fresh install of latest Grav+Admin v1.7.43
- In Admin edit config of plugin Flex-Objects and enable 'Contact' directory
- Copied folder */user/plugins/flex-objects/data/flex-objects* to folder */user/data*
- Copied file */user/plugins/flex-objects/blueprints/flex-objects/contacts.yaml* to */user/blueprints/flex-objects/contacts.yaml*
- Added a filepicker field to form section in blueprint */user/blueprints/flex-objects/contacts.yaml*
  ```
  picked_image:
    type: filepicker
    folder: 'theme://images'
    label: Select a file
    preview_images: true
    accept:
      - .png
      - .jpg
  ```
- Added extra image *windows background.jpg* to folder */user/themes/quark/images*
- Admin shows the following field when editing a Contact flex-object
  ![image](https://github.com/getgrav/grav/assets/5120011/02401086-ca3a-4b5e-b7d8-e0d80f21cbbc)
- When picking a file and saving the contact, the contact in */user/data/flex-objects/contacts.json* looks as follows:
  ```
    "gizwsvkyo5xtms2s": {
        "published": true,
        "first_name": "David",
        "last_name": "Tucker",
        "email": "dtucker0@tripod.com",
        "website": "http:\/\/flavors.me",
        "tags": [
            "Puce",
            "Teal"
        ],
        "picked_image": "windows background.jpg"
    },
  ```
