### ISSUE TITLE
[BugReport] Session cookie naming, failure to add __Secure- prefix

### ISSUE THREAD

**Issue by Pancake11** [getgrav/grav#3773]
Hi, I'm currently trying to set my session cookie to follow the MDN recommendation by adding the prefix `__Secure-` to my session cookie.

By putting `__Secure-session_cookie` in the session.name field of the `user/config/system.yaml` i get the following cookie name in my responses from the website `secure-session-cookie`, it seems that grav trims the leading underscores and puts everything in lowercase.

This issue appears with localhost and on a nginx hosted server.

yaml: 
```yaml
session:
  enabled: true
  initialize: true
  timeout: 1800
  name: __Secure-session-cookie
  uniqueness: path
  secure: true
  secure_https: true
  httponly: true
  samesite: Lax
  split: true
  domain: null
  path: null
```

result in website:
![image](https://github.com/getgrav/grav/assets/59865749/b62bcae3-e0f2-4660-90d4-950e476caf05)

This appears using Microsoft Edge browser or by using wget.

Grav version: 1.7.43
Php version: 8.1.2

MDN link: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#cookie_prefixes
