### ISSUE TITLE
problem with blog type items ordering option

### ISSUE THREAD

**Issue by simogeo** [getgrav/grav#3803]
Hi, 

I have the following configuration in my blog.md file : 

```
---
title: 'Les actualités'
blog_url: actualites
menu: Actualités
body_classes: 'header-lite fullwidth blogstyling'
bg_color: '#E85C5C'
slug: actualites
sitemap:
    changefreq: monthly
content:
    items: '@self.children'
    order:
        by: date
        dir: desc
    limit: '15'
    pagination: '1'
feed:
    description: 'Les actualités de la Fondation Geomanum'
    limit: 10
metadata:
    description: 'Suivre l''actualité de la Fondation Geomanum'
pagination: '1'
cache_enable: false
child_type: default
process:
    markdown: true
    twig: false
robots: index
    
---
```

But the order parameter is not working and the limit / pagination neither ... any Clue ?

See online : https://geomanum.org/fr/actualites

Thanks for your support

**Comment by pmoreno-rodriguez** [comment]
Hi.
What theme are you using?

**Comment by simogeo** [comment]
Hi, I use hydrogen theme

**Comment by simogeo** [comment]
I did not add anything myself, so I guess !

**Comment by simogeo** [comment]
![image](https://github.com/getgrav/grav/assets/154323/412db721-27dc-4651-bbf8-1c3545755ab6)

**Comment by simogeo** [comment]
yes, actually, I use blog 

I always edit manually files ... and doing it through the UI generates a big mess. I don't use blog-item neither particle, I use "blog". Forget my screenshot - sorry.

**Comment by pmoreno-rodriguez** [comment]
I have tested on a local page based on Gantry and Hydrogen and my blog page works as it should, that is:
- In the blog with descending date order, the most recent pages would be the first to be displayed.
- In the blog with ascending order, it would be the opposite.

I can only think of clearing the cache or clearing the temporary files of your browser, because it seems to work fine.

This is my blog.md:
```
---
title: 'Blog Page'
blog_url: blog
sitemap:
    changefreq: monthly
    priority: 1.03
content:
    items:
        - '@self.children'
    order:
        by: date
        dir: desc
    limit: 5
    pagination: true
    show_date: true
    leading: 0
    columns: 2
    url_taxonomy_filters: true
feed:
    description: 'Sample Blog Description'
    limit: 10
pagination: true
---
```

**Comment by simogeo** [comment]
It should behave as described but it does not. 

Can you sow me your date format ?

**Comment by pmoreno-rodriguez** [comment]
> It should behave as described but it does not.
> 
> Can you show me your date format ?

This is my date config in system.yaml:
```
dateformat:
    default: null
    short: 'jS M Y'
    long: 'F jS \a\t g:ia'
```
By default Gantry uses `{{ page.date|date(config.system.pages.dateformat.default) }}` in partials\blog_item.html.twig`.

There's something I don't understand yet. In Gantry the blog template does not exist, instead blog_list exists. Therefore, I don't understand how you have a `blog.md` file instead of a `blog_list.md`.
