### ISSUE TITLE
blueprint: add admin-field for type only

### ISSUE THREAD

**Issue by domhaas** [getgrav/grav#3875]
Hey,
is it possible to add a custom field like:
```
form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT
          fields:
            header.lexicon_term:
              type: text
              label: Lexicon Term
              placeholder: Enter Lexicon-Text
```

to only to one page-type, like for example blog-item?
