### ISSUE TITLE
*onFormProcessed* will not be triggered without *process* has at least one item

### ISSUE THREAD

**Issue by snailcatcher** [getgrav/grav#3879]
Hi there,
I have struggled a lot with implementing my own plugin for grav.
One issue which I really slowed me down, was that *onFormProcessed* is not processed at all, if there isn't at least one item in the *process* array of the form definition.

This is the code I use in the plugin implementation
```yaml
public static function getSubscribedEvents(): array
{
    return [
        ...
        'onFormProcessed'      => ['onFormProcessed', 0],
        ...
    ];
}

public function onFormProcessed(Event $event): void
{
    $form = $event['form'];
    $form->validate();

    /** @var Data $form_data */
    $form_data = $form->getData();
    $rep = print_r($form_data, true);
    print_r('<br /><br /><br /><br /><pre>' . htmlentities(string: $rep) . '</pre>');
}
```

If I use my form like this it works as expected (*onFormProcessed* is called and the values are printed):
```yaml
---
title: qwertz
expires: 0
cache_enable: false
access:
  admin.login: false

forms:
  orderform:
    method: POST

    fields:
      personal:
        type: fieldset
        title: abcdef
        fields:
          lalalala:
            type: text
            autofocus: true
            validate:
              required: true
    buttons:
      submit:
        type: submit
        value: abc

    process: # mandatory when using "onFormProcessed" 
      message: ABCD
```

If I uncomment *process:* completely or just *message: ABCD* or write *process: true*, it doesn't work as expected (*onFormProcessed* is **not** called and therefore the values are **not** printed)

I personally think this cloud be a bug, because I did not find anything in the docs about it and it doesn't feel right to call a unrelated method just to call my *onFormProcessed* handler.

Thanks for the great project btw!

Sincerly snailcatcher
