### ISSUE TITLE
Dump is not working for me in Twig files

### ISSUE THREAD

**Issue by kellyjoe256** [getgrav/grav#3892]
Hello,

At my workplace, we currently use WordPress, but I was told by my boss to look at alternatives that we can explore.

I am currently following the documentation for the latest grav, and I am liking it at the moment.

The issue I am currently facing is the twig dump (I am using it in the file `default.html.twig`) is not working for whatever reason

```twig
{% extends 'partials/base.html.twig' %}

{% block content %}
    <pre>{{ dump(page) }}</pre>
    {{ page.content|raw }}
{% endblock %}
```

I have enabled all the necessary settings in `system.yaml` as shown below

```yaml
# ...
twig:
  cache: true 
  debug: true
  auto_reload: true
  autoescape: true
  undefined_functions: false
  undefined_filters: false
  safe_functions: []
  safe_filters: [] filters
  umask_fix: false
# ...
debugger:
  enabled: true
  provider: debugbar
  censored: false
  shutdown:
    close_connection: true
```

GRAV VERSION
```bash
Grav CLI Application 1.7.48
```

Thanks
