### ISSUE TITLE
Submenus possible?

### ISSUE THREAD

**Issue by visioncode** [getgrav/grav#39]
There is no word about submenus - are they possible with the current code?

**Comment by spikerola** [comment]
The page has been remove, where could I find it now?

**Comment by flaviocopes** [comment]
I think it got removed since dropdown menus are currently implemented in themes, Antimatter and other ones as well. 

E.g. https://github.com/getgrav/grav-theme-antimatter#dropdown-menu

**Comment by cocodrino** [comment]
would be great could create custom menus like this

```yaml

menu:
    - text: menu
      url: https://github.com/getgrav/grav
       - icon: submenu here
         url: http://twitter.com/getgrav

```

is there any way for achieve this? thanks
