### ISSUE TITLE
Email Plugin Does Not Accept RFC 5322 Mailbox Format in site.yaml

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav#3905]
With the RFC 5322 standard mailbox `John Doe <john@example.com>` address stored in site.yaml as follows:

```
form_email:
    myaddress: "John Doe <john@example.com>"
```

And the form configured as follows:

```
email:
        -
            subject: '[Contact] from {{ form.value.name|e }}'
            body: '{% include ''forms/data.html.twig'' %}'
            to: '{{ config.site.form_email.myaddress|e }}'
            to_name: 'Contact'
            reply_to: '{{ form.value.email|e }}'
```

The email is not sent. If I modify the mailbox address to just `john@example.com>` like so:

```
form_email:
    myaddress: john@example.com
```

The email is sent.

Note that the form submission is being processed asynchronously with the following:

```
<script>
$(document).ready(function(){

    var form = $('#contact-form'); 
    form.submit(function(e) {
        // prevent form submission
        e.preventDefault();
        
        // Start spinner here?
        document.getElementById('contact-spinner').setAttribute('class', 'visible');

        // submit the form via Ajax
        $.ajax({
            url: form.attr('action'),
            type: form.attr('method'),
            dataType: 'html',
            data: form.serialize(),
            success: function(result) {
                // Inject the result in the HTML
                $('#form-result').html(result);
            }
        });
       
        // scroll to message region
        document.getElementById('myIdLocation').scrollIntoView({
          behavior: 'smooth'
        });
    });
});
</script>
```
