### ISSUE TITLE
file loading for pages with prefix number was broken with latest update

### ISSUE THREAD

**Issue by ichik** [getgrav/grav#457]
I use custom CSS loading for some pages like this:
```
{% if page.header.customcss %}
{% do assets.add('/user/pages' ~ page.url() ~ '/custom.css',10,false) %}
{% endif %}
```

It worked previously for pages with numbers in folder name previously, but now it returns 404.

e.g.: http://sqncbrk.com/user/pages/metroidvanias/custom.css but http://sqncbrk.com/user/pages/02.metroidvanias/custom.css

What gives? Is there a way to request page slug with number?

**Comment by ichik** [comment]
I've created duplicating folder for now, so you won't get 404 I guess.

**Comment by rhukster** [comment]
What version are you running?

**Comment by ichik** [comment]
Hm, nope, that didn't work.

**Comment by ichik** [comment]
For reference part of system.yaml:
```
pages:
  theme: GrvSqncBrk
  markdown_extra: true
  process:
    markdown: true
    twig: true
  redirect_default_route: true
  fallback_types: [css,png,jpg,gif]
```
