### ISSUE TITLE
Add support for 7z as standard media type

### ISSUE THREAD

**Issue by acki-m** [getgrav/grav#521]
So i don't have to create a special media config.
Please also add a corresponding thumbnail for it.
```
7z:
  type: file
  thumb: media/thumb-7zip.png
  mime: application/x-7z-compressed
```
