### ISSUE TITLE
Field Descriptions in Blueprints

### ISSUE THREAD

**Issue by ellioseven** [getgrav/grav#611]
I'm not sure if I am missing something here as I am only just starting to get into Grav (really like it so far) and Grav Admin, but I am looking to create field descriptions in my blueprints, eg:

```
fields:
  my_field:
    type: text
    label: 'My Field'
    description: 'This is my description for my field.'
```

Does this feature exist? I feel like this is quite important.
