### ISSUE TITLE
Blueprints Type of List inside Type of List (Not Working)

### ISSUE THREAD

**Issue by sturple** [getgrav/grav#619]
I thought i would add this to Issues, as either a future enhancement or a bug fix.  
I am trying to add a List type inside a List type
```yaml
testimonials:
  type: section
  underline: true
  title: Testimonials
  fields:              
    header.testimonial:                 
      type: list
      label: Testimonial
      name: testimonials
      fields: 
        .title:
          type: text
          name: title2
          label: Name
        .content:
          type: textarea
          name: testimonial
          label: Testimonial
        .soundbite:
          type: list
          label: Soundbite
          name: soundbite
          fields:
            .item:
              type: text
              name: soundbiteItem
              label: Soundbite
```
Thanks,
Shawn
