### ISSUE TITLE
Blueprints "ignore" field removes tab options but not the tab itself

### ISSUE THREAD

**Issue by benblee** [getgrav/grav#620]
Inheriting the "default" blueprint, but wanting to ignore a tab in it. This is a modular template blueprint.

Using ignore in the following code removes the options (content) in the tab, but does not remove the tab itself:

```
title: Showcase
@extends: default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    name:
                      default: modular/showcase
                      @data-options: '\Grav\Common\Page\Pages::modularTypes'
            overrides:
              fields:
                header.template:
                  default: modular/showcase
                  @data-options: '\Grav\Common\Page\Pages::modularTypes'

        styles:
          type: tab
          title: Row Style
          fields:
            header.styles:
              type: textarea
              label: CSS Classes

        foundation:
          type: ignore

```

The Gitter conversation is here:
https://gitter.im/getgrav/grav?at=56a0614928b4586d1c8de357

The Grav Docs are here:
http://learn.getgrav.org/advanced/blueprints#special-form-fields-available-only-in-admin

This is using the Bones Site Skeleton on the "/modular/showcase.yaml" blueprint for testing:
https://github.com/smartgravity/grav-skeleton-bones-site/releases
