### ISSUE TITLE
Switching languages with Cache enabled doesn't work

### ISSUE THREAD

**Issue by iforwms** [getgrav/grav#655]
My desired set up is that no language information is stored in the session, it's purely done via the URL (using the grav-langswitcher plugin). But this doesn't seem to work with the global cache turned on. Have I incorrectly set up Grav or is this a bug? Here's my user/config/system.yaml fro reference:

```yaml
absolute_urls: false
timezone: Asia/Shanghai
param_sep: ':'
wrapped_site: false
languages:
  supported:
    - en
    - zh
  include_default_lang: true
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
home:
  alias: /home
  hide_in_urls: false
pages:
  theme: custom-theme
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    short: 'jS M Y'
    long: 'D, d M Y G:i:s'
  publish_dates: true
  process:
    markdown: true
    twig: false
  twig_first: false
  events:
    page: true
    twig: true
  markdown:
    extra: false
    auto_line_breaks: false
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  types:
    - txt
    - xml
    - html
    - htm
    - json
    - rss
    - atom
  expires: 604800
  last_modified: true
  etag: true
  vary_accept_encoding: true
  redirect_default_route: false
  redirect_default_code: '301'
  redirect_trailing_slash: true
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
  markdown_extra: true
cache:
  enabled: true # Disabling this option fixes the language switching problem.
  check:
    method: file
  driver: auto
  prefix: g
  lifetime: 604800
  gzip: true
twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false
  undefined_functions: true
  undefined_filters: true
  umask_fix: true
assets:
  css_pipeline: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: true
  js_minify: true
  enable_asset_timestamp: true
  collections:
    jquery: 'system://assets/jquery/jquery-2.1.4.min.js'
errors:
  display: false
  log: true
debugger:
  enabled: false
  shutdown:
    close_connection: true
  twig: true
images:
  default_image_quality: 80
  cache_all: false
  cache_perms: '0755'
  debug: false
media:
  enable_media_timestamp: true
  upload_limit: 0
session:
  enabled: true
  timeout: 1800
  name: custom_session_name
  secure: false
  httponly: true
supported:
  - en
  - zh
http_accept_language: true
home_redirect:
  include_lang: true
  include_route: false
session_store_active: true
```

**Comment by flaviocopes** [comment]
Cannot recreate it on the clean "MultiLang" skeleton.

Can you check your config on that skeleton, so we test on the same base? https://getgrav.org/downloads/skeletons

P.S. unrelated to the problem, but the last part of your system config shouldn't be there.

```
supported:
  - en
  - zh
http_accept_language: true
home_redirect:
  include_lang: true
  include_route: false
session_store_active: true
```
