### ISSUE TITLE
Metatag's outputting name via the metadata.html.twig partial

### ISSUE THREAD

**Issue by stephenvoisey** [getgrav/grav#700]
I was asked by Flaviocopes to add this as an issue and he has also made this suggested commit:

https://github.com/getgrav/grav/pull/699/files

It sort of follows on from the excellent feedback regarding the meta tags and the way Grav is handling them internally and the way the twig template can help extract this data from the header and site.yaml file in a consistent manner.

While it is perfectly reasonable to expect to add this stuff in the twig template, because Grav is offering a more dynamic solution, once I dug into the partial code, it made no sense to me as it included calls about http_equiv and charset as if statements, but didn't seem to act upon this or out anything differently if I added these to the metadata.

```
{% for meta in page.metadata %}
<meta {% if meta.name %}name="{{ meta.name }}" {% endif %}{% if meta.http_equiv %}http-equiv="{{ meta.http_equiv }}" {% endif %}{% if meta.charset %}charset="{{ meta.charset }}" {% endif %}{% if meta.property %}property="{{ meta.property }}" {% endif %}{% if meta.content %}content="{{ meta.content }}" {% endif %}/>
{% endfor %}
```
With site.yaml meta data set as:

```
metadata:
  generator: 'GravCMS'
  charset: 'utf-8'
  http_equiv: 'x-ua-compatible'
  description: 'Page description'
```

Resulted in HTTP out of:

```
<meta name="generator" content="GravCMS" />
<meta name="charset" content="utf-8" />
<meta name="http_equiv" content="x-ua-compatible" />
<meta name="description" content="Page description" />
```

Both the charset and http_equiv should appear in the meta tag as properties in themselves, not as name properties, and without the content property.

So I tweaked the antimatter metadata partial to make sure the output was corrected and still worked with page or site data nicely.

```
{% for meta in page.metadata %}
<meta {% if meta.name == 'http_equiv' %}http-equiv="{{ meta.content }}"{% elseif meta.name == 'charset' %}charset="{{ meta.content }}"{% else %}name="{{ meta.name }}"{% if meta.property %} property="{{ meta.property }}" {% endif %}{% if meta.content %} content="{{ meta.content }}" {% endif %}{% endif %}>
{% endfor %}
```

Which now outputs HTML:

```
<meta name="generator" content="GravCMS" >
<meta charset="utf-8">
<meta http-equiv="x-ua-compatible">
<meta name="description" content="Page description" >
```

With this method however, I am unable - apart from coding it into the twig template add content="ie=edge" so that the full meta appears like this:

```
<meta http-equiv="x-ua-compatible" content="ie=edge">
```

As i've used http-equiv's content for the first property, I'm not sure how I can create a second other than adding more if else to the twig code.

None of this is holding me back, I've got a more elaborate partial in place, I just wanted to try to extrapolate the data from the page or site.yaml if at all possible to make it more flexible in the future and make the templates simpler and learn about grav in the process. Many thanks.

**Comment by flaviocopes** [comment]
https://github.com/getgrav/grav/pull/699 should fix `x-ua-compatible` https://github.com/getgrav/grav/pull/699. 

Charset on the other hand is a special one, should be hardcoded in the theme header?

**Comment by stephenvoisey** [comment]
Right now, that is exactly how the antimatter template is functioning, it's added in the template above the title. The metadata.html.twig partial is simply extracting any other properties and nothing is happening with http_equiv or the charset in the if statements that I can see. That in itself is useful, but it means the http_equiv and charset should be removed.

**Comment by rhukster** [comment]
Ok, this works with antimatter as-is (ie without your change) and a minor fix just commited:

```
metadata:
    charset: 'utf-8'
    x-ua-compatible: ie=edge
    content-type: 'text/html; charset=UTF-8'
    refresh: 30
    description: 'Your page "description" goes here'
    generator: Grav
    testkey: testvalue
    keywords: 'HTML, CSS, XML, JavaScript'
    author: 'John Smith'
    robots: 'noindex, nofollow'
    og: { title: 'The Rock', type: video.movie, url: 'http://www.imdb.com/title/tt0117500/', image: 'http://ia.media-imdb.com/images/rock.jpg' }
    fb: { app_id: your_facebook_app_id }
    'twitter:card': summary
    'twitter:site': '@flickr'
    'twitter:title': 'Your Page Title'
    'twitter:description': 'Your page description can contain summary information'
    'twitter:image': 'https://farm6.staticflickr.com/5510/14338202952_93595258ff_z.jpg'
```
