### ISSUE TITLE
Problem with translations? 

### ISSUE THREAD

**Issue by moreplavec** [getgrav/grav#703]
I downloaded skeleton of this theme: https://github.com/getgrav/grav-skeleton-receptar-site, which has in templates tags like:

```
placeholder="{{ 'SEARCH_FIELD'|t }}"
<a href="{{ page.url }}">{{ 'READ_MORE'|t }}</a>
```

and others. In the theme root, there is file languages.yaml with content for czech translation:

```
cs:
  SITE:
    TITLE: Můj blog
    DESCRIPTION: Blogování o všem možném
    COPYRIGHT: © Copyright %s Moje společnost
  SUBSCRIBE: Odebírat
  TWEET: Tweet
  SHARE: Sdílet
  MONTHS_OF_THE_YEAR: [Leden, Únor, Březen, Duben, Květen, Červen, Červenec, Srpen, Září, Říjen, Listopad, Prosinec]
  DAYS_OF_THE_WEEK: [Pondělí, Úterý, Středa, Čtvrtek, Pátek, Sobota, Neděle]
  READ_MORE: Číst dále
  SEARCH_FIELD: Hledaný výraz
```

But these variables are never used and if i add another, still stay untouched. Is it possible, that translations are not working?

Regards, Stanley
