### ISSUE TITLE
Site.description not working

### ISSUE THREAD

**Issue by nehero** [getgrav/grav#722]
```twig
{% if page.summary %}
  <meta name="description" content="{{ page.summary | striptags }}">
{% else %}
  <meta name="description" content="{{ site.description }}">
{% endif %}
```

Site description is set in `/user/config/site.yaml` but does not show up via `{{site.description}}`

Tried removing the conditional and just setting the 

    <meta name="description" content="{{ site.description }}">

But still won't work. Description tag comes up as blank string in html.

**Comment by flaviocopes** [comment]
Just tried, works for me, are you sure you cleared the cache or cache is disabled?

**Comment by nehero** [comment]
Yup. Cleared the cache on both the grav admin and tested in chrome + safari

**Comment by flaviocopes** [comment]
Cannot replicate! Tried on Antimatter.

**Comment by nehero** [comment]
Definitely an issue with site.description, though I'm not sure why. If I just simply replace

```javascript
{% if page.summary %}
  <meta name="description" content="{{ page.summary | striptags }}">
{% else %}
  <meta name="description" content="{{ site.description }}">
{% endif %}
```

with a hard-coded value:

```javascript
{% if page.summary %}
  <meta name="description" content="{{ page.summary | striptags }}">
{% else %}
  <meta name="description" content="Test Description">
{% endif %}
```

It works. Weird.

**Comment by rhukster** [comment]
What does your `site.yaml` look like?

**Comment by nehero** [comment]
```yaml
title: 'First Last'
author:
  name: 'First Last'
  email: example@email.com
taxonomies:
  - category
  - tag
metadata:
  description: 'This is a test description'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
```

All modified via the admin panel, not the file directly
