### ISSUE TITLE
Default author?

### ISSUE THREAD

**Issue by ghost** [getgrav/grav#74]
First and foremost, I'd like to say this — I am really enjoying working with Grav and I thank you wholeheartedly for your efforts! :+1: 

My question is this - Is there a way to add, for all site's pages, by default, an author?

E.g., I've tried adding this to `system.yaml` (last two lines):

```
pages:
  theme: antimatter
  process:
    markdown: true
    twig: false
  metadata:
    author: Andre Lima
```

But Grav doesn't produce the `meta author` code I was assuming it would...
