### ISSUE TITLE
Can you give an example of using the `fetch_command` option for assets?

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#769]
Can you give an example of how to define closure in the `assets:fetch_command:` configuration option to work with the `$fetch_command` variable which is described in `Assets.php`?

**Comment by flaviocopes** [comment]
It's part of the Stolz's Assets library, which Grav Assets is based upon: https://github.com/Stolz/Assets/blob/master/API.md#fetch_command

**Comment by maxlysenko** [comment]
Thank you for the information.
But I'm still unable to define instance of Closure inside the `system.yaml`
Can you please help me with the example of how to achieve this.
```yaml
assets:
  css_pipeline: true
  css_minify: true 
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: false
  js_minify: true
  enable_asset_timestamp: false
  fetch_command: <what should be written here?>
```
