### ISSUE TITLE
btnLabel and sort attribute without function for list blueprint

### ISSUE THREAD

**Issue by tfeldmann** [getgrav/grav#779]
I have a page blueprint:
```yaml
title: PLUGIN_ADMIN.DEFAULT
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.references:
              name: references
              type: list
              label: References
              sort: 0
              btnLabel: Add reference
              fields:
                .company:
                  type: text
                  label: Company
                .description:
                  type: text
                  label: Description
                .url:
                  type: text
                  label: URL
                .logo:
                  label: Logo
                  type: pagemediaselect

```

This works, but the btnLabel and sort attribute of my list seem to be ignored.
I'm using the currently released grav download from the getgrav.org website.
