### ISSUE TITLE
@self.children and @self.descendants not filtering out folders

### ISSUE THREAD

**Issue by fvsch** [getgrav/grav#791]
Grav version: 1.0.10.

I have a `/news` page with subfolers (e.g. `/news/2016`) which contain pages I want to list in the `/news` page’s collection. I’m using this frontmatter:

```yaml
title: News
content:
    items:
        '@self.descendants'
    order:
        by: header.publish_date
        dir: desc
    limit: 5
    pagination: true
```

The resulting `page.collection()` returns all descendant folders, including folders that do not have a `.md` file. I would expect that, by default at least, it would only list pages (folders with a `.md` file).
