### ISSUE TITLE
Add a `sort_by_key_case_insensitive` twig filter

### ISSUE THREAD

**Issue by tfeldmann** [getgrav/grav#796]
You run into problems if you have a frontmatter like this and want to sort the companies by name:
```yaml
---
title: Referenzen
references:
    1:
        company: 'C'
    2:
        company: 'B'
    3:
        company: 'a'
    4:
        company: 'd'
---
```
because the included `sort_by_key` twig filter is case sensitive
```twig
{% for ref in page.header.references|sort_by_key('company') %}
{{ ref.company }}
{% endfor %}
```
will output `B C a d`.

At the moment you have to use a solution like:
```twig
{% set references = {} %}
{% for ref in page.header.references %}
    {% set references = references|merge({(ref.company|lower): ref}) %}
{% endfor %}

{% for ref in references|ksort %}
    <p>{{ ref.company }}</p>
{% endfor %}
```

but something like
```twig
{% for ref in page.header.references|sort_by_key_case_insensitive('company') %}
```
would be nicer, wouldn't it? Or use an optional argument like `sort_by_key('company', false)`?
