### ISSUE TITLE
issue with file type in THEME blueprint

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav#838]
Hello,

Can't success with file type in THEME blueprints, works with Plugin Blueprint
see that Gitter thread https://gitter.im/getgrav/grav?at=573b23a91794136a7d096f5c
Tested with master and develop branch
```` 
 type: tab
          title: THEME_LOGO
          fields:
            picture_src:
                type: file
                label: Picture file
                multiple: false
                destination: 'user/themes/my-theme/images'
                accept:
                    - image/*
````
