### ISSUE TITLE
Help tooltip on label markdown field type issue with translate or even simple string

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav#839]
Hi,
when using a help tooltip with markdown field , string is always surrounded by double quotes, and with translate var, no translation string from languages.yaml only the var surrounded by quotes.

Tested on Grav and admin develop branch (beta 4)

```
        header.map_content:
              type: markdown
              label: THEME_MYTHEME_MAP_CONTENT
              showPreview: true
              help: THEME_MYTHEME_MAP_CONTENT_HELP
              validate:
                type: textarea
```
