### ISSUE TITLE
Configuration merge problem

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#857]
The bare minimum to recreate this problem, e.g. in a plugin's default configuration (`plugins/comments/comments.yaml`)

``` yaml
comments_form:
    fields:
        -
            name: 1
        -
            name: 2
        -
            name: 3
```

In the custom user configuration (`user/config/plugins/comments.yaml`)

``` yaml
comments_form:
    fields:
        -
            name: test
```

If I do 

`{{dump(grav.config.plugins.comments.comments_form.fields)}}`

I get 

```
array:3 [
  0 => array:1 [
    "name" => "something"
  ]
  1 => array:1 [
    "name" => 2
  ]
  2 => array:1 [
    "name" => 3
  ]
]
```

**Buggy behavior**: The array is merged, the first item is entered instead of the first item of the original config, but the rest is still added.

**Expected behavior**: I should only get the config option set in the user folder:

```
array:1 [
  0 => array:1 [
    "name" => "something"
  ]
]
```

**Comment by flaviocopes** [comment]
I can't replicate this problem any more, must have been solved since it's been opened, in 1.1

**Comment by flaviocopes** [comment]
Not yet solved after some inspection of #1285 

The issue happens **only** when the plugin/theme blueprint defines the property as a `list` field.

**Comment by paulhibbitts** [comment]
Hi @flaviocopes , I wonder if any issue I am encountering is related? I have the following blueprint:

```
        -
            name: taxonomy.tag
            type: checkboxes
            label: 'Tag for Blog Post'
            options:
                tag1: 'Tag 1'
                tag2: 'Tag 2'
                tag3: 'Tag 3'
                tag4: 'Tag 4'
```

And the front matter generated looks like this:

```
---
taxonomy:
    tag:
        taxonomy.tag-tag1: tag1
        taxonomy.tag-tag3: tag3
---
```

What do you think? Is this an issue or am I missing something here?

Thanks very much,
Paul
