### ISSUE TITLE
Collections in frontmatter aren't able to filter by visible/published etc.

### ISSUE THREAD

**Issue by khanduras** [getgrav/grav#866]
```
cards:
    items:
        '@page.descendants.visible': /cards
    order:
        by: date
        dir: desc
    limit: 10
    pagination: true
```

What I find is that this ignores the `.visible` filter and non-visible pages count towards the limit count. I can filter using twig, however if you're expecting 10 pages you might get 9 if one of those pages were non-visible or non-published.
