### ISSUE TITLE
Blueprints not loaded

### ISSUE THREAD

**Issue by ArrowBaZ** [getgrav/grav#881]
Grav version 1.1.0-rc.1
Admin version 1.1.0-rc.2

In `user/pages/blueprints/modular` modular tab aren't add in modular page admin interface.
Workarround : `user/theme/antimatter/blueprints/modular`.

In `user/theme/antimatter/blueprints/pages` new tab aren't load in pages interface.
Workarround : `user/pages/blueprints/pages`.

**Comment by flaviocopes** [comment]
If you want to provide page blueprints outside of the theme, you need to put them into `user/blueprints/pages`. In the case of modular, put them in `user/blueprints/pages/modular`.

In the theme, put pages blueprints directly into `blueprints`, not `blueprints/pages`.

**Comment by ArrowBaZ** [comment]
Oh thanks, my bad, i miss this part of documentation.

**Comment by maximelebreton** [comment]
blueprints in `user/theme/antimatter/blueprints/pages` works
but same blueprints in `user/blueprints/pages` doesn't...

any idea?

**Comment by rhukster** [comment]
Are you sure you don't have the same blueprint in your theme?  The theme's `user/theme/antimatter/blueprint/pages` will override the one set in `user/blueprints/pages`.  

If you want to override a default blueprint coming from the theme, you really should create your own theme by inheriting antimatter: https://learn.getgrav.org/themes/customization#theme-inheritance

**Comment by maximelebreton** [comment]
yep, sure, and it doesn't appears on the admin 'page templates' list...

**Comment by rhukster** [comment]
hmm.. ok let me test..

**Comment by rhukster** [comment]
Ok, works fine for me.. 

here's what i did:

1) created a new page `custom.md` with this:

```
---
title: "Blueprints not loaded #881"
---

This page uses the `custom` template.  Blueprint should be loaded from `user/blueprints/pages/custom.yaml`
```

2) created a simple twig template to render it in `user/themes/antimatter/templates/custom.html.twig`:

```
{% extends 'partials/base.html.twig' %}

{% block content %}
    {{ content }}
{% endblock %}
```

3) created a form blueprint to test with in `user/blueprints/pages/custom.yaml`:

```
title: Custom
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:

      fields:
        content:
          unset@: true
        options:
          unset@: true
        advanced:
          unset@: true

        custom:
          type: tab
          title: Custom

          fields:

            header.custom_field:
              type: text
              label: Text Field
```

Page rendered, and the custom form rendered too:

![edit blueprints not loaded 881 grav 2016-09-16 11-38-16](https://cloud.githubusercontent.com/assets/1084697/18595452/14ea84b6-7c02-11e6-86c1-558ed9229571.png)
