### ISSUE TITLE
dateRange without end date problem

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#898]
Hello!

This issue related to:
https://github.com/getgrav/grav/issues/274
https://github.com/getgrav/grav/pull/275

I'm trying to show some posts from blog to in a home modular page depending to start date and found a bug with `dateRange` filter. Blog has 2 posts with 2013 and 2016 years.

My section `frontmatter.yaml`:
```yaml
events:
    items:
        '@page': '/events'
    dateRange:
        start: 1/1/2012
        end: 1/1/2017
```

Markdown:
```twig
{% set events_collection = page.collection('events') %}

{% for event in events_collection %}
    <p>{{ event.title }}</p>
{% endfor %}
```

With this settings I see both posts, it's fine.

But without end date in `frontmatter.yaml`:
```
events:
    items:
        '@page': '/events'
    dateRange:
        start: 1/1/2012
```

I see no posts at all. 

Env:
* Grav v1.1.0-rc.1
