### ISSUE TITLE
Can't switch between all available languages (a case study)

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav#907]
Imagine we have the settings:

```yaml
languages:
  supported:
    - de
    - en
  include_default_lang: true
  translations: true
  translations_fallback: true
  session_store_active: true
  http_accept_language: true
  override_locale: true
```

then it is currently not possible with the latest version of Grav to switch freely between the available languages of the site. You can test it here https://benjamin-regler.de . The issue occurs for example for a browser, which only accepts the english version. At the first time of the visit, Grav finds it out and stores the language in the cookie. At the second time when you want to switch to the German site, Grav redirects you again to the English version of the site. I guess this has something to do with the `include_default_lang: true` option, but I'm not quite sure.
