### ISSUE TITLE
Custom order in page collection is not working if the Slug of page collection elements is defined

### ISSUE THREAD

**Issue by lid3rs** [getgrav/grav#947]
Tested on my project. I have 3 pages as page collections in my 4th page. The 4th page has:
```yaml
content:
  items: @self.children
  order:
    by: default
    custom:
      - web
      - logo
      - graphic_design
```

If the web, logo, graphic_design are having their slugs, then the custom order is not working, if the slug is removed, custom order is working again.
