### ISSUE TITLE
Blueprint: File upload in list

### ISSUE THREAD

**Issue by andlinger** [getgrav/grav#971]
I have following blueprint for a page:

```
title: Website
'@extends':
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      types: tabs
      active: 1

      fields:
        test:
          type: tab
          title: The Tab
          fields:
            header.test:
              type: list
              fields:
                .title:
                  type: text
                  label: Test
                .file:
                  type: file
                  label: A file
                  destination: 'assets'
                  blueprint: 'themes.theme'
                  accept:
                    - image/*
```

These blueprint results in a correct view:

![screenshot](https://cloud.githubusercontent.com/assets/1436448/17523690/ce0dbb08-5e5b-11e6-903d-07345fc04706.png)

But after uploading a file nothing happens. No file was copied in the destination directory neither any entry for member "file" is visible in the pages yaml file. 

If the file form is outside of the list everything works fine.
