### ISSUE TITLE
Trouble with ordering collections

### ISSUE THREAD

**Issue by jonathan-chin** [getgrav/grav#972]
I apologize ahead of time; I am very new to Grav, but have been coding with other platforms for many years (WordPress, CakePHP).

I have an index file in one of my user pages subdirectories (05.Blog). When my frontmatter is this:

```
content:
    items: @self.children
    limit: 10
    pagination: true
```

I get what is expected. The posts are, however, ordered alphabetically by the title (which, for a blog, doesn't make sense). I tried to specify ordering:

```
content:
    items: @self.children
    limit: 10
    order:
        by: date
        dir: desc
    pagination: true
```

But two things happen:
1) no posts show at all
2) the name of the category in my navbar goes from Blog to blog (lowercased). I don't expect adding an order to my collection to change the capitalization.

I tried looking through log files and I have debugging enabled, but I can't seem to find a relevant error message.
