### ISSUE TITLE
problem showing collection inside page

### ISSUE THREAD

**Issue by danielpetrica** [getgrav/grav#976]
How can I show a collection inside a page?
This is my .md page 

```
---
title: 'Quote Archive '
published: true
metadata:
    keywords: 'home'
taxonomy:
    category:
        - main
    tag:
        - 'home'
menu: 'Home'
slug: home
process:
    markdown: false
    twig: true
routable: true
cache_enable: true
visible: true
content:
    items: '@root'
---
 {% for p in page.collection %}
<h2> {{ p.title }} </h2>
 {{ p.summary }}
 {% endfor %} 
```

this is the result:  
![screencapture-quotesarchive-xyz-en-1470944070522](https://cloud.githubusercontent.com/assets/4850686/17602123/81c02c98-600b-11e6-8d86-6d0ac59d192d.png)
 how can I not show the collection code before the collection?
