### ISSUE TITLE
user/config/media.yaml completely replaces, not extends, system/config/media.yaml

### ISSUE THREAD

**Issue by antoneliasson** [getgrav/grav#979]
Using Grav 1.1.2. While attempting to add a media type to user/config/media.yaml I found that when this file exists and has at least the `types:` element, system/config/media.yaml is disregarded and only user/config/media.yaml is read. Expected result is that system/config/media.yaml provides default values and user/config/media.yaml can be used to selectively override or extend these.

As an example, I expected this user/config/media.yaml to just add support for serving files with the eml extension:

```
types:
  eml:
    type: file
    mime: message/rfc822
```
Instead, this caused a *0 - Unsupported operand types* error. If I extend the config to the following:

```
types:
  defaults:
    type: file
    thumb: media/thumb.png
    mime: application/octet-stream
    image:
      filters:
        default:
          - enableProgressive

  eml:
    type: file
    mime: message/rfc822
```

the site works again, but attachments other than eml no longer work (for example, images are no longer embedded).

This may be related to issue #943 .

**Comment by rhukster** [comment]
This was actually a change we made in Grav 1.1.  The main reason behind it was that it was impossible to 'remove' a media type with the override mechanism we had previously.  Now you must copy the entire media file from `system/config/media.yaml` and then make your changes.  This is done automatically in the admin (as long as you don't already have an override).

So in your case, please copy the entire file, then add your `eml` entry at the end.  Unfortunately there is no simple way to make this backwards compatible because we have no way to know if you wanted to remove all the other entries or not.

Closing now, but feel free to comment or reopen if you have any further questions.

**Comment by antoneliasson** [comment]
Thanks for the explanation!

If I have to copy the entire file then I take the responsibility of later merging upstream changes to `system/config/media.yaml` into my `user/config/media.yaml`. I feel that doesn't save me any work compared to making the changes directly in `system/config/media.yaml`, keeping track of the change as a patch and then reapplying the patch after every Grav update (when the config supposedly gets overwritten).

When would you want to remove a media type? That implies that you would store files in `user/pages` that you don't want to be served, which doesn't make any sense to me.

**Comment by hughbris** [comment]
Like @antoneliasson, I was surprised by this behaviour, as it's inconsistent with the way most Grav config works. Not overbearing, but it puts the onus on developers to track changes to `media.yaml` in Grav core, unlike anything else I know of.

I see your problem with backwards compatibility. I think removing types is an edge case but should be supported. How about you create new YAML properties in both the system and `user/config/media.yaml`?

Spitballing:
```yaml
add_types:
  dwg:
    type: Drawing
    thumb: media/thumb.png
    mime: image/vnd.dwg
remove_types:
  - ai
  - wav
```
Switch to a new parent property name in `system/config/media.yaml` like `supported_types`.

Then you have a slightly complex merge expression to determine supported types, which checks for the legacy `types` first, then uses `supported_types` union `add_types`, and removes `remove_types`. Something like that.

Is that clear and is it viable?
