### ISSUE TITLE
Question: create different Modular Page/s from admin with custom modules/templates

### ISSUE THREAD

**Issue by p-h-i-l** [getgrav/grav#997]
In the documentation a `modular.md` is created as explained [here](https://learn.getgrav.org/content/modular#setting-up-the-primary-page). 

My Question is: 
Can i create two `modular pages` **from the backend**. One called `home` and one called e.g. `company`. **i dont** want to add this part of code in `home.zy.md` and `company.zy.md` everytime i create a modular page:

```
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _showcase
            - _highlights
            - _callout
            - _features
```

Can this be defined in the  `blueprint`  /  `template`  for a `modular page`? I cant find anything related to this in the docs... 

thanks
